'use strict'
const fs=require('fs')
const path=require('path')
const root=path.resolve(__dirname,'../..')
const push=fs.readFileSync(path.join(root,'app/push-notifications-s14.js'),'utf8')
const server=fs.readFileSync(path.join(root,'app/server-f17.js'),'utf8')
const client=fs.readFileSync(path.join(root,'app/public/notification-push-s14.js'),'utf8')
const sw=fs.readFileSync(path.join(root,'app/public/phase2-service-worker.js'),'utf8')
const alerts=fs.readFileSync(path.join(root,'app/public/wa-human-alerts.js'),'utf8')
const migration=fs.readFileSync(path.join(root,'supabase/migrations/20260817221500_wa_s14_web_push_notification_transport.sql'),'utf8')
const pkg=JSON.parse(fs.readFileSync(path.join(root,'app/package.json'),'utf8'))
function ok(cond,msg){if(!cond){console.error('WA S14 CONTRACT FAIL:',msg);process.exit(1)}}

ok(pkg.dependencies&&pkg.dependencies['web-push'],'web-push dependency missing')
ok(push.includes("webpush.generateVAPIDKeys()"),'VAPID generation missing')
ok(push.includes("aos_push_vapid_store_v1"),'VAPID Vault store RPC missing')
ok(push.includes("return { ok: true, version: 'AOS_PUSH_V1', configured: true, public_key: cfg.publicKey }"),'public config must expose public VAPID key only')
ok(!push.includes('public_key: cfg.publicKey, private_key'),'private VAPID key must never be returned to browser config')
ok(migration.includes("vault.create_secret(v_private, 'aos_push_vapid_private_v1'"),'VAPID private key must be stored in Supabase Vault')
ok(migration.includes("grant execute on function public.aos_push_vapid_config_v1(jsonb) to service_role"),'VAPID config RPC must be service-role only')
ok(migration.includes("revoke all on public.aos_push_subscriptions_v1 from anon, authenticated"),'push subscriptions must not be directly readable by anon/authenticated')

ok(server.includes("url.pathname === '/api/push/config'"),'push config endpoint missing')
ok(server.includes("url.pathname === '/api/push/subscribe'"),'push subscribe endpoint missing')
ok(server.includes("url.pathname === '/api/push/unsubscribe'"),'push unsubscribe endpoint missing')
ok(server.includes("verifyApp(req.headers['x-aos-app-token'], false)"),'push endpoints must bind subscription to authenticated ASCENDA actor')
ok(server.includes('res.writeHead(upstream.statusCode || 502, headers); res.end(responseBody)')&&server.includes('setImmediate(function()'),'push dispatch must be fail-open after webhook response')
ok(server.indexOf('res.writeHead(upstream.statusCode || 502, headers); res.end(responseBody)')<server.indexOf("setImmediate(function() {\n        push.dispatchWhatsAppEnvelope"),'Meta webhook ACK must precede Web Push dispatch')

ok(migration.includes("v_conv.state <> 'HUMAN_ACTIVE'"),'server target RPC must require HUMAN_ACTIVE')
ok(migration.includes("v_conv.last_message_direction <> 'INBOUND'"),'server target RPC must require inbound last message')
ok(migration.includes("v_conv.owner_user_id is null"),'server target RPC must require assigned owner')
ok(migration.includes("c.last_message_id=v_provider_id"),'push target must match the current provider message')
ok(push.includes("aos_push_dispatch_claim_v1"),'per-device dedupe claim missing')
ok(migration.includes('unique(subscription_id, dedupe_key)'),'push ledger unique dedupe constraint missing')
ok(push.includes("code === 404 || code === 410"),'stale Web Push subscription retirement missing')

ok(client.includes("'PushManager' in window"),'PushManager support gate missing')
ok(client.includes("Notification.permission==='granted'"),'automatic subscription must require previously granted permission')
ok(client.includes("Notification.permission!=='default'"),'permission gesture guard missing')
ok(client.includes("closest('#nav-admin-whatsapp,#nav-whatsapp-agent')"),'permission request must be tied to a user gesture')
ok(client.includes("reg.pushManager.subscribe({userVisibleOnly:true"),'browser Push subscription missing')
ok(sw.includes("self.addEventListener('push'"),'service-worker Push event missing')
ok(sw.includes("payload.version!=='AOS_PUSH_V1'"),'service worker must enforce versioned notification envelope')
ok(sw.includes("if(list.length){list.forEach"),'open ASCENDA clients must suppress duplicate system Web Push notification')
ok(sw.includes("self.registration.showNotification(title,opts)"),'closed-app system notification missing')
ok(sw.includes("u.pathname.indexOf('/api/push/')===0"),'service-worker app-token bridge must cover push APIs')

ok(alerts.includes("title='WhatsApp · '+safeSender(r)"),'WhatsApp notification sender identity missing')
ok(alerts.includes('body:safePreview(r)'),'WhatsApp notification preview sanitizer missing')
ok(alerts.includes("icon:'/icons/channel-whatsapp.svg'"),'WhatsApp channel icon missing')
ok(!alerts.includes('body:r.last_message_preview'),'raw preview must never bypass sanitizer')

const {createPushService}=require(path.join(root,'app/push-notifications-s14.js'))
const svc=createPushService({serviceRpc:async()=>({ok:true})})
const preview=svc.messagePreview({message_body:'  Hola\n\u0000mundo   '.repeat(30)})
ok(preview.length<=140,'preview must be truncated to 140 characters')
ok(!/[\u0000-\u001f\u007f]/.test(preview),'preview must remove control characters')
ok(svc.senderLabel({contact_name:'',contact_number:'51987654321'},{} )==='+51987654321','phone fallback must identify unknown WhatsApp contact')

console.log('WA S14 contract PASS')
