'use strict';
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'../..');
const alerts=fs.readFileSync(path.join(root,'app/public/wa-human-alerts.js'),'utf8');
const sw=fs.readFileSync(path.join(root,'app/public/phase2-service-worker.js'),'utf8');
function ok(cond,msg){if(!cond){console.error('WA S12 CONTRACT FAIL:',msg);process.exit(1);}}
ok(alerts.includes("r.owner_user_id===S.actorId"),'alerts must require current actor ownership');
ok(alerts.includes("r.state==='HUMAN_ACTIVE'"),'alerts must be HUMAN_ACTIVE only');
ok(alerts.includes("r.last_message_direction==='INBOUND'"),'alerts must be inbound only');
ok(!alerts.includes("r.state==='AI_COPILOT'&&"),'copilot must not qualify for human alerts');
ok(alerts.includes('reg.showNotification(title,opts)')||alerts.includes('new Notification(title,opts)'),'system notification missing');
ok(alerts.includes('AudioContext||window.webkitAudioContext'),'WebAudio chime missing');
ok(alerts.includes("title='WhatsApp · '+safeSender(r)"),'channel-aware WhatsApp title missing');
ok(alerts.includes('body:safePreview(r)'),'notification preview must pass through sanitizer');
ok(alerts.includes("replace(/[\\u0000-\\u001f\\u007f]+/g,' ')"),'preview control-character sanitizer missing');
ok(alerts.includes("slice(0,max||140)"),'preview truncation missing');
ok(!alerts.includes('body:r.last_message_preview'),'raw message preview must never be placed directly in notification');
ok(alerts.includes("icon:'/icons/channel-whatsapp.svg'"),'WhatsApp channel icon missing');
ok(alerts.includes("tag:'aos-wa-human-'"),'notification dedupe tag missing');
ok(alerts.includes("localStorage.setItem('aos_wa_selected',r.id)")||alerts.includes("localStorage.setItem('aos_wa_selected',id)"),'notification click must target conversation');
ok(alerts.includes("Notification.permission==='default'"),'permission request must be gated');
ok(sw.includes('/wa-human-alerts.js?v=20260817-wa-alerts-s13-p01')||sw.includes('/wa-human-alerts.js?v=20260817-wa-alerts-s14-p01'),'service worker must inject governed alerts asset');
console.log('WA S12 contract PASS');
