'use strict'
const fs=require('fs')
function read(p){return fs.readFileSync(p,'utf8')}
function ok(v,m){if(!v){console.error('CIA PACK-B CONTRACT FAIL:',m);process.exit(1)}}
const shell=read('app/public/clinic-shell-ui-v1.js')
const workspace=read('app/public/cia-audience-workspace-v3.js')
const perf=read('app/public/calls-performance-v1.js')
const q=read('app/public/cia-queue-gateway-v1.js')
const canary=read('supabase/migrations/20260917181548_cia_pack_b_reversible_canary_gateway_v2.sql')
const catalog=read('supabase/migrations/20260918015000_cia_audience_workspace_v3.sql')
const reliability=read('supabase/migrations/20260918231000_cia_workspace_canary_io_v1.sql')

ok(shell.includes('/cia-audience-workspace-v3.js?v=20260918-2'),'Audience Workspace V3 loader/cache-bust missing')
ok(!shell.includes('/cia-audience-control-center-v1.js?v=20260917-3'),'legacy Audience Center must not be the active shell asset')
ok(shell.includes('__AOS_CIA_INSTALL_AUDIENCE_BUTTON_V1__'),'shared shell observer must own CIA button install')

ok(workspace.includes('/rpc/aos_cia_control_center_app_v5'),'Audience Workspace must use reliability gateway V5')
ok(workspace.includes("'CATALOG_META'")&&workspace.includes("'REFRESH_CATALOG'"),'catalog-first metadata/count refresh missing')
ok(workspace.includes("'PREVIEW_CATALOG'")&&workspace.includes('limit:25'),'bounded cached preview path missing')
ok(workspace.includes("'EXPORT_CSV_FAST'"),'governed cached CSV export missing')
ok(workspace.includes("'ACTIVITY_SUMMARY'"),'activation/activity read model missing')
ok(workspace.includes("'START_CANARY_ASSIGNMENT'")&&workspace.includes('source_limit:1'),'one-contact Call Center test guard missing')
ok(workspace.includes("'STOP_CANARY_ASSIGNMENT'")&&workspace.includes('Cerrar prueba · volver a modo normal'),'Call Center rollback UI missing')
ok(workspace.includes("'CANARY_READBACK'")&&workspace.includes('Comprobar asignación'),'human-readable assignment verification missing')
ok(workspace.includes(".panels.indexOf('advisor-calls')>=0"),'advisor selector must be restricted to Call Center-enabled advisors')
ok(workspace.includes('__AOS_CIA_INSTALL_AUDIENCE_BUTTON_V1__')&&!workspace.includes('MutationObserver'),'workspace must reuse shell observer and not own a recurrent observer')
ok(!workspace.includes('confirm('),'native confirm is forbidden for assignment activation')
ok(!workspace.includes('setInterval('),'Audience Workspace must not poll')
ok(!workspace.includes('Human Canary')&&!workspace.includes('readback técnico')&&!workspace.includes('resolver v2'),'engineering labels must not leak into normal admin UX')
ok(workspace.includes('Audiencias')&&workspace.includes('Distribución')&&workspace.includes('Actividad')&&workspace.includes('Explorar'),'product workspaces missing')
ok(workspace.includes('loadMeta().catch')&&workspace.includes('loadBoot();loadLibrary();'),'catalog must load independently from bootstrap/library')

ok(catalog.includes('aos_audience_preset_runtime_cache_v1'),'catalog count cache missing')
ok(catalog.includes('aos_cia_catalog_refresh_counts_v1'),'explicit cached count refresh missing')
ok(catalog.includes('aos_cia_control_center_app_v3'),'additive catalog gateway missing')
ok(catalog.includes('CATALOG_META')&&catalog.includes('EXPORT_CSV')&&catalog.includes('ACTIVITY_SUMMARY'),'catalog/export/activity actions missing')
ok(catalog.includes('aos_cia_catalog_assignment_stale_guard_v1'),'stale audience fail-closed guard missing')

ok(canary.includes('aos_cia_control_center_app_v2'),'reversible canary gateway V2 migration missing')
ok(reliability.includes('aos_cia_control_center_app_v5'),'reliability gateway V5 migration missing')
ok(reliability.includes('aos_cia_contact_runtime_cache_v1')&&reliability.includes('aos_cia_contact_runtime_refresh_v1'),'contact runtime cache missing')
ok(reliability.includes('aos_cia_activation_context_bind_admin_v1'),'canary context bind is required before assignment plan creation')
ok(reliability.indexOf('aos_cia_activation_context_bind_admin_v1')<reliability.indexOf('aos_cia_assignment_plan_create_admin_v1'),'context must be bound before plan creation')
ok(!reliability.includes('START_DISTRIBUTION'),'reliability patch must not enable bulk distribution')
ok(canary.includes('CANARY_SOURCE_LIMIT_MUST_BE_ONE'),'one-contact DB hard bound missing')
ok(canary.includes('CANARY_ALREADY_ACTIVE')&&canary.includes('ROUTING_NOT_BASELINE'),'single-canary/baseline guards missing')
ok(canary.includes("v_cia_token,'SET_ADVISOR'")&&canary.includes("v_cia_token,'SET_GLOBAL'"),'routing arm operations missing')
ok(canary.indexOf("v_cia_token,'SET_ADVISOR'")<canary.indexOf("v_cia_token,'SET_GLOBAL'"),'selected advisor must be armed before global router is enabled')
ok(canary.includes("v_action='STOP_CANARY_ASSIGNMENT'")&&canary.includes("v_cia_token,'CLEAR_ADVISOR'"),'fail-closed canary rollback missing')
ok(perf.includes("fn==='aos_siguiente_lead_v2'?'aos_siguiente_lead_v3':fn"),'advisor selector does not route through V3 authority')
ok(perf.includes("var coalesceOnly=actual==='aos_siguiente_lead_v3'"),'V3 selector single-flight missing')
ok(q.includes("h.delete('Prefer')"),'queue RPC compatibility must strip legacy Prefer header')

console.log('CIA Audience Workspace V3 + reversible one-contact test contract: PASS')
