'use strict'
const fs=require('fs')
function read(p){return fs.readFileSync(p,'utf8')}
function ok(v,m){if(!v){console.error('CIA PACK-B CONTRACT FAIL:',m);process.exit(1)}}
const shell=read('app/public/clinic-shell-ui-v1.js')
const center=read('app/public/cia-audience-control-center-v2.js')
const perf=read('app/public/calls-performance-v1.js')
const q=read('app/public/cia-queue-gateway-v1.js')
const canary=read('supabase/migrations/20260917181548_cia_pack_b_reversible_canary_gateway_v2.sql')
const catalog=read('supabase/migrations/20260917195800_cia_audience_catalog_v2.sql')
ok(shell.includes('/cia-audience-control-center-v2.js?v=20260917-4'),'Audience Catalog V2 cache-bust missing')
ok(shell.includes('__AOS_CIA_INSTALL_AUDIENCE_BUTTON_V2__')||shell.includes('__AOS_CIA_INSTALL_AUDIENCE_BUTTON_V1__'),'shared shell observer must own CIA button install')
ok(center.includes('/rpc/aos_cia_control_center_app_v3'),'Audience Catalog must use additive gateway V3')
ok(center.includes("rpc('CATALOG_META'")&&center.includes('Catálogo vivo'),'catalog-first UX missing')
ok(center.includes("rpc('PREVIEW'")&&center.includes('limit:25'),'bounded audience preview missing')
ok(center.includes("rpc('PREVIEW_ALL'")&&center.includes('Todos los contactos'),'full-base governed preview missing')
ok(center.includes("rpc('EXPORT_CSV'")&&center.includes('Descargar CSV'),'governed CSV export missing')
ok(center.includes("rpc('LIST_AUDIENCES'")&&center.includes('loadLibrary'),'saved audience library path missing')
ok(center.includes("rpc('START_CANARY_ASSIGNMENT'")&&center.includes('source_limit:1'),'one-contact Human Canary guard missing')
ok(center.includes("rpc('STOP_CANARY_ASSIGNMENT'")&&center.includes('Cancelar prueba · volver a modo normal'),'Human Canary rollback UI missing')
ok(center.includes("rpc('CANARY_READBACK'")&&center.includes('Comprobar asignación'),'Human Canary readback UI missing')
ok(center.includes("a.panels.indexOf('advisor-calls')>=0"),'advisor selector must be restricted to Call Center-enabled advisors')
ok(center.includes('__AOS_CIA_INSTALL_AUDIENCE_BUTTON_V2__')&&!center.includes('MutationObserver'),'Audience Catalog must reuse shell observer and not own a recurrent observer')
ok(!center.includes('confirm('),'native confirm is forbidden for Human Canary activation')
ok(!center.includes('setInterval('),'Audience Catalog must not poll')
ok(center.includes('loadMeta().catch')&&center.includes('loadBoot();loadLibrary()'),'catalog must render independently from secondary library/bootstrap loads')
ok(catalog.includes('aos_cia_control_center_app_v3'),'catalog V3 gateway migration missing')
ok(catalog.includes("v_action not in ('CATALOG_META','PREVIEW_ALL','EXPORT_CSV')")&&catalog.includes('aos_cia_control_center_app_v2'),'V3 must delegate legacy/canary actions to V2')
ok(catalog.includes('EXPORT_LIMIT_EXCEEDED')&&catalog.includes('20000'),'CSV export hard bound missing')
ok(catalog.includes('aos_cia_audience_validate_v1')&&catalog.includes('aos_cia_audience_resolve_node_v2'),'CSV export must reuse governed resolver')
ok(catalog.includes('CALLED_NO_EFFECTIVE_CONTACT')&&catalog.includes('NEVER_APPOINTED')&&catalog.includes('DIAMOND_CUSTOMERS'),'curated live catalog seeds missing')
ok(canary.includes('CANARY_SOURCE_LIMIT_MUST_BE_ONE'),'one-contact DB hard bound missing')
ok(canary.includes('CANARY_ALREADY_ACTIVE')&&canary.includes('ROUTING_NOT_BASELINE'),'single-canary/baseline guards missing')
ok(canary.includes("v_cia_token,'SET_ADVISOR'")&&canary.includes("v_cia_token,'SET_GLOBAL'"),'routing arm operations missing')
ok(canary.indexOf("v_cia_token,'SET_ADVISOR'")<canary.indexOf("v_cia_token,'SET_GLOBAL'"),'selected advisor must be armed before global router is enabled')
ok(canary.includes("v_action='STOP_CANARY_ASSIGNMENT'")&&canary.includes("v_cia_token,'CLEAR_ADVISOR'"),'fail-closed canary rollback missing')
ok(perf.includes("fn==='aos_siguiente_lead_v2'?'aos_siguiente_lead_v3':fn"),'advisor selector does not route through V3')
ok(perf.includes("var coalesceOnly=actual==='aos_siguiente_lead_v3'"),'V3 selector single-flight missing')
ok(q.includes("h.delete('Prefer')"),'queue RPC compatibility must strip legacy Prefer header')
console.log('CIA PACK-B catalog-first reversible readiness contract: PASS')
