'use strict'
const fs=require('fs')
function read(p){return fs.readFileSync(p,'utf8')}
function ok(v,m){if(!v){console.error('CIA PACK-B CONTRACT FAIL:',m);process.exit(1)}}
const shell=read('app/public/clinic-shell-ui-v1.js')
const center=read('app/public/cia-audience-control-center-v1.js')
const perf=read('app/public/calls-performance-v1.js')
const q=read('app/public/cia-queue-gateway-v1.js')
const canary=read('supabase/migrations/20260917181548_cia_pack_b_reversible_canary_gateway_v2.sql')
ok(shell.includes('/cia-audience-control-center-v1.js?v=20260917-3'),'Audience Control Center V1.2 cache-bust missing')
ok(shell.includes('__AOS_CIA_INSTALL_AUDIENCE_BUTTON_V1__'),'shared shell observer must own CIA button install')
ok(center.includes('/rpc/aos_cia_control_center_app_v2'),'Audience Control Center must use reversible gateway V2')
ok(center.includes("rpc('COUNT'")&&center.includes("rpc('PREVIEW'")&&center.includes('limit:25'),'explicit bounded resolver UX missing')
ok(center.includes("rpc('CREATE_AUDIENCE'")&&center.includes("rpc('LIST_AUDIENCES'"),'Audience Library path missing')
ok(center.includes("rpc('START_CANARY_ASSIGNMENT'")&&center.includes('source_limit:1'),'one-contact Human Canary guard missing')
ok(center.includes("rpc('STOP_CANARY_ASSIGNMENT'")&&center.includes('Cancelar prueba · volver a modo normal'),'Human Canary rollback UI missing')
ok(center.includes("rpc('CANARY_READBACK'")&&center.includes('Verificar readback técnico'),'Human Canary readback UI missing')
ok(center.includes("a.panels.indexOf('advisor-calls')>=0"),'advisor selector must be restricted to Call Center-enabled advisors')
ok(center.includes('__AOS_CIA_INSTALL_AUDIENCE_BUTTON_V1__')&&!center.includes('MutationObserver'),'Audience Control Center must reuse shell observer and not own a recurrent observer')
ok(!center.includes('confirm('),'native confirm is forbidden for Human Canary activation')
ok(!center.includes('setInterval('),'Audience Control Center must not poll')
ok(center.includes('resetForPreset')&&center.includes("document.getElementById('cia-name')")&&center.includes('state.audience=null'),'preset switch must resync identity fields and invalidate stale audience selection')
ok(center.includes('isSilentError')&&center.includes('AbortError')&&center.includes('STALE_RESPONSE'),'replaced requests must not surface abort noise to the operator')
ok(center.includes('Primero calcula la audiencia')&&center.includes('state.count==null'),'audience save must require a successful bounded resolve')
ok(canary.includes('aos_cia_control_center_app_v2'),'reversible canary gateway V2 migration missing')
ok(canary.includes('CANARY_SOURCE_LIMIT_MUST_BE_ONE'),'one-contact DB hard bound missing')
ok(canary.includes('CANARY_ALREADY_ACTIVE')&&canary.includes('ROUTING_NOT_BASELINE'),'single-canary/baseline guards missing')
ok(canary.includes("v_cia_token,'SET_ADVISOR'")&&canary.includes("v_cia_token,'SET_GLOBAL'"),'routing arm operations missing')
ok(canary.indexOf("v_cia_token,'SET_ADVISOR'")<canary.indexOf("v_cia_token,'SET_GLOBAL'"),'selected advisor must be armed before global router is enabled')
ok(canary.includes("v_action='STOP_CANARY_ASSIGNMENT'")&&canary.includes("v_cia_token,'CLEAR_ADVISOR'"),'fail-closed canary rollback missing')
ok(perf.includes("fn==='aos_siguiente_lead_v2'?'aos_siguiente_lead_v3':fn"),'advisor selector does not route through V3')
ok(perf.includes("var coalesceOnly=actual==='aos_siguiente_lead_v3'"),'V3 selector single-flight missing')
ok(q.includes("h.delete('Prefer')"),'queue RPC compatibility must strip legacy Prefer header')
console.log('CIA PACK-B reversible canary readiness contract: PASS')
