'use strict';
// WA-4 outer boundary. Copilot only; WA-3 V2/V1 remain ownership/human-send authority.
const http=require('http'),https=require('https'),path=require('path');
const {spawn}=require('child_process');
const ai=require('./ai-router');
const {createCopilot}=require('./wa4-copilot');
const EXTERNAL_PORT=parseInt(process.env.PORT||'4173',10),INNER_PORT=EXTERNAL_PORT===4198?4199:4198;
const SB_URL=process.env.SUPABASE_URL||'https://ituyqwstonmhnfshnaqz.supabase.co',SB_ANON_KEY=process.env.SUPABASE_ANON_KEY||'',SB_SERVICE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||'';
const HOOK=path.join(__dirname,'legacy-groq-model-hook.js'),UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
let child=null,startupHealth={checked_at:null,configured:false,active:{},legacy_compat_ready:false,copilot_ready:false,error:'NOT_CHECKED'},healthExpiresAt=0;
function writeJson(res,status,obj){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Ascenda-WA4-AI':'v1'});res.end(JSON.stringify(obj));}
function readJson(req,max=262144){return new Promise((ok,bad)=>{let raw='',over=false;req.on('data',c=>{if(over)return;raw+=c;if(Buffer.byteLength(raw)>max)over=true;});req.on('end',()=>{if(over)return bad(Object.assign(new Error('PAYLOAD_TOO_LARGE'),{status:413}));try{ok(JSON.parse(raw||'{}'));}catch(_){bad(Object.assign(new Error('INVALID_JSON'),{status:400}));}});req.on('error',bad);});}
function parseData(raw){try{return raw?JSON.parse(raw):null;}catch(_){return null;}}
function sbRequest(method,endpoint,body,service,prefer){return new Promise((ok,bad)=>{const key=service?SB_SERVICE_KEY:SB_ANON_KEY;if(!key)return bad(Object.assign(new Error(service?'SUPABASE_SERVICE_ROLE_NOT_CONFIGURED':'SUPABASE_ANON_KEY_NOT_CONFIGURED'),{status:503}));let u;try{u=new URL(SB_URL);}catch(e){return bad(e);}const data=body==null?'':JSON.stringify(body),headers={apikey:key,Authorization:'Bearer '+key,'Content-Type':'application/json','User-Agent':'AscendaOS-WA4/1.0'};if(data)headers['Content-Length']=Buffer.byteLength(data);if(prefer)headers.Prefer=prefer;const q=https.request({hostname:u.hostname,port:u.port||443,path:endpoint,method,headers,timeout:12000},r=>{let raw='';r.on('data',c=>raw+=c);r.on('end',()=>{const out={status:r.statusCode||502,data:parseData(raw),raw};if(out.status>=200&&out.status<300)ok(out);else bad(Object.assign(new Error('WA4_DB_UNAVAILABLE'),{status:502,upstreamStatus:out.status,data:out.data}));});});q.on('timeout',()=>q.destroy(new Error('WA4_DB_TIMEOUT')));q.on('error',bad);if(data)q.write(data);q.end();});}
const sbRpc=(n,p)=>sbRequest('POST','/rest/v1/rpc/'+n,p,false),serviceRpc=(n,p)=>sbRequest('POST','/rest/v1/rpc/'+n,p,true),serviceGet=e=>sbRequest('GET',e,null,true),servicePost=(e,b)=>sbRequest('POST',e,b,true,'return=minimal');
function token(req){const t=String(req.headers['x-aos-app-token']||'').trim();return t.length>=32?t:'';}
async function actor(req){const t=token(req);if(!t)return null;try{const o=await sbRpc('aos_wa3_actor_v1',{p_token:t}),a=o.data;return a&&a.ok===true&&UUID_RE.test(String(a.actor_id||''))?a:null;}catch(_){return null;}}
async function requireActor(req,res,admin){const a=await actor(req);if(!a){writeJson(res,403,{ok:false,error:'WA4_2FA_PANEL_REQUIRED'});return null;}if(admin&&a.is_admin!==true){writeJson(res,403,{ok:false,error:'WA4_ADMIN_REQUIRED'});return null;}return a;}
async function getProviderSecret(tipo,nombreLike){const t=String(tipo||'').toLowerCase();if(!/^[a-z0-9_-]{2,32}$/.test(t))return '';try{const o=await serviceGet('/rest/v1/aos_integration_secrets_v1?tipo=eq.'+encodeURIComponent(t)+'&select=api_key,nombre&limit=20'),rows=Array.isArray(o.data)?o.data:[],r=nombreLike?rows.find(x=>String(x.nombre||'').toLowerCase().includes(String(nombreLike).toLowerCase())):rows[0],k=r&&typeof r.api_key==='string'?r.api_key:'';if(k.length>10)return k;}catch(_){}try{const o=await serviceGet('/rest/v1/aos_integraciones?tipo=eq.'+encodeURIComponent(t)+'&estado=eq.conectado&select=api_key,nombre&limit=20'),rows=Array.isArray(o.data)?o.data:[],r=nombreLike?rows.find(x=>String(x.nombre||'').toLowerCase().includes(String(nombreLike).toLowerCase())):rows[0];return r&&typeof r.api_key==='string'&&r.api_key.length>10?r.api_key:'';}catch(_){return '';}}
async function loadSecrets(){const [groq,gemini,openai,resend]=await Promise.all([getProviderSecret('groq'),getProviderSecret('gemini'),getProviderSecret('api','openai'),getProviderSecret('resend')]);return{groq,gemini,openai,resend};}
async function modelHealth(force){const now=Date.now();if(!force&&now<healthExpiresAt)return startupHealth;try{const key=(await loadSecrets()).groq;if(!key)throw new Error('GROQ_KEY_NOT_CONFIGURED');const m=await ai.listModels(key);startupHealth={checked_at:new Date().toISOString(),configured:true,models:ai.MODELS,active:m.active,legacy_compat_ready:m.active.fast===true&&m.active.reasoning===true,copilot_ready:m.active.fast===true&&m.active.reasoning===true&&m.active.safety===true,error:null};}catch(e){startupHealth={checked_at:new Date().toISOString(),configured:false,models:ai.MODELS,active:{},legacy_compat_ready:false,copilot_ready:false,error:String(e&&e.message||'MODEL_HEALTH_FAILED').slice(0,120)};}healthExpiresAt=now+300000;return startupHealth;}
async function authorize(req,id){const t=token(req);if(!t)return{ok:false,error:'WA4_2FA_PANEL_REQUIRED'};const o=await sbRpc('aos_wa4_authorize_copilot_v1',{p_token:t,p_conversation_id:id});return o.data||{};}
const suggest=createCopilot({serviceGet,servicePost,serviceRpc,authorize,getGroqKey:()=>getProviderSecret('groq'),modelHealth,writeJson});
async function bootstrap(req,res){const a=await requireActor(req,res,false);if(!a)return;try{const [c,h]=await Promise.all([serviceGet('/rest/v1/aos_wa_ai_control_v1?select=provider,fast_model,reasoning_model,safety_model,copilot_enabled,auto_reply_enabled,daily_budget_usd,max_context_messages,max_catalog_items,updated_at&id=eq.1'),modelHealth(false)]);writeJson(res,200,{ok:true,version:'WA4-V1',actor:{id:a.actor_id,is_admin:a.is_admin===true},control:Array.isArray(c.data)?c.data[0]||{}:{},health:h});}catch(_){writeJson(res,503,{ok:false,error:'WA4_BOOTSTRAP_UNAVAILABLE'});}}
async function control(req,res,body){const a=await requireActor(req,res,true);if(!a)return;const h=await modelHealth(false);if(body.copilot_enabled===true&&h.copilot_ready!==true)return writeJson(res,409,{ok:false,error:'WA4_MODELS_NOT_READY',health:h});try{const o=await serviceRpc('aos_wa4_admin_set_control_v1',{p_actor_id:a.actor_id,p_copilot_enabled:typeof body.copilot_enabled==='boolean'?body.copilot_enabled:null,p_daily_budget_usd:body.daily_budget_usd==null?null:Number(body.daily_budget_usd)});writeJson(res,o.data&&o.data.ok===false?409:200,o.data||{ok:false,error:'WA4_CONTROL_EMPTY'});}catch(_){writeJson(res,503,{ok:false,error:'WA4_CONTROL_UNAVAILABLE'});}}
function proxy(req,res){const q=http.request({hostname:'127.0.0.1',port:INNER_PORT,path:req.url,method:req.method,headers:Object.assign({},req.headers,{host:'127.0.0.1:'+INNER_PORT})},r=>{res.writeHead(r.statusCode||502,r.headers);r.pipe(res);});q.on('error',()=>{if(!res.headersSent)res.writeHead(502,{'Content-Type':'application/json'});res.end(JSON.stringify({ok:false,error:'WA4_UPSTREAM_UNAVAILABLE'}));});req.pipe(q);}
const proxyServer=http.createServer(async(req,res)=>{let u;try{u=new URL(req.url,'http://localhost');}catch(_){return writeJson(res,400,{ok:false,error:'INVALID_URL'});}const p=u.pathname;if(p==='/api/wa4/health'&&req.method==='GET')return writeJson(res,200,{ok:true,version:'WA4-V1',auto_send:false,health:await modelHealth(false)});if(p==='/api/wa4/bootstrap'&&req.method==='GET')return bootstrap(req,res);if(p==='/api/wa4/control'&&req.method==='POST'){try{return control(req,res,await readJson(req));}catch(e){return writeJson(res,e.status||400,{ok:false,error:e.message});}}const m=p.match(/^\/api\/wa4\/conversations\/([0-9a-f-]+)\/suggest$/i);if(m&&req.method==='POST'){try{await readJson(req);}catch(e){return writeJson(res,e.status||400,{ok:false,error:e.message});}return suggest(req,res,m[1]);}return proxy(req,res);});
proxyServer.on('clientError',(_,s)=>s.end('HTTP/1.1 400 Bad Request\r\n\r\n'));function shutdown(sig){proxyServer.close(()=>process.exit(0));if(child&&!child.killed)child.kill(sig);setTimeout(()=>process.exit(1),5000).unref();}process.on('SIGTERM',()=>shutdown('SIGTERM'));process.on('SIGINT',()=>shutdown('SIGINT'));
async function start(){const secrets=await loadSecrets(),h=await modelHealth(true),legacy=h.legacy_compat_ready===true&&!!secrets.groq,inherited=String(process.env.NODE_OPTIONS||'').trim(),nodeOptions=(inherited+' --require='+HOOK).trim();child=spawn(process.execPath,['server-wa3-v2.js'],{cwd:__dirname,env:Object.assign({},process.env,{PORT:String(INNER_PORT),NODE_OPTIONS:nodeOptions,ASCENDA_GROQ_COMPAT:legacy?'1':'0',GROQ_API_KEY:secrets.groq||'',GEMINI_API_KEY:secrets.gemini||'',OPENAI_API_KEY:process.env.OPENAI_API_KEY||secrets.openai||'',RESEND_API_KEY:process.env.RESEND_API_KEY||secrets.resend||''}),stdio:['ignore','inherit','inherit']});child.on('exit',code=>process.exit(code==null?1:code));proxyServer.listen(EXTERNAL_PORT,'0.0.0.0',()=>console.log('[WA4] listening',{external:EXTERNAL_PORT,inner:INNER_PORT,legacyCompat:legacy,copilotReady:h.copilot_ready===true}));}
start().catch(e=>{console.error('[WA4] startup failed',e.message);process.exit(1);});
