'use strict';
const fs = require('fs');
function read(path){ return fs.readFileSync(path, 'utf8'); }
function ok(condition, message){ if(!condition) throw new Error(message); }
const bridge = read('app/public/f4-revenue-ops.js');
const kronia = read('app/public/f4-kronia-revenue-bridge.js');
const sw = read('app/public/phase2-service-worker.js');
const proxy = read('app/server-f4.js');
const railway = read('app/railway.json');
const wa2 = fs.existsSync('app/server-wa2.js') ? read('app/server-wa2.js') : '';
const wa3 = fs.existsSync('app/server-wa3.js') ? read('app/server-wa3.js') : '';
const wa4 = fs.existsSync('app/server-wa4.js') ? read('app/server-wa4.js') : '';
const f5 = fs.existsSync('app/server-f5.js') ? read('app/server-f5.js') : '';
const phaseS = fs.existsSync('app/server-phase-s.js') ? read('app/server-phase-s.js') : '';
const core = read('supabase/migrations/20260814223000_f4_revenue_operations_core_v1.sql');
const carteraAuth = read('supabase/migrations/20260815191500_f4_cartera_gateway_v2_auth_chain_hotfix.sql');
const requiredBridge = ['aos_sales_admin_gateway_v4','aos_sales_admin_sale_v4','aos_editar_venta_v4','aos_importar_ventas_preview_v4','aos_importar_ventas_v4','aos_grabar_venta_caja_v4','/api/f4/cartera-candidates','aos_cartera_reconcile_v2','canonicalProductName','physicalQty','productResolutionStatus','REVIEW_REQUIRED','PAGO_RECONCILIADO','importApproval','carteraCandidateByCase'];
for(const marker of requiredBridge) ok(bridge.includes(marker), `missing F4 bridge marker: ${marker}`);
ok(bridge.includes("sessionStorage.getItem('aos_app_token')"), 'F4 must use the Auth V3 app token');
ok(!bridge.includes('aos_si_token'), 'F4 must not fall back to the Sales Intelligence token scope');
ok(sw.includes('/f4-revenue-ops.js'), 'service worker must inject F4 revenue bridge');
ok(sw.includes('/f4-kronia-revenue-bridge.js'), 'service worker must inject KronIA revenue proof bridge');
ok(!sw.includes("var CARTERA={aos_cartera_gateway:'aos_cartera_gateway_v2'}"), 'Cartera reads must not be re-proxied by the service worker');
ok(!sw.includes('CARTERA[rm[1]]'), 'Cartera service-worker interception must remain absent');
ok(carteraAuth.includes('select public.aos_cartera_gateway_v2('), 'DB compatibility alias must route legacy Cartera read to Auth V3 V2');
ok(kronia.includes("'/api/kronia/chat'") && kronia.includes('X-AOS-App-Token'), 'KronIA authenticated bridge contract missing');
ok(proxy.includes("body.confirmar_accion.rpc==='aos_editar_venta'"), 'server edit confirmation gate missing');
ok(proxy.includes('F4_STRONG_SESSION_REQUIRED'), 'strong-session guard missing');
ok(proxy.includes('aos_sales_admin_sale_v4') && proxy.includes('aos_editar_venta_v4'), 'server sales V4 RPC routing missing');
ok(proxy.includes("pathname==='/api/f4/cartera-candidates'"), 'cartera candidates route missing');
ok(proxy.includes('aos_cartera_candidates_v2'), 'cartera candidates RPC missing');
const directF4 = railway.includes('node server-f4.js');
const wa2WrappedF4 = railway.includes('node server-wa2.js') && wa2.includes("['server-f4.js']") && wa2.includes('proxy(req,res)');
const wa3WrappedChain = railway.includes('node server-wa3.js') && wa3.includes("['server-wa2.js']") && wa3.includes('proxy(req,res)') && wa2.includes("['server-f4.js']") && wa2.includes('proxy(req,res)');
const wa4WrappedChain = railway.includes('node server-wa4.js') && wa4.includes("['server-wa3.js']") && wa4.includes('proxy(req,res)') && wa3.includes("['server-wa2.js']") && wa3.includes('proxy(req,res)') && wa2.includes("['server-f4.js']") && wa2.includes('proxy(req,res)');
const f5WrappedChain = railway.includes('node server-f5.js') && f5.includes("['server-wa4.js']") && f5.includes('proxy(req,res)') && wa4.includes("['server-wa3.js']") && wa4.includes('proxy(req,res)') && wa3.includes("['server-wa2.js']") && wa3.includes('proxy(req,res)') && wa2.includes("['server-f4.js']") && wa2.includes('proxy(req,res)');
const phaseSWrappedChain = railway.includes('node server-phase-s.js') && phaseS.includes("['server-f5.js']") && phaseS.includes('proxy(req,res)') && f5.includes("['server-wa4.js']") && f5.includes('proxy(req,res)') && wa4.includes("['server-wa3.js']") && wa4.includes('proxy(req,res)') && wa3.includes("['server-wa2.js']") && wa3.includes('proxy(req,res)') && wa2.includes("['server-f4.js']") && wa2.includes('proxy(req,res)');
ok(directF4 || wa2WrappedF4 || wa3WrappedChain || wa4WrappedChain || f5WrappedChain || phaseSWrappedChain, 'Railway must preserve certified F4 chain through explicit WA/F5/Phase-S wrappers');
const preEnvironments = railway.split('"environments"')[0];
ok(!preEnvironments.includes('node server-phase2.js'), 'legacy phase2 server must not be production start command');
for(const text of [bridge,kronia]) ok(!text.toLowerCase().includes('service_role'), 'browser/runtime bridge must not contain service_role');
ok(proxy.includes('SUPABASE_SERVICE_ROLE_KEY'), 'server front boundary service role marker missing');
ok(proxy.includes('delete childEnv.SUPABASE_SERVICE_ROLE_KEY'), 'service role child isolation missing');
for(const marker of ['delete childEnv.WHATSAPP_VERIFY_TOKEN','delete childEnv.WHATSAPP_APP_SECRET','delete childEnv.WHATSAPP_ACCESS_TOKEN','delete childEnv.WHATSAPP_PHONE_NUMBER_ID','delete childEnv.WHATSAPP_GRAPH_VERSION','delete childEnv.WA_CANARY_MODE','delete childEnv.WA_CANARY_ALLOW_TO']) ok(proxy.includes(marker), `missing secret isolation marker: ${marker}`);
ok(core.includes("'rawDescription',e->>'descripcion'"), 'raw evidence e descripcion marker missing');
ok(core.includes("'rawDescription',v.descripcion"), 'raw evidence v descripcion marker missing');
ok(core.includes("'canonicalProductName'"), 'canonical product marker missing');
const carteraPage = read('app/public/admin-cartera.html');
const siPage = read('app/public/admin-sales-intelligence.html');
ok(proxy.includes("pathname==='/api/f4/cartera-read'") && proxy.includes("pathname==='/api/f4/sales-intelligence-read'"), 'F4 same-origin sensitive-read transport routes missing');
ok(proxy.includes("rpcName='aos_cartera_gateway'") && proxy.includes("rpcName='aos_sales_intelligence_gateway'"), 'F4 same-origin read RPC routing missing');
ok(proxy.includes('const appToken=strongToken(req)') && proxy.includes('F4_STRONG_SESSION_REQUIRED'), 'F4 same-origin read must require strong app token');
ok(carteraPage.includes("'/api/f4/cartera-read'") && carteraPage.includes("'X-AOS-App-Token':t"), 'Cartera same-origin transport missing');
ok(carteraPage.includes("caches.open('aos-phase2-auth')"), 'Cartera cache recovery missing');
ok(siPage.includes("'/api/f4/sales-intelligence-read'") && siPage.includes("'X-AOS-App-Token':token"), 'Sales Intelligence same-origin transport missing');
ok(siPage.includes("caches.open('aos-phase2-auth')"), 'Sales Intelligence cache recovery missing');
ok(!carteraPage.includes("api('aos_cartera_gateway'"), 'Cartera direct PostgREST read must remain absent');
ok(!siPage.includes("fetch(SB+'/rest/v1/rpc/aos_sales_intelligence_gateway'"), 'SI direct PostgREST read must remain absent');
console.log('F4 UI/runtime contract PASS');
