'use strict';
const fs=require('fs');
function repOnce(src,a,b,label){const n=src.split(a).length-1;if(n!==1)throw new Error((label||'needle')+' expected once, found '+n);return src.replace(a,b);}
function repN(src,a,b,n,label){const count=src.split(a).length-1;if(count!==n)throw new Error((label||'needle')+' expected '+n+', found '+count);return src.split(a).join(b);}

const panelPath='app/public/wa-native-panel.js';
let p=fs.readFileSync(panelPath,'utf8');
p=repOnce(p,`var S={root:null,viewId:'',boot:null,rows:[],filtered:[],selected:null,messages:[],pollInbox:null,pollMessages:null,leftOpen:true,rightOpen:true,search:'',composerSig:'',messageReqSeq:0};`,`var S={root:null,viewId:'',boot:null,rows:[],filtered:[],selected:null,messages:[],pollInbox:null,pollMessages:null,leftOpen:true,rightOpen:true,search:'',composerSig:'',messageReqSeq:0,provider:null,heartbeatBusy:false,heartbeatTick:0,focusHandler:null,visibilityHandler:null};`,'panel state');
p=repOnce(p,`<div class="wa8-status"><span>Bootstrap</span><b>'+esc((b.stability&&b.stability.mode)||'WA3')+'</b></div></div>';bindRight();}`,`<div class="wa8-status"><span>Bootstrap</span><b>'+esc((b.stability&&b.stability.mode)||'WA3')+'</b></div><div class="wa8-status"><span><i class="wa8-dot '+(S.provider&&S.provider.ok?'on':'off')+'"></i>Meta API</span><b>'+esc(S.provider?(S.provider.ok?'READY':(S.provider.diagnosis||S.provider.error||'ERROR')):'CHECK')+'</b></div></div>';bindRight();}`,'provider row');
p=repOnce(p,`function selectConversation(id){`,`function probeProvider(){if(!S.boot||!S.boot.actor||S.boot.actor.is_admin!==true)return Promise.resolve(null);return api('/api/wa3/provider-health').then(function(d){S.provider=d;renderRight();return d;}).catch(function(e){S.provider={ok:false,error:e.message||'META_PROVIDER_CHECK_FAILED',diagnosis:e&&e.data&&e.data.diagnosis||null,provider_details:e&&e.data&&e.data.provider_details||null};renderRight();return S.provider;});}\nfunction selectConversation(id){`,'provider probe');
p=repOnce(p,`}).catch(function(e){var detail=e&&e.data&&e.data.provider_details?(' · '+String(e.data.provider_details).slice(0,220)):'';toast('Envío bloqueado: '+e.message+detail,true);}).finally(function(){renderComposer(true);});}`,`}).catch(function(e){var detail=e&&e.data&&e.data.provider_details?(' · '+String(e.data.provider_details).slice(0,220)):'';if(e&&e.message==='META_190')probeProvider();toast('Envío bloqueado: '+e.message+detail,true);}).finally(function(){renderComposer(true);});}`,'send meta190 hook');
const oldStart=`function startPoll(){stopPoll();S.pollInbox=setInterval(function(){if(!S.root||document.hidden)return;refreshInbox().catch(function(e){if(e.status===403)setAuthError(e);});},3000);S.pollMessages=setInterval(function(){if(!S.root||document.hidden||!S.selected)return;loadMessages();},2200);}`;
const newStart=`function panelAlive(){var r=document.getElementById('aos-wa-native');if(!r)return false;if(S.root!==r)S.root=r;return true;}\nfunction heartbeat(force){if(!panelAlive()||(!force&&document.hidden)||S.heartbeatBusy)return Promise.resolve();S.heartbeatBusy=true;var beforeId=S.selected&&S.selected.last_message_id||'',beforeCount=Number(S.selected&&S.selected.message_count||0),beforeAt=String(S.selected&&S.selected.last_message_at||'');return refreshInbox().then(function(){S.heartbeatTick++;if(!S.selected)return;var changed=String(S.selected.last_message_id||'')!==String(beforeId)||Number(S.selected.message_count||0)!==beforeCount||String(S.selected.last_message_at||'')!==beforeAt;if(force||changed||S.heartbeatTick%3===0)return loadMessages();}).catch(function(e){if(e&&e.status===403)setAuthError(e);}).finally(function(){S.heartbeatBusy=false;});}\nfunction startPoll(){stopPoll();S.focusHandler=function(){heartbeat(true);};S.visibilityHandler=function(){if(!document.hidden)heartbeat(true);};window.addEventListener('focus',S.focusHandler);document.addEventListener('visibilitychange',S.visibilityHandler);S.pollInbox=setInterval(function(){heartbeat(false);},1500);heartbeat(true);}`;
p=repOnce(p,oldStart,newStart,'start heartbeat');
p=repOnce(p,`function stopPoll(){if(S.pollInbox)clearInterval(S.pollInbox);if(S.pollMessages)clearInterval(S.pollMessages);S.pollInbox=S.pollMessages=null;}`,`function stopPoll(){if(S.pollInbox)clearInterval(S.pollInbox);if(S.pollMessages)clearInterval(S.pollMessages);if(S.focusHandler)window.removeEventListener('focus',S.focusHandler);if(S.visibilityHandler)document.removeEventListener('visibilitychange',S.visibilityHandler);S.pollInbox=S.pollMessages=null;S.focusHandler=S.visibilityHandler=null;S.heartbeatBusy=false;}`,'stop heartbeat');
p=repOnce(p,`if(first)selectConversation(first.id);else{renderRight();renderComposer(true);}startPoll();}).catch(function(e){setAuthError(e);});}`,`if(first)selectConversation(first.id);else{renderRight();renderComposer(true);}if(S.boot&&S.boot.actor&&S.boot.actor.is_admin)probeProvider();startPoll();}).catch(function(e){setAuthError(e);});}`,'mount provider probe');
p=repOnce(p,`function unmount(){stopPoll();S.root=null;S.boot=null;S.rows=[];S.filtered=[];S.selected=null;S.messages=[];S.composerSig='';S.messageReqSeq++;}`,`function unmount(){stopPoll();S.root=null;S.boot=null;S.rows=[];S.filtered=[];S.selected=null;S.messages=[];S.provider=null;S.composerSig='';S.messageReqSeq++;S.heartbeatTick=0;}`,'unmount reset');
fs.writeFileSync(panelPath,p);

const wa3Path='app/server-wa3.js';
let w=fs.readFileSync(wa3Path,'utf8');
const providerCode=`function graphProviderGet(suffix){return new Promise((resolve,reject)=>{if(!WA_ACCESS_TOKEN||!/^v\\d+\\.\\d+$/.test(WA_GRAPH_VERSION))return reject(Object.assign(new Error('WA_PROVIDER_NOT_CONFIGURED'),{status:503,definite:true}));const q=https.request({hostname:'graph.facebook.com',path:'/'+WA_GRAPH_VERSION+'/'+suffix,method:'GET',headers:{Authorization:'Bearer '+WA_ACCESS_TOKEN,'Accept':'application/json','User-Agent':'AscendaOS-WA3/1.0'},timeout:12000},r=>{let raw='';r.on('data',c=>raw+=c);r.on('end',()=>{const d=parseData(raw)||{};if(r.statusCode>=200&&r.statusCode<300)return resolve(d);const me=d&&d.error||{},mc=String(me.code||'').trim(),md=String((me.error_data&&me.error_data.details)||me.message||'').slice(0,500);reject(Object.assign(new Error(mc?('META_'+mc):'META_PROVIDER_CHECK_FAILED'),{status:502,definite:true,metaStatus:r.statusCode,metaCode:mc||null,metaDetails:md||null}));});});q.on('timeout',()=>q.destroy(Object.assign(new Error('META_PROVIDER_TIMEOUT'),{status:504})));q.on('error',reject);q.end();});}\nfunction providerDiagnosis(e,stage){const c=String(e&&e.metaCode||'');if(c==='190')return 'TOKEN_INVALID_OR_EXPIRED';if(stage==='PHONE'&&c==='100')return 'PHONE_NUMBER_ID_INVALID_OR_INACCESSIBLE';if(c==='10'||c==='200')return 'PERMISSION_OR_ASSET_ACCESS';return 'META_PROVIDER_CHECK_FAILED';}\nasync function providerHealth(req,res){const a=await requireActor(req,res,true);if(!a)return;if(!WA_ACCESS_TOKEN||!WA_PHONE_NUMBER_ID||!/^v\\d+\\.\\d+$/.test(WA_GRAPH_VERSION))return writeJson(res,503,{ok:false,error:'WA_PROVIDER_NOT_CONFIGURED',diagnosis:'CONFIG_MISSING',access_token_present:!!WA_ACCESS_TOKEN,phone_number_id_present:!!WA_PHONE_NUMBER_ID,graph_version_present:/^v\\d+\\.\\d+$/.test(WA_GRAPH_VERSION)});try{await graphProviderGet('me?fields=id');}catch(e){return writeJson(res,e.status||502,{ok:false,error:e.message||'META_AUTH_CHECK_FAILED',diagnosis:providerDiagnosis(e,'TOKEN'),provider_http_status:e.metaStatus||null,provider_code:e.metaCode||null,provider_details:e.metaDetails||null});}try{const d=await graphProviderGet(encodeURIComponent(WA_PHONE_NUMBER_ID)+'?fields=id%2Cdisplay_phone_number%2Cverified_name');return writeJson(res,200,{ok:true,provider:'META',diagnosis:'READY',graph_version:WA_GRAPH_VERSION,phone_number_id:WA_PHONE_NUMBER_ID,display_phone_number:d.display_phone_number||null,verified_name:d.verified_name||null});}catch(e){return writeJson(res,e.status||502,{ok:false,error:e.message||'META_PHONE_CHECK_FAILED',diagnosis:providerDiagnosis(e,'PHONE'),provider_http_status:e.metaStatus||null,provider_code:e.metaCode||null,provider_details:e.metaDetails||null});}}\n\n`;
w=repOnce(w,`async function reserveOutbound(key,actorId,payload){`,providerCode+`async function reserveOutbound(key,actorId,payload){`,'provider diagnostic insert');
const bootRoute=`if(req.method==='GET'&&p==='/api/wa3/bootstrap')return await bootstrap(req,res);`;
w=repOnce(w,bootRoute,bootRoute+`\n  if(req.method==='GET'&&p==='/api/wa3/provider-health')return await providerHealth(req,res);`,'provider route');
fs.writeFileSync(wa3Path,w);

const phasePath='app/server-phase-s.js';
let ph=fs.readFileSync(phasePath,'utf8');
ph=repN(ph,'/wa-native-panel.js?v=20260817-wa-native-s10-p01','/wa-native-panel.js?v=20260817-wa-native-s11-p01',2,'phase native anchor');
ph=repN(ph,'/wa-shell-integration.js?v=20260817-wa-shell-s10-p01','/wa-shell-integration.js?v=20260817-wa-shell-s11-p01',2,'phase shell anchor');
fs.writeFileSync(phasePath,ph);

const shellPath='app/public/wa-shell-integration.js';
let sh=fs.readFileSync(shellPath,'utf8');
sh=repOnce(sh,"NATIVE_SRC='/wa-native-panel.js?v=20260817-wa-native-s10-p01'","NATIVE_SRC='/wa-native-panel.js?v=20260817-wa-native-s11-p01'",'shell native fallback');
fs.writeFileSync(shellPath,sh);
console.log('S11_LIVE_SYNC_META_AUTH_APPLIED');
