\set ON_ERROR_STOP on

-- Extend the existing Phase 2 synthetic fixture only. No production PII.
update public.aos_usuarios
set paneles_acceso=array['admin-sales-intelligence','admin-cartera','admin-caja','admin-team','admin-config']::text[],
    rol='admin',nivel_jerarquia=1,two_factor=true,activo=true
where codigo_asesor='CAROWNER';

insert into public.aos_rrhh(codigo_asesor,nombre,apellido,puesto,sede,usuario,password_hash,permisos,estado)
values('K1ADV','K1 ADVISOR','TEST','ASESOR','SAN ISIDRO','k1.advisor','advisor-pass-2026','{}','ACTIVO')
on conflict(codigo_asesor) do nothing;

insert into public.aos_usuarios(codigo_asesor,nombre,email,rol,paneles_acceso,nivel_jerarquia,sedes_permitidas,area,cargo,two_factor,activo)
values('K1ADV','K1 ADVISOR','advisor@example.invalid','asesor',array['ventas']::text[],4,array['SAN ISIDRO']::text[],'VENTAS','ASESOR',false,true)
on conflict(codigo_asesor) do nothing;

-- Production-shaped configuration metadata used by K1. Values are synthetic.
create table if not exists public.aos_configuracion (
  clave text primary key,
  valor text,
  descripcion text,
  updated_at timestamptz default now(),
  updated_by text
);
insert into public.aos_configuracion(clave,valor,descripcion)
values ('seg_2fa_habilitado','true','synthetic K1 2FA setting'),
       ('k1_public_setting','enabled','synthetic non-secret setting')
on conflict(clave) do nothing;

alter table public.aos_integraciones add column if not exists cuenta text default '';
alter table public.aos_integraciones add column if not exists config jsonb;
alter table public.aos_integraciones add column if not exists created_at timestamptz default now();
alter table public.aos_integraciones add column if not exists categoria text;
alter table public.aos_integraciones add column if not exists icono text;
alter table public.aos_integraciones add column if not exists descripcion text;
alter table public.aos_integraciones add column if not exists api_secret text;
alter table public.aos_integraciones add column if not exists webhook_url text;
alter table public.aos_integraciones add column if not exists pasos_guia jsonb;
alter table public.aos_integraciones add column if not exists uso_para text[] default ARRAY[]::text[];
alter table public.aos_integraciones add column if not exists orden integer default 0;
alter table public.aos_integraciones add column if not exists url_api text;
alter table public.aos_integraciones add column if not exists url_docs text;
alter table public.aos_integraciones add column if not exists url_signup text;
alter table public.aos_integraciones add column if not exists multi_cuenta boolean default false;
alter table public.aos_integraciones add column if not exists logo_url text;

-- Legacy KronIA/agent/audit stores that K1 locks down. Structural fixture only.
create table if not exists public.aos_kronia_tokens (
  id bigint generated by default as identity primary key,token text,usuario text,id_asesor text,rol text,sede text,email text,
  device_info text,ip_origen text,emitido_at timestamptz default now(),expira_at timestamptz,ultimo_uso timestamptz,
  revocado boolean default false,origen text
);
create table if not exists public.aos_kronia_acciones (
  id text primary key default extensions.gen_random_uuid()::text,usuario text,rol text,accion text,objeto_tipo text,objeto_id text,
  cambios jsonb,resultado text,exitoso boolean,session_id text,created_at timestamptz default now()
);
create table if not exists public.aos_kronia_conversaciones (
  id bigint generated by default as identity primary key,ts timestamptz default now(),usuario text,rol text,sede text,pregunta text,
  intencion text,tablas_usadas text[],respuesta text,fue_exitosa boolean,fue_redundante boolean,session_id text,metadata jsonb
);
create table if not exists public.aos_agente_logs (
  id text primary key default extensions.gen_random_uuid()::text,agente_id text,tarea_id text,accion text,input_resumen text,
  output_resumen text,resultado jsonb,motor_usado text,modelo_usado text,tokens_input integer,tokens_output integer,
  costo_usd numeric,duracion_ms integer,exitoso boolean,error text,created_at timestamptz default now()
);
create table if not exists public.aos_agente_acciones (
  id uuid primary key default extensions.gen_random_uuid(),agente_id text,tipo_accion text,descripcion text,metadata jsonb,
  created_at timestamptz default now()
);
create table if not exists public.aos_log_auditoria (
  id bigint generated by default as identity primary key,timestamp_reg timestamptz default now(),asesor text,accion text,
  referencia text,detalle text,ts timestamptz default now(),tabla text,usuario text,registro_id text,datos_new jsonb,datos_old jsonb,metadata jsonb
);

-- Legacy raw RPCs are implementation dependencies that K1 must revoke from the browser.
-- Parameter names/defaults and result types mirror production so CREATE OR REPLACE
-- is compatible even when Phase 2 already materialized one of these routines.
create or replace function public.aos_editar_venta(p_venta_id bigint,p_campos jsonb,p_editado_por text,p_rol text default 'asesor',p_origen text default 'manual') returns jsonb language sql security definer set search_path='' as $$select jsonb_build_object('ok',true)$$;
create or replace function public.aos_kronia_agregar_nota_paciente(p_numero_paciente text,p_nota text,p_usuario text) returns jsonb language sql security definer set search_path='' as $$select jsonb_build_object('ok',true)$$;
create or replace function public.aos_kronia_buscar_cita(p_filtro text,p_usuario text,p_rol text default 'asesor') returns jsonb language sql security definer set search_path='' as $$select jsonb_build_object('ok',true)$$;
create or replace function public.aos_kronia_buscar_paciente(p_filtro text) returns jsonb language sql security definer set search_path='' as $$select jsonb_build_object('ok',true)$$;
create or replace function public.aos_kronia_buscar_venta(p_filtro text,p_usuario text,p_rol text default 'asesor') returns jsonb language sql security definer set search_path='' as $$select jsonb_build_object('ok',true)$$;
create or replace function public.aos_kronia_editar_cita(p_cita_id bigint,p_campos jsonb,p_usuario text,p_rol text default 'asesor') returns jsonb language sql security definer set search_path='' as $$select jsonb_build_object('ok',true)$$;
create or replace function public.aos_kronia_editar_paciente(p_paciente_id text,p_campos jsonb,p_usuario text) returns jsonb language sql security definer set search_path='' as $$select jsonb_build_object('ok',true)$$;
create or replace function public.aos_kronia_explorar(p_modulo text,p_accion text,p_params jsonb default '{}'::jsonb) returns jsonb language sql security definer set search_path='' as $$select jsonb_build_object('ok',true)$$;
create or replace function public.aos_kronia_marcar_estado_cita(p_cita_id bigint,p_nuevo_estado text,p_usuario text,p_rol text default 'asesor') returns jsonb language sql security definer set search_path='' as $$select jsonb_build_object('ok',true)$$;
create or replace function public.aos_kronia_reprogramar_seguimiento(p_seg_id text,p_nueva_fecha text,p_nueva_hora text,p_usuario text,p_rol text default 'asesor') returns jsonb language sql security definer set search_path='' as $$select jsonb_build_object('ok',true)$$;
create or replace function public.aos_kronia_obtener_insights_sofia() returns jsonb language sql security definer set search_path='' as $$select jsonb_build_object('ok',true)$$;
create or replace function public.aos_kronia_stats_agenda() returns jsonb language sql security definer set search_path='' as $$select jsonb_build_object('ok',true)$$;
create or replace function public.aos_kronia_stats_leads() returns jsonb language sql security definer set search_path='' as $$select jsonb_build_object('ok',true)$$;
create or replace function public.aos_kronia_stats_llamadas() returns jsonb language sql security definer set search_path='' as $$select jsonb_build_object('ok',true)$$;
create or replace function public.aos_kronia_stats_pacientes() returns jsonb language sql security definer set search_path='' as $$select jsonb_build_object('ok',true)$$;
create or replace function public.aos_kronia_limpiar_tokens_expirados() returns jsonb language sql security definer set search_path='' as $$select jsonb_build_object('ok',true,'deleted',0)$$;
create or replace function public.aos_kronia_emitir_token(p_usuario text,p_id_asesor text default null,p_rol text default 'ASESOR',p_sede text default null,p_email text default null,p_device_info text default null,p_ip_origen text default null) returns jsonb language sql security definer set search_path='' as $$select jsonb_build_object('ok',true,'token','synthetic-token')$$;
create or replace function public.aos_kronia_verify_token(p_token text) returns jsonb language sql security definer set search_path='' as $$select jsonb_build_object('ok',true)$$;
create or replace function public.aos_kronia_revocar_token(p_token text) returns jsonb language sql security definer set search_path='' as $$select jsonb_build_object('ok',true)$$;

grant execute on function public.aos_editar_venta(bigint,jsonb,text,text,text) to anon,authenticated,service_role;
grant execute on function public.aos_kronia_agregar_nota_paciente(text,text,text) to anon,authenticated,service_role;
grant execute on function public.aos_kronia_buscar_cita(text,text,text) to anon,authenticated,service_role;
grant execute on function public.aos_kronia_buscar_paciente(text) to anon,authenticated,service_role;
grant execute on function public.aos_kronia_buscar_venta(text,text,text) to anon,authenticated,service_role;
grant execute on function public.aos_kronia_editar_cita(bigint,jsonb,text,text) to anon,authenticated,service_role;
grant execute on function public.aos_kronia_editar_paciente(text,jsonb,text) to anon,authenticated,service_role;
grant execute on function public.aos_kronia_explorar(text,text,jsonb) to anon,authenticated,service_role;
grant execute on function public.aos_kronia_marcar_estado_cita(bigint,text,text,text) to anon,authenticated,service_role;
grant execute on function public.aos_kronia_reprogramar_seguimiento(text,text,text,text,text) to anon,authenticated,service_role;
grant execute on function public.aos_kronia_obtener_insights_sofia() to anon,authenticated,service_role;
grant execute on function public.aos_kronia_stats_agenda() to anon,authenticated,service_role;
grant execute on function public.aos_kronia_stats_leads() to anon,authenticated,service_role;
grant execute on function public.aos_kronia_stats_llamadas() to anon,authenticated,service_role;
grant execute on function public.aos_kronia_stats_pacientes() to anon,authenticated,service_role;
grant execute on function public.aos_kronia_limpiar_tokens_expirados() to anon,authenticated,service_role;
grant execute on function public.aos_kronia_emitir_token(text,text,text,text,text,text,text) to anon,authenticated,service_role;
grant execute on function public.aos_kronia_verify_token(text) to anon,authenticated,service_role;
grant execute on function public.aos_kronia_revocar_token(text) to anon,authenticated,service_role;
grant all on public.aos_kronia_tokens,public.aos_kronia_acciones,public.aos_kronia_conversaciones,public.aos_agente_logs,public.aos_agente_acciones,public.aos_log_auditoria to anon,authenticated,service_role;
grant all on public.aos_configuracion to anon,authenticated,service_role;

-- Known 2FA app token for owner-admin gateway tests. This is a synthetic CI token.
insert into public.aos_app_sessions_v3(token_hash,user_id,assurance_level,expires_at,revoked)
select encode(extensions.digest('k1-owner-app-token-00000000000000000000000001','sha256'),'hex'),id,'PASSWORD_2FA',now()+interval '8 hours',false
from public.aos_usuarios where codigo_asesor='CAROWNER';

-- Advisor token for negative/positive non-admin control-plane tests.
insert into public.aos_app_sessions_v3(token_hash,user_id,assurance_level,expires_at,revoked)
select encode(extensions.digest('k1-advisor-app-token-000000000000000000000001','sha256'),'hex'),id,'PASSWORD',now()+interval '8 hours',false
from public.aos_usuarios where codigo_asesor='K1ADV';
