'use strict'
const fs=require('fs')
const runtime=fs.readFileSync('app/public/advisor-break-persistence-v1.js','utf8')
const sw=fs.readFileSync('app/public/phase2-service-worker.js','utf8')
const app=fs.readFileSync('app/public/app.html','utf8')
function ok(v,m){if(!v){console.error('BREAK PERSISTENCE CONTRACT FAIL:',m);process.exit(1)}}
ok(runtime.includes("KEY='aos_blocking_state_v1'"),'persistent blocking-state key missing')
ok(runtime.includes("userId:user"),'blocking state must be bound to advisor identity')
ok(runtime.includes("startedAt:Number(startedAt)||Date.now()"),'blocking state timestamp missing')
ok(runtime.includes("Date.now()-Number(s.startedAt)"),'timer must derive from persisted timestamp')
ok(runtime.includes("p.p_estado==='LOGEADO'&&state"),'login state overwrite guard missing')
ok(runtime.includes("p_estado:state.estado"),'active blocking state must win over LOGEADO')
ok(runtime.includes("window.addEventListener('pageshow'"),'pageshow restore missing')
ok(runtime.includes("document.addEventListener('visibilitychange'"),'visibility restore missing')
ok(runtime.includes("window.terminarEstadoBloqueante=function()"),'finish hook missing')
ok(runtime.includes("clear();"),'finish must clear persisted state')
ok(runtime.includes("MAX_AGE=12*60*60*1000"),'stale state bound missing')
ok(sw.includes('/advisor-break-persistence-v1.js?v=20260915-p01'),'service worker must inject break persistence runtime')
ok(app.includes("p_estado:'LOGEADO'"),'test expects legacy shell login state write to remain intercepted rather than rewritten')
ok(app.includes("function activarOverlayEstado("),'blocking overlay authority missing')
console.log('BREAK persistence V1 contract: PASS')
