'use strict'
const fs=require('fs')
const path=require('path')
const root=path.resolve(__dirname,'../..')
function read(p){return fs.readFileSync(path.join(root,p),'utf8')}
function ok(v,m){if(!v)throw new Error(m)}

const migration=read('supabase/migrations/20260912073000_app_pwa_v2_device_registry.sql')
const rollback=read('supabase/rollback/20260912073000_app_pwa_v2_device_registry_rollback.sql')
const runtime=read('app/public/aos-device-runtime-v2.js')
const panel=read('app/public/admin-device-center-v2.html')
const api=read('app/device-api-v2.js')
const contract=read('docs/control/ASCENDA_APP_PWA_V2_CONTRACT_517.md')
const panelRegistry=read('supabase/migrations/20260912164500_app_pwa_v2_device_center_panel_registry.sql')
const panelRegistryRollback=read('supabase/rollback/20260912164500_app_pwa_v2_device_center_panel_registry_rollback.sql')
const rolloutRepair=read('app/public/app-pwa-device-center-rollout.js')
const phaseS=read('app/server-phase-s.js')
const pushClient=read('app/public/notification-push-s14.js')
const push=read('app/push-notifications-s14.js')
const adminMigration=read('supabase/migrations/20260914125000_app_pwa_admin_push_console.sql')
const adminRollback=read('supabase/rollback/20260914125000_app_pwa_admin_push_console_rollback.sql')
const idempotency=read('supabase/migrations/20260914130500_s15_push_idempotent_completion.sql')
const login=read('app/public/login.html')
const brain=read('app/public/cerebro.html')
const agents=read('app/public/agents.html')
const manifest=JSON.parse(read('app/public/manifest.json'))

ok(migration.includes('create table if not exists public.aos_devices_v1'),'device registry missing')
ok(migration.includes('unique(user_id, installation_id)'),'stable user+installation identity missing')
ok(migration.includes('add column if not exists device_id uuid'),'push->device bridge missing')
ok(migration.includes('create table if not exists public.aos_app_presence_v1'),'app presence table missing')
ok(migration.includes('aos_effective_presence_v1'),'effective presence RPC missing')
ok(migration.includes('HEARTBEAT_STALE'),'stale presence cutoff missing')
ok(migration.includes('revoke all on public.aos_devices_v1 from anon, authenticated'),'device table must not be browser-readable')
ok(migration.includes('grant execute on function public.aos_device_upsert_v1(jsonb) to service_role'),'device upsert must remain service-role only')
ok(migration.includes('aos_devices_actor_v1'),'actor-bound device listing missing')
ok(migration.includes('aos_device_preferences_actor_v1'),'actor-bound preferences missing')

ok(api.includes("b.user_id = a.actor_id"),'registration must overwrite browser user identity')
ok(api.includes("b.actor_id = a.actor_id"),'device mutations must be actor-bound')
ok(api.includes("verifyApp(req.headers['x-aos-app-token'], false)"),'device API must verify ASCENDA app token')
ok(!api.includes('graph.facebook.com'),'device API must not depend on Meta')
ok(!api.includes('/api/wa/send'),'device API must not alter WhatsApp send path')

ok(runtime.includes("localStorage.getItem(KEY)"),'installation identity must persist locally')
ok(runtime.includes("matchMedia('(display-mode: standalone)')"),'PWA installed surface detection missing')
ok(runtime.includes("badge_supported:typeof n.setAppBadge==='function'"),'Badge capability detection missing')
ok(runtime.includes("document.visibilityState==='visible'"),'visibility capability missing')
ok(!runtime.includes('supabase.co'),'browser device runtime must not call Supabase directly')
ok(!runtime.includes('apikey'),'browser device runtime must not embed an API key')

ok(panel.includes('Dispositivos y Notificaciones'),'Spanish panel name missing')
ok(panel.includes("'X-AOS-App-Token'"),'panel must use actor-bound same-origin API')
ok(panel.includes('/api/devices/register'),'device registration UI missing')
ok(panel.includes('/api/devices/preferences'),'device preference UI missing')
ok(panel.includes("window.AOS_PUSH.enable"),'local notification consent must enroll Web Push immediately')
ok(pushClient.includes("reg.showNotification('ASCENDA · Prueba local'"),'Push owner must use Service Worker notification for Android/PWA local test')
ok(panel.includes("window.AOS_PUSH.localTest"),'Device Center must delegate local system notification to Push owner')
ok(!panel.includes('supabase.co'),'device center must not call Supabase directly')
ok(!panel.includes('graph.facebook.com'),'device center must not call Meta')
ok(panel.includes('/api/devices/admin/overview'),'admin fleet overview UI missing')
ok(panel.includes('/api/devices/admin/test'),'admin targeted Push test UI missing')
ok(panel.includes('Probar a todos'),'admin fleet broadcast diagnostic control missing')
ok(api.includes('aos_push_admin_overview_v1'),'admin overview endpoint missing')
ok(api.includes('adminTestTargets'),'admin Push test endpoint missing')
ok(push.includes("priority: text(n && n.priority"),'generic Push payload must propagate priority to service worker')
ok(push.includes("force_system: true"),'admin Push diagnostics must force OS notification')
ok(pushClient.includes('advisorOnboarding'),'advisor guided Push onboarding missing')
ok(adminMigration.includes("categoria='admin'"),'Device Center registry must become admin-only')
ok(adminMigration.includes("array_remove(coalesce(paneles_acceso"),'advisor Device Center assignments must be revoked')
ok(adminMigration.includes('aos_push_admin_overview_v1'),'admin fleet RPC missing')
ok(adminMigration.includes('aos_push_admin_targets_v1'),'admin Push target RPC missing')
ok(adminRollback.includes("categoria='asesor'"),'admin console rollback must restore registry category')
ok(idempotency.includes("'deduped',true"),'dispatch claim must expose deduped readback')
ok(idempotency.includes("when n.push_status='DELIVERED' then 'DELIVERED'"),'notification completion must never downgrade DELIVERED')
ok(push.includes("claim && claim.status || '').toUpperCase() === 'DELIVERED'"),'Push runtime must treat deduped delivered dispatch as delivered')
ok(phaseS.includes('/app-pwa-device-center-rollout.js?v=20260914-rollout-p01'),'Phase S must inject Device Center rollout repair')
ok(rolloutRepair.includes("AOS.role!=='ADMIN'"),'rollout repair must stay admin-scoped')
ok(rolloutRepair.includes("p.indexOf(PANEL_ID)<0"),'rollout repair must restore missing Device Center panel in admin shell')
ok(rolloutRepair.includes("localStorage.getItem('aos_session')"),'rollout repair must persist refreshed admin panel context')

const shell=read('app/public/app.html')
const advisorSidebar=shell.split('var SIDEBAR_ASESOR = [')[1].split('];')[0]
const adminSidebar=shell.split('var SIDEBAR_ADMIN = [')[1].split('];')[0]
ok(!advisorSidebar.includes("id:'devices-notifications'"),'advisor sidebar must not expose Device Center')
ok(adminSidebar.includes("id:'devices-notifications',ico:'settings',lbl:'Dispositivos y avisos'"),'admin sidebar must expose Device Center')
ok(shell.includes("viewId === 'devices-notifications' && AOS.role !== 'ADMIN'"),'direct Device Center navigation must be admin-only')
const sourceShell=read('src/frontend/app.html')
const sourceAdvisorSidebar=sourceShell.split('var SIDEBAR_ASESOR = [')[1].split('];')[0]
ok(!sourceAdvisorSidebar.includes("id:'devices-notifications'"),'source advisor sidebar must not expose Device Center')
ok(sourceShell.includes("'devices-notifications':'ViewDeviceCenter'"),'source shell device-center view mapping missing')
ok(sourceShell.includes("'ViewDeviceCenter':       '/admin-device-center-v2.html'"),'source shell device-center route missing')

ok(contract.includes('Notifications are side effects'),'side-effect isolation contract missing')
ok(contract.includes('No mass replay.'),'backlog anti-replay gate missing')
ok(contract.includes('time_outside_app_sec'),'call duration semantics gate missing')
ok(login.includes('<link rel="manifest" href="/manifest.json">'),'login must expose the installable manifest')
ok(login.includes("navigator.serviceWorker.register('/phase2-service-worker.js'"),'login must register the canonical PWA service worker before authentication')
ok(login.includes("PENDING_KEY='aos_auth_pending_v1'"),'mobile 2FA challenge resume state missing')
ok(login.includes('autocomplete="one-time-code"'),'OTP field must expose native one-time-code autocomplete semantics')
ok(!shell.includes('Notification.requestPermission();'),'app shell must not auto-request notification permission')
ok(!agents.includes('Notification.requestPermission();'),'agents panel must not auto-request notification permission')
ok(pushClient.includes('SamsungBrowser'),'Push onboarding must identify Samsung Internet')
ok(pushClient.includes('Ya lo habilité'),'blocked Push permission must provide a recovery flow')
ok(pushClient.includes('no pedir Push por clicks laterales'),'navigation clicks must not opportunistically request Push permission')
ok(login.includes('SamsungBrowser'),'login install onboarding must identify Samsung Internet')
ok(login.includes('Instalar apps desconocidas'),'Samsung install failure must include Android recovery guidance')
ok(pushClient.includes('20260915-samsung-push-p02')===false,'Push client source must not self-couple to cache version')
ok(login.includes("clearPending();message('Código verificado.'"),'successful 2FA must clear pending challenge state')
const pendingSave=login.split('function savePending(){')[1].split('function clearPending(){')[0]
ok(!pendingSave.includes('loginPass')&&!pendingSave.includes('password'),'pending 2FA state must never persist the password')
ok(!brain.includes('reg.unregister()'),'KronIA must never unregister the shared Ascenda service worker')
ok(!brain.includes('caches.delete(n)'),'KronIA must never purge shared Ascenda PWA caches')
ok(manifest.id==='/app'&&manifest.scope==='/'&&manifest.display==='standalone','manifest identity/scope/install mode regression')

ok(rollback.includes('drop table if exists public.aos_devices_v1'),'device rollback missing')
ok(rollback.includes('drop function if exists public.aos_devices_actor_v1(jsonb)'),'actor RPC rollback missing')
ok(panelRegistry.includes("'devices-notifications'"),'governed device-center panel registry missing')
ok(!panelRegistry.includes("update public.aos_usuarios"),'original panel registry must not auto-grant access')
ok(panelRegistryRollback.includes("array_remove(coalesce(paneles_acceso"),'device-center panel rollback must revoke assignments')
ok(panelRegistryRollback.includes("delete from public.aos_paneles_disponibles"),'device-center panel rollback must remove registry row')

console.log('APP-PWA-V2 #517 contract: PASS')
