'use strict'
const fs=require('fs');
const path='app/server-f4.js';
let src=fs.readFileSync(path,'utf8');
function once(oldText,newText,label){const n=src.split(oldText).length-1;if(n!==1)throw new Error(label+': expected 1 match, found '+n);src=src.replace(oldText,newText)}

once("const wa=require('./wa-gateway');","const wa=require('./wa-gateway');\nconst {createF17WhatsAppAdapter}=require('./f17-whatsapp-adapter');",'adapter import');

once("const data=body==null?'':JSON.stringify(body);const headers={apikey:SB_SERVICE_KEY,Authorization:'Bearer '+SB_SERVICE_KEY,'Content-Type':'application/json','User-Agent':'AscendaOS-WA-Gateway/1.0'};","const data=body==null?'':JSON.stringify(body);const headers={apikey:SB_SERVICE_KEY,'Content-Type':'application/json','User-Agent':'AscendaOS-WA-Gateway/1.0'};if(String(SB_SERVICE_KEY).split('.').length===3)headers.Authorization='Bearer '+SB_SERVICE_KEY;",'secret-key compatibility');

once("function strongToken(req){const t=String(req.headers['x-aos-app-token']||'').trim();return t.length>=32?t:'';}","async function sbServiceRpc(name,payload){const out=await sbService('POST','/rest/v1/rpc/'+encodeURIComponent(name),payload||{});return out.data;}\nconst F17_WA=createF17WhatsAppAdapter({serviceRpc:sbServiceRpc});\nfunction strongToken(req){const t=String(req.headers['x-aos-app-token']||'').trim();return t.length>=32?t:'';}",'adapter wiring');

once("  for(const ev of envelope.events){await sbService('POST','/rest/v1/aos_wa_events_v1?on_conflict=event_key',ev,'resolution=ignore-duplicates,return=minimal');}\n}","  for(const ev of envelope.events){await sbService('POST','/rest/v1/aos_wa_events_v1?on_conflict=event_key',ev,'resolution=ignore-duplicates,return=minimal');}\n  for(const m of envelope.messages){await F17_WA.recordInbound(m);}\n  for(const ev of envelope.events){\n    const first=await F17_WA.recordEvent(ev);\n    if(first&&first.matched===true&&ev.event_type==='message.status'){\n      const replay=await F17_WA.recordEvent(ev);\n      if(first.inserted===true&&replay&&replay.inserted===false){await F17_WA.setGate('WEBHOOK_REPLAY_VALIDATED','Signed Meta webhook event persisted once; immediate exact normalized replay returned inserted=false');}\n      if(first.context&&first.context.canary===true&&['sent','delivered','read'].includes(String(ev.status||'').toLowerCase())){await F17_WA.setGate('CANARY_PASSED','Allowlisted governed WhatsApp canary received signed Meta '+String(ev.status||'')+' status');}\n    }\n  }\n}",'webhook bridge');

once("  if(!wa.canaryAllows(payload.to,WA_CANARY_MODE,WA_CANARY_ALLOW_TO)){writeJson(res,403,{ok:false,error:'WA_CANARY_RECIPIENT_BLOCKED'});return;}\n  let reservation;","  if(!wa.canaryAllows(payload.to,WA_CANARY_MODE,WA_CANARY_ALLOW_TO)){writeJson(res,403,{ok:false,error:'WA_CANARY_RECIPIENT_BLOCKED'});return;}\n  let f17Prepared;\n  try{f17Prepared=await F17_WA.prepare({to:payload.to,actor:actor,idempotencyKey:body.idempotency_key,messageClass:payload.type,canary:String(WA_CANARY_MODE).toLowerCase()==='true'});}catch(e){writeJson(res,e.message==='F17_POLICY_SEND_BLOCKED'?403:503,{ok:false,error:e.message||'F17_POLICY_UNAVAILABLE'});return;}\n  let reservation;",'policy before transport');

once("    if(!reservation.owner){\n      const row=reservation.row||{};\n      writeJson(res,row.state==='FAILED'?409:200,{ok:row.state!=='FAILED',idempotent:true,message_id:row.provider_message_id||null,status:row.state||'PENDING',error:row.state==='FAILED'?(row.error_code||'PREVIOUS_SEND_FAILED'):undefined});return;\n    }","    if(!reservation.owner){\n      const row=reservation.row||{};\n      if(row.state==='ACCEPTED'&&row.provider_message_id){try{await F17_WA.markAccepted(f17Prepared.request_id,row.provider_message_id);}catch(_){}}\n      writeJson(res,row.state==='FAILED'?409:200,{ok:row.state!=='FAILED',idempotent:true,message_id:row.provider_message_id||null,status:row.state||'PENDING',error:row.state==='FAILED'?(row.error_code||'PREVIOUS_SEND_FAILED'):undefined});return;\n    }",'idempotent repair');

once("    await sbService('PATCH','/rest/v1/aos_wa_outbound_requests_v1?idempotency_key=eq.'+encodeURIComponent(body.idempotency_key),{state:'ACCEPTED',provider_message_id:String(messageId),error_code:null,updated_at:new Date().toISOString()},'return=minimal');","    await sbService('PATCH','/rest/v1/aos_wa_outbound_requests_v1?idempotency_key=eq.'+encodeURIComponent(body.idempotency_key),{state:'ACCEPTED',provider_message_id:String(messageId),error_code:null,updated_at:new Date().toISOString()},'return=minimal');\n    await F17_WA.markAccepted(f17Prepared.request_id,String(messageId));\n    await F17_WA.recordEvent({provider_message_id:String(messageId),event_key:'f17:accepted:'+String(messageId),event_type:'message.accepted',status:'accepted',payload:{transport:'META_WHATSAPP'}});",'accepted ledger');

once("    if(reservation&&reservation.owner&&e.definite===true){try{await sbService('PATCH','/rest/v1/aos_wa_outbound_requests_v1?idempotency_key=eq.'+encodeURIComponent(body.idempotency_key),{state:'FAILED',error_code:String(e.message||'WA_SEND_FAILED').slice(0,128),updated_at:new Date().toISOString()},'return=minimal');}catch(_e){}}","    if(reservation&&reservation.owner&&e.definite===true){try{await sbService('PATCH','/rest/v1/aos_wa_outbound_requests_v1?idempotency_key=eq.'+encodeURIComponent(body.idempotency_key),{state:'FAILED',error_code:String(e.message||'WA_SEND_FAILED').slice(0,128),updated_at:new Date().toISOString()},'return=minimal');}catch(_e){}try{if(f17Prepared&&f17Prepared.request_id)await F17_WA.markFailed(f17Prepared.request_id,e.message||'WA_SEND_FAILED');}catch(_f17){}}",'failed ledger');

if(!src.includes('F17_WA.prepare'))throw new Error('policy wiring missing');
if(!src.includes('WEBHOOK_REPLAY_VALIDATED'))throw new Error('replay gate wiring missing');
if(!src.includes('CANARY_PASSED'))throw new Error('canary gate wiring missing');
if(!src.includes("split('.').length===3"))throw new Error('secret key compatibility missing');
fs.writeFileSync(path,src);
console.log('F17 governed WA adapter materialized');
