-- Synthetic contract for FASE 2 Cartera. No production data or identities.

alter table public.aos_ventas
  add column if not exists moneda text default 'PEN',
  add column if not exists cotizacion_id text,
  add column if not exists plan_id text,
  add column if not exists created_at timestamptz default now();

create table public.aos_cotizaciones (
  id text primary key default extensions.gen_random_uuid()::text,
  numero_cotizacion integer generated by default as identity,
  numero_limpio text not null,
  nombre_paciente text,
  dni_paciente text,
  estado text default 'CREADO',
  subtotal numeric(14,2) default 0,
  total_pagado numeric(14,2) default 0,
  saldo_pendiente numeric(14,2) default 0,
  sede text,
  asesor text,
  id_asesor text,
  doctor_responsable text,
  nota_interna text,
  nota_paciente text,
  fecha_creacion date default current_date,
  fecha_pago_completo date,
  venta_legacy_id text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  plan_id text,
  origen text default 'MANUAL'
);

alter table public.aos_ventas
  add constraint aos_ventas_cotizacion_fk
  foreign key (cotizacion_id) references public.aos_cotizaciones(id);

create table public.aos_cotizacion_items (
  id text primary key default extensions.gen_random_uuid()::text,
  cotizacion_id text references public.aos_cotizaciones(id),
  tipo text default 'SERVICIO',
  descripcion text default '',
  cantidad integer default 1,
  precio_unitario numeric(14,2) default 0,
  subtotal numeric(14,2) default 0,
  estado_entrega text default 'EN_ESPERA',
  created_at timestamptz default now(),
  estado_pago text default 'PAGO COMPLETO',
  nombre text,
  metodo_pago text,
  moneda text default 'PEN',
  monto_pagado numeric(14,2) default 0,
  plan_item_id text,
  sesiones_programadas integer default 0,
  sesiones_completadas integer default 0,
  frecuencia text,
  proxima_sesion date
);

create table public.aos_pagos (
  id text primary key default extensions.gen_random_uuid()::text,
  cotizacion_id text references public.aos_cotizaciones(id),
  monto numeric(14,2) not null,
  moneda text default 'PEN',
  metodo_pago text not null,
  tipo_comprobante text default 'BOLETA',
  numero_comprobante text,
  sede text,
  almacen text,
  registrado_por text,
  fecha_pago date default current_date,
  nota text,
  created_at timestamptz default now(),
  asesor_comision text,
  item_id text
);

create table public.aos_caja_sesiones (
  id text primary key default extensions.gen_random_uuid()::text,
  sede text not null,
  fecha date not null default current_date,
  estado text not null default 'ABIERTA',
  abierto_por text,
  cerrado_por text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table public.aos_caja_log (
  id uuid primary key default extensions.gen_random_uuid(),
  sesion_id text,
  sede text,
  accion text,
  entidad_tipo text,
  entidad_id text,
  usuario text,
  detalle text,
  monto_despues numeric(14,2),
  created_at timestamptz default now()
);

create or replace function public.aos_abonar_cotizacion(
  p_cotizacion_id text,
  p_monto numeric,
  p_metodo_pago text,
  p_tipo_comprobante text default 'BOLETA VIRTUAL',
  p_nro_doc text default '',
  p_sede text default 'SAN ISIDRO',
  p_usuario text default 'CAJA',
  p_asesor text default '',
  p_nota text default '',
  p_sesion_id text default null,
  p_fecha text default null
) returns jsonb language sql as $$ select jsonb_build_object('ok',false) $$;

grant execute on function public.aos_abonar_cotizacion(
  text,numeric,text,text,text,text,text,text,text,text,text
) to anon,authenticated,service_role;
