'use strict';
const fs = require('fs');
function read(path){ return fs.readFileSync(path, 'utf8'); }
function ok(condition, message){ if(!condition) throw new Error(message); }
const app = read('app/public/app.html');
const cartera = read('app/public/admin-cartera.html');
const caja = read('app/public/caja.html');
const migration = read('supabase/migrations/20260814034401_cartera_phase2_reconciliation.sql');
const cleanup = read('supabase/migrations/20260814050000_cartera_phase2_security_cleanup.sql');
const rollback = read('supabase/rollbacks/20260814034401_cartera_phase2_reconciliation.rollback.sql');
ok(/id\s*:\s*['"]admin-cartera['"]/.test(app), 'admin-cartera menu id missing');
ok(/admin-cartera[\s\S]{0,220}requiresPanel\s*:\s*true/.test(app), 'admin-cartera panel gate missing');
ok(/['"]admin-cartera['"]\s*:\s*['"]ViewAdminCartera['"]/.test(app), 'admin-cartera view mapping missing');
ok(/['"]ViewAdminCartera['"]\s*:\s*['"]\/admin-cartera\.html['"]/.test(app), 'admin-cartera route missing');
ok(/viewId\s*===\s*['"]admin-cartera['"]/.test(app), 'admin-cartera view activation missing');
for(const marker of ['aos_cartera_gateway','aos_cartera_reconcile','p_expected_updated_at:current.updatedAt','aos_si_token','RECORDATORIOS BLOQUEADOS','Adelantos ≠ deuda']) ok(cartera.includes(marker), `missing Cartera marker: ${marker}`);
ok(caja.includes("rpc('aos_abonar_cotizacion_v2'"), 'secure quote payment RPC missing');
ok(/p_token\s*:\s*financeToken/.test(caja), 'finance token missing from quote payment');
ok(/p_idempotency_key\s*:/.test(caja), 'idempotency key missing');
ok(caja.includes('aos_caja_cotizaciones_gateway'), 'quote gateway missing');
ok(!/rpc\(['"]aos_abonar_cotizacion['"]/.test(caja), 'legacy quote payment RPC must be absent');
ok(!/sbGet\(['"]aos_cotizaciones['"]/.test(caja), 'direct quotes table read must be absent');
ok(caja.length > 150000, 'caja.html unexpectedly small');
for(const anchor of ['id="ov-venta"','function cargarCaja(','function buscarPaciente(q)','function finalizarGrabado()']) ok(caja.includes(anchor), `missing caja anchor: ${anchor}`);
ok(!caja.includes('onclick="selPaciente('), 'unsafe inline patient onclick remains');
ok(caja.includes("row.addEventListener('click', function(){ selPaciente(p); })"), 'safe patient click handler missing');
ok(!caja.includes('JSON.stringify(r).replace(/"/g'), 'unsafe JSON inline catalog handler remains');
ok(caja.includes("row.addEventListener('click', function(){ agregarItemDesdeCatalogo(r); })"), 'safe catalog click handler missing');
ok(caja.includes("row.addEventListener('click', function(){ cargarCotEnVenta(cot.id); })"), 'safe quote click handler missing');
ok(caja.includes("advisor.textContent = 'Asesor: ' + cot.asesor"), 'advisor textContent contract missing');
ok(caja.includes("escH(plan.autor || '')"), 'plan author escaping missing');
ok(caja.includes("escH(item.nombre || '')"), 'item name escaping missing');
ok(caja.includes('suggestion.textContent = value'), 'suggestion textContent missing');
ok(caja.includes("suggestion.addEventListener('click'"), 'suggestion click handler missing');
ok(caja.includes('badgeDetail.textContent = pendientes.length'), 'pending badge textContent missing');
ok(caja.includes("badge.addEventListener('click'"), 'badge click handler missing');
ok(caja.includes('precioVariante.toFixed(2)'), 'variant price formatting missing');
ok(caja.includes('precioItem.toFixed(2)'), 'item price formatting missing');
ok(!caja.includes("box.innerHTML='<div"), 'unsafe box innerHTML remains');
ok(!caja.includes("badge.innerHTML = '<div style=\"display:flex;align-items:center;gap:8px;font-size:12px;\">'"), 'unsafe badge innerHTML remains');
ok(!caja.includes("(v.precio||0) + '</span>"), 'unsafe price HTML concatenation remains');
ok(caja.includes('var abonoFailed = false'), 'abono failure guard missing');
ok(!caja.includes('delete VT._paymentKeys[cotId]'), 'payment idempotency key deletion must remain absent');
ok(caja.includes('if (abonoFailed)'), 'abono failure branch missing');
const migrationLower = migration.toLowerCase();
for(const marker of ['enable row level security','revoke all on table public.aos_cartera_reconciliacion','revoke all on table public.aos_cotizaciones','revoke all on table public.aos_pagos','for update;','forbidden_sede','stale_case','send-reminder']) {
  if(marker === 'send-reminder') ok(!migrationLower.includes(marker), 'reminder send path must remain absent');
  else ok(migrationLower.includes(marker), `missing migration marker: ${marker}`);
}
for(const marker of ["set search_path = ''",'request_id','request_hash','registrado_por_user_id','abierto_por_user_id','BALANCE_MUST_MATCH_QUOTE','aos_cartera_saldo_finite_chk','aos_cartera_monto_finite_chk',"'OVERPAYMENT'","'SERVICIO'","'remindersEnabled',false"]) ok(migration.includes(marker), `missing migration marker: ${marker}`);
ok(!migrationLower.includes('send-template'), 'template send path must remain absent');
ok(/drop function if exists public\.aos_cartera_reconcile\(\s*text,uuid,text,text,numeric,numeric,text,text,text\s*\)/i.test(cleanup), 'legacy reconcile signature cleanup missing');
ok(/drop function if exists public\.aos_abonar_cotizacion_v2\(\s*text,text,numeric,text,text,text,text,text,text,text,text,text\s*\)/i.test(cleanup), 'legacy abonar signature cleanup missing');
ok(cleanup.includes('aos_sales_intelligence_access'), 'SI access cleanup marker missing');
const rollbackLower = rollback.toLowerCase();
ok(!rollbackLower.includes('grant execute'), 'rollback must not grant execute');
ok(!/grant[\s\S]{0,120}\b(?:anon|authenticated)\b/i.test(rollback), 'rollback must not grant anon/authenticated');
ok(rollbackLower.includes('revoke all on function public.aos_abonar_cotizacion_v2'), 'rollback revoke missing');
ok(rollbackLower.includes('rename to aos_cartera_reconciliacion_rollback_20260814'), 'rollback rename missing');
console.log('CARTERA_PHASE2_UI_CONTRACT=PASS');
