'use strict'
const fs=require('fs')
function read(p){return fs.readFileSync(p,'utf8')}
function ok(v,m){if(!v){console.error('CIA DISTRIBUTION PLANNER V1 FAIL:',m);process.exit(1)}}
const ui=read('app/public/cia-audience-workspace-v3.js')
const sql=read('supabase/migrations/20260918022500_cia_distribution_planner_v1.sql')
const ux=read('supabase/migrations/20260919003000_cia_distribution_ux_v2.sql')

ok(ui.includes('aos_cia_distribution_preview_app_v2'),'UI must use dedicated fast distribution preview RPC')
ok(ui.includes("'DISTRIBUTION_RELEASE_STATE'"),'release state read missing')
ok(ui.includes("'DISTRIBUTION_PREVIEW'"),'distribution preview missing')
ok(ui.includes('Simular distribución'),'planner CTA missing')
ok(ui.includes('Ejecución real todavía bloqueada'),'rollout lock copy missing')
ok(ui.includes('Activar distribución')&&ui.includes('disabled'),'bulk activation must remain disabled')
ok(ui.includes('Cantidad a asignar')&&ui.includes('Todo asignable'),'flexible quantity controls missing')
ok(ui.includes("vals=[25,50,100,250,500]")&&ui.includes('data-quick'),'quick quantity actions missing')
ok(ui.includes('aw-test-overlay')&&ui.includes('🧪 Probar con 1 contacto'),'compact test modal missing')
ok(!ui.includes("rpc('START_DISTRIBUTION'"),'bulk distribution execution must not exist before canary PASS')
ok(ui.includes("rpc('START_CANARY_ASSIGNMENT'")&&ui.includes('source_limit:1'),'one-contact gate must remain intact')
ok(!ui.includes('setInterval('),'planner must not poll')

ok(sql.includes('aos_cia_distribution_release_state_v1'),'distribution release control missing')
ok(sql.includes("'CALL','HUMAN_CANARY_REQUIRED',false,1,1"),'CALL release must remain fail-closed')
ok(sql.includes('aos_cia_control_center_app_v4'),'V4 gateway missing')
ok(sql.includes("v_action not in ('DISTRIBUTION_RELEASE_STATE','DISTRIBUTION_PREVIEW')"),'V4 must delegate all other actions to V3')
ok(sql.includes("coalesce(u.paneles_acceso,'{}'::text[]) @> array['advisor-calls']::text[]"),'planner targets must require Call Center permission')
ok(sql.includes('aos_cia_audience_validate_v1')&&sql.includes('aos_cia_audience_count_v2'),'planner must use governed audience resolver')
ok(!sql.includes('START_DISTRIBUTION'),'bulk execution action forbidden before canary PASS')
ok(!sql.includes('SET_GLOBAL'),'planner must never mutate routing')
ok(!sql.includes('aos_cia_assignment_plan_create_admin_v1'),'planner must not create plans')
ok(ux.includes('aos_cia_control_center_app_v6'),'Distribution UX V6 missing')
ok(ux.includes('v_source_limit>100000'),'V6 must retain a high operational safety ceiling')
ok(ux.includes('ALL_AVAILABLE'),'all available mode missing')
ok(!ux.includes('START_DISTRIBUTION')&&!ux.includes('SET_GLOBAL')&&!ux.includes('aos_cia_assignment_plan_create_admin_v1'),'V6 preview must stay read-only')

console.log('CIA Distribution Planner V1 contract: PASS')
