
'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const copilot=require('../../app/wa4-copilot');
const knowledge=require('../../app/wa4-knowledge');
const quality=require('../../app/wa4-response-quality-guard');

const NABOTA='11111111-1111-4111-8111-111111111111';
const HUTOX='22222222-2222-4222-8222-222222222222';
function item(id,name){return {knowledge_id:'service:'+id,domain:'CATALOG',title:name,facts:{tipo:'SERVICIO',nombre:name,categoria:'TOXINA',descripcion_comercial:'Opción gobernada de toxina.'},authority_tier:10,freshness_state:'FRESH',conflict_state:'CLEAR',retrieval_state:'READY',evidence_ref:{relation:'public.aos_catalogo_servicios',pk:id,version:'v1'}};}
function ctx(id,name,price,ready=true){return {entity_id:id,entity_type:'SERVICIO',entity_name:name,category:'TOXINA',quote_price:price,precio_base:price,precio_oferta:price,moneda:'PEN',price_state:ready?'READY':'REVIEW_REQUIRED',freshness_state:'FRESH',ready_for_quote:ready,price_evidence_ref:'aos_catalogo_servicios:'+id+':PEN:v1'};}
function bundle(){return {version:'TEST',audience:'PUBLIC_CLIENT',authority:'GOVERNED_SOURCE_ONLY',generic_llm_authority:false,items:[item(NABOTA,'NABOTA 3 ZONAS 50U'),item(HUTOX,'HUTOX 3 ZONAS 50U')]};}
const pb={status:'FAIL_CLOSED',commercial_stage:'PROMOTION',recommended_next_action:'HUMAN_COMMERCIAL',policy_escalation:{required:true,reason:'NO_READY_PROMOTION_EVIDENCE'}};

test('R4 WhatsApp renderer converts double-markdown and headings to WhatsApp-safe text',()=>{const out=copilot.renderWhatsAppText('## Precio\\nEl valor es **S/ 399** y __vigente__.');assert.equal(out,'Precio\\nEl valor es *S/ 399* y _vigente_.');assert.equal(out.includes('**'),false);});
test('R4 greeting-only first contact uses the exact owner-approved presentation',()=>{assert.equal(copilot.composePatientReply('Hola, ¿en qué te ayudo?',[],'Hola'),copilot.APPROVED_FIRST_CONTACT_COPY);});
test('R4 substantive first contact prepends approved brand copy without adding a second generic question',()=>{const out=copilot.composePatientReply('Hola! Nabota 1 zona cuesta **S/ 399**. ¿Quieres avanzar con una cita?',[],'Quiero precio de toxina');assert.ok(out.startsWith(copilot.APPROVED_FIRST_CONTACT_PREFIX));assert.equal(out.charCodeAt(copilot.APPROVED_FIRST_CONTACT_PREFIX.length),10);assert.equal(out.split('?').length-1,1);assert.equal(out.includes('**'),false);assert.ok(out.includes('*S/ 399*'));});
test('R4 approved presentation is not duplicated after it already appeared outbound',()=>{const messages=[{direction:'OUTBOUND',message_body:copilot.APPROVED_FIRST_CONTACT_COPY}];const out=copilot.composePatientReply('Hola! Claro, seguimos con tu consulta.',messages,'Otra pregunta');assert.equal(out,'Claro, seguimos con tu consulta.');assert.equal(out.includes(copilot.APPROVED_FIRST_CONTACT_PREFIX),false);});
test('R4 no-promo continuity answers governed regular prices for an explicit 3-zone request instead of human handoff',()=>{const contexts=[ctx(NABOTA,'NABOTA 3 ZONAS 50U',999),ctx(HUTOX,'HUTOX 3 ZONAS 50U',799)];const priced=copilot.gatePublicCatalogMoney(bundle(),contexts,'PRICE_QUOTE',{intents:[]});const draft=copilot.deterministicNoPromotionDraft(pb,priced,contexts,'y si quiero 3 zonas de toxina? hay alguna promocion?');assert.ok(draft);assert.equal(draft.needs_human,false);assert.equal(draft.next_action,'REPLY');assert.deepEqual(draft.cited_knowledge_ids,['service:'+NABOTA,'service:'+HUTOX]);assert.match(draft.reply,/No tengo una promoción vigente confirmada/i);assert.ok(draft.reply.includes('S/ 999'));assert.ok(draft.reply.includes('S/ 799'));const grounded=knowledge.validateGroundedSuggestion(draft,priced);assert.equal(grounded.ok,true);const q=quality.validate({reply:draft.reply,runtime:{intents:['PROMOTION_REQUEST'],state:{}},contexts:{booking:{}},inbound:'y si quiero 3 zonas de toxina? hay alguna promocion?',approved_public_knowledge:priced});assert.equal(q.ok,true,q.violations.join(','));});
test('R4 booking deterministic branch is evaluated before generic playbook fail-closed',()=>{const fs=require('node:fs');const src=fs.readFileSync(require.resolve('../../app/wa4-copilot'),'utf8');assert.ok(src.indexOf("if(runtime.booking_readiness==='HIGH')")<src.indexOf("if(!pb||pb.status!=='READY'"));});
test('R4 no-promo continuity stays fail-closed without explicit zone count or READY regular price',()=>{const contexts=[ctx(NABOTA,'NABOTA 3 ZONAS 50U',999,false),ctx(HUTOX,'HUTOX 3 ZONAS 50U',799,false)];const priced=copilot.gatePublicCatalogMoney(bundle(),contexts,'PRICE_QUOTE',{intents:[]});assert.equal(copilot.deterministicNoPromotionDraft(pb,priced,contexts,'hay alguna promoción?'),null);assert.equal(copilot.deterministicNoPromotionDraft(pb,priced,contexts,'quiero 3 zonas, hay promoción?'),null);});
