-- WA-4A.1 Zi Vital knowledge seed — corporal_capilar
begin;
insert into public.aos_zi_knowledge_entities_v1(entity_key,entity_type,canonical_name,aliases,parent_entity_key,source_key,page_start,page_end,canonical_summary,public_client,advisor_internal,owner_admin,clinical_restricted,system_reference,status,version)
values
('DOMAIN_CORPORAL','DOMAIN','Dominio Corporal',array['Corporal']::text[],'ZI_SYSTEM','ZI_DOMAINS_20260827',6,9,'Forma, contorno y reconfiguración consciente con preparación sistémica y trabajo del tejido.','El Dominio Corporal aborda forma, contorno y reconfiguración consciente. El documento propone preparar el cuerpo antes de la reducción o remodelación.','Diferencia preparación, reducción/definición y firmeza/proyección. Esas necesidades corresponden a Body Reset, Sculpt Body y Sculpt Booty.','El dominio corporal se construye como proceso y no como promesa rápida de reducción de medidas.','La elección de intervención corporal y su secuencia depende de evaluación; no convertir la narrativa de preparación en una indicación médica automática.','{"summary":"Dominio con enfoques canónicos: APP_BODY_RESET, APP_SCULPT_BODY, APP_SCULPT_BOOTY.","approaches":["APP_BODY_RESET","APP_SCULPT_BODY","APP_SCULPT_BOOTY"]}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827'),
('DOMAIN_CAPILAR','DOMAIN','Dominio Capilar',array['Capilar']::text[],'ZI_SYSTEM','ZI_DOMAINS_20260827',9,12,'Densidad, vitalidad y permanencia consciente con procesos prolongados, soporte sistémico y mantenimiento.','El Dominio Capilar trabaja densidad, vitalidad y permanencia consciente. Zi Vital lo plantea como un proceso prolongado con expectativas realistas y seguimiento.','Distingue caída/pérdida de densidad activa de mantenimiento o prevención. Eso separa Activación & Regeneración de Mantenimiento & Prevención.','El dominio capilar se posiciona como proceso médico estructurado y de continuidad, no como un producto milagroso.','El documento incluye medicamentos y procedimientos médicos dentro de protocolos capilares; su indicación concreta queda restringida a evaluación y validación profesional.','{"summary":"Dominio con enfoques canónicos: APP_HAIR_REVIVAL, APP_HAIR_GUARD.","approaches":["APP_HAIR_REVIVAL","APP_HAIR_GUARD"]}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827'),
('APP_BODY_RESET','APPROACH','Body Reset','{}'::text[],'DOMAIN_CORPORAL','ZI_DOMAINS_20260827',6,7,'Enfoque corporal de limpieza, descarga y preparación metabólica previo a reducción o remodelación.','Body Reset es el enfoque corporal de preparación. Busca ordenar el proceso antes de pasar a reducción o remodelación.','Explícalo como fase de preparación y descarga, no como promesa directa de reducción. El documento lo relaciona con detox iónico, vitaminas, drenaje y activación muscular suave.','Funciona como punto de entrada del Dominio Corporal y como argumento de proceso frente a expectativas de resultados rápidos.','El documento lo presenta como preparación del cuerpo, pero la necesidad individual de detox, vitaminas u otras intervenciones no debe determinarse automáticamente.','{"summary":"Enfoque canónico dentro del sistema Zi Vital.","domain":"DOMAIN_CORPORAL","aliases":[],"source_treatments":["Detox iónico","Vitaminas endovenosas","Drenaje linfático manual","Ondas rusas (activación muscular suave)"],"source_products":["Redu Fast","Astaxantina","Perfect-B","Prunex","Suplementos antioxidantes y hepáticos","Productos antiinflamatorios sistémicos"],"source_terms_are_not_canonical_catalog_names":true}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827'),
('APP_SCULPT_BODY','APPROACH','Sculpt Body',array['Contour Sculpt']::text[],'DOMAIN_CORPORAL','ZI_DOMAINS_20260827',7,8,'Enfoque corporal de reducción, definición y contorno inteligente tras la preparación del cuerpo.','Sculpt Body es el enfoque corporal de reducción, definición y contorno, planteado después de la preparación del cuerpo.','El documento también usa el nombre Contour Sculpt. Relaciónalo con criolipólisis, enzimas, HIFU corporal, radiofrecuencia, vitaminas y drenaje dentro de un proceso.','Debe comunicarse como reducción consciente y progresiva, evitando promesas agresivas o milagrosas.','La selección de tecnología y técnicas médicas, así como su secuencia, requiere evaluación profesional.','{"summary":"Enfoque canónico dentro del sistema Zi Vital.","domain":"DOMAIN_CORPORAL","aliases":["Contour Sculpt"],"source_treatments":["Criolipólisis","Enzimas recombinantes","HIFU corporal","Radiofrecuencia corporal","Vitaminas","Detox continuo de apoyo","Drenaje linfático post tratamiento + Ondas rusas"],"source_products":["Beauty Maker","Neuro Vital","Redu Fast","Astaxantina","Perfect-B","Prunex","Lymdharial / Gotas, Pomada","Suplementos lipotrópicos","Antioxidantes sistémicos"],"source_terms_are_not_canonical_catalog_names":true}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827'),
('APP_SCULPT_BOOTY','APPROACH','Sculpt Booty',array['Volume & Firm']::text[],'DOMAIN_CORPORAL','ZI_DOMAINS_20260827',8,9,'Enfoque corporal de proyección, firmeza y calidad de tejido, especialmente glúteos, flacidez y estrías.','Sculpt Booty es el enfoque corporal orientado a proyección, firmeza y calidad del tejido, especialmente en glúteos, flacidez y estrías.','El texto también lo describe como Volume & Firm. Comunícalo desde proporción, textura y firmeza, no desde volumen exagerado.','Su narrativa estratégica combate referencias corporales irreales y refuerza proporción y elegancia.','El documento incluye ácido hialurónico corporal, bioestimuladores, enzimas para estrías, peptonas y radiofrecuencia; su indicación corresponde a evaluación profesional.','{"summary":"Enfoque canónico dentro del sistema Zi Vital.","domain":"DOMAIN_CORPORAL","aliases":["Volume & Firm"],"source_treatments":["Ácido hialurónico corporal de alta calidad (glúteos)","Bioestimuladores corporales","Enzimas para estrías","Peptonas","Radiofrecuencia corporal"],"source_products":["Beauty Maker","Neuro Vital","Astaxantina","Suplementos regenerativos","Antioxidantes de soporte"],"source_terms_are_not_canonical_catalog_names":true}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827'),
('APP_HAIR_REVIVAL','APPROACH','Activación & Regeneración',array['Hair Revival']::text[],'DOMAIN_CAPILAR','ZI_DOMAINS_20260827',10,11,'Enfoque capilar de intervención activa para caída, adelgazamiento o pérdida de densidad.','Activación & Regeneración, también llamado Hair Revival en el documento, es el enfoque capilar para caída activa, adelgazamiento o pérdida de densidad.','Explícalo como proceso estructurado y de constancia. El documento lo relaciona con radiofrecuencia capilar, mesoterapia, PRP, exosomas, PDRN y soporte domiciliario.','Su diferenciación está en convertir la frustración por soluciones aisladas en un proceso médico estructurado y medible en el tiempo.','El documento menciona minoxidil, dutasteride, PRP, exosomas y PDRN dentro de protocolos. Nunca convertir esas menciones en prescripción automática; requieren evaluación y criterio médico.','{"summary":"Enfoque canónico dentro del sistema Zi Vital.","domain":"DOMAIN_CAPILAR","aliases":["Hair Revival"],"source_treatments":["Radiofrecuencia capilar","Mesoterapia capilar con Minoxidil","Mesoterapia capilar con Dutasteride","Cóctel Hair (polivitamínico)","PRP (plasma rico en plaquetas con suplementos)","Exosomas capilares","PDRN / polinucleótidos","Protocolos combinados según evaluación médica"],"source_products":["Minoxidil tópico (loción / spray)","Shampoo anticaída especializado","Cápsulas orales de soporte capilar","Beauty Maker","Neuro Vital","Suplementos vitamínicos específicos"],"source_terms_are_not_canonical_catalog_names":true}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827'),
('APP_HAIR_GUARD','APPROACH','Mantenimiento & Prevención',array['Hair Guard']::text[],'DOMAIN_CAPILAR','ZI_DOMAINS_20260827',11,12,'Enfoque capilar de prevención, refuerzo y protección de resultados a largo plazo.','Mantenimiento & Prevención, también llamado Hair Guard, es el enfoque que busca proteger los resultados capilares y reducir el riesgo de abandono del cuidado.','Úsalo para explicar continuidad: sesiones de refuerzo, controles, ajustes y productos domiciliarios según evolución.','Convierte el mantenimiento en parte del sistema y da protagonismo a la continuidad y al uso domiciliario.','Los refuerzos, ajustes y productos deben adaptarse según evolución, cambios hormonales o estrés bajo supervisión profesional.','{"summary":"Enfoque canónico dentro del sistema Zi Vital.","domain":"DOMAIN_CAPILAR","aliases":["Hair Guard"],"source_treatments":["Sesiones periódicas de radiofrecuencia capilar","Refuerzos con mesoterapia según evolución","Controles médicos programados","Ajustes de protocolo según cambios hormonales o estrés"],"source_products":["Shampoo y acondicionador preventivo","Spray fortalecedor","Cápsulas de mantenimiento","Beauty Maker","Vitaminas de soporte continuo"],"source_terms_are_not_canonical_catalog_names":true}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827')
on conflict (entity_key) do update set
 entity_type=excluded.entity_type,canonical_name=excluded.canonical_name,aliases=excluded.aliases,
 parent_entity_key=excluded.parent_entity_key,source_key=excluded.source_key,page_start=excluded.page_start,
 page_end=excluded.page_end,canonical_summary=excluded.canonical_summary,public_client=excluded.public_client,
 advisor_internal=excluded.advisor_internal,owner_admin=excluded.owner_admin,
 clinical_restricted=excluded.clinical_restricted,system_reference=excluded.system_reference,
 status='ACTIVE',version=excluded.version,updated_at=now();
commit;
