create or replace function public.aos_cia_phase9_admin_gateway_v1(p_token text,p_action text,p_payload jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare auth jsonb;uid uuid;usr text;act text:=upper(coalesce(p_action,''));payload jsonb:=coalesce(p_payload,'{}'::jsonb);res jsonb;t0 timestamptz:=clock_timestamp();dur integer;v_advisor uuid;v_state text;
begin
 if jsonb_typeof(payload)<>'object' or octet_length(payload::text)>65536 then return jsonb_build_object('ok',false,'error','INVALID_PAYLOAD');end if;
 auth:=public.aos_cia_verify_admin_session_v1(p_token);if not coalesce((auth->>'ok')::boolean,false)then return jsonb_build_object('ok',false,'error','UNAUTHORIZED');end if;uid:=(auth->>'user_id')::uuid;usr:=coalesce(auth->>'usuario','');
 if act='BOOTSTRAP' then res:=jsonb_build_object('ok',true,'version',1,'advisors',public.aos_cia_assignment_advisors_v1(),'plans',public.aos_cia_assignment_plan_list_v1(false,50,0)->'items','workload',public.aos_cia_assignment_advisor_workload_v1()->'items','limits',jsonb_build_object('max_targets',50,'max_list',100,'max_events',200,'payload_bytes',65536));
 elsif act='LIST_PLANS' then res:=public.aos_cia_assignment_plan_list_v1(coalesce((payload->>'include_terminal')::boolean,true),least(greatest(coalesce((payload->>'limit')::integer,50),1),100),greatest(coalesce((payload->>'offset')::integer,0),0));
 elsif act='GET_PLAN' then res:=public.aos_cia_assignment_plan_summary_v1((payload->>'plan_id')::uuid);
 elsif act='CREATE_PLAN' then res:=public.aos_cia_assignment_plan_create_admin_v1(p_token,(payload->>'activation_id')::uuid,payload->>'strategy',payload->'targets',coalesce(payload->>'ownership_scope','GLOBAL'),nullif(payload->>'source_limit','')::integer,coalesce((payload->>'lease_minutes')::integer,480),coalesce((payload->>'must_start_minutes')::integer,120),coalesce(payload->>'topup_policy','NONE'),nullif(payload->>'topup_target_per_advisor','')::integer,coalesce((payload->>'allow_reassign_released')::boolean,true),coalesce((payload->>'allow_reassign_expired')::boolean,true),payload->>'idempotency_key',coalesce(payload->'metadata','{}'::jsonb));
 elsif act='TRANSITION_PLAN' then res:=public.aos_cia_assignment_plan_transition_admin_v1(p_token,(payload->>'plan_id')::uuid,payload->>'action');
 elsif act='TOPUP' then res:=public.aos_cia_assignment_topup_admin_v1(p_token,(payload->>'plan_id')::uuid,payload->>'idempotency_key');
 elsif act='RECONCILE' then res:=public.aos_cia_assignment_reconcile_admin_v1(p_token,(payload->>'plan_id')::uuid);
 elsif act='LIST_ASSIGNMENTS' then v_advisor:=case when nullif(payload->>'advisor_user_id','') is null then null else (payload->>'advisor_user_id')::uuid end;v_state:=nullif(upper(coalesce(payload->>'state','')),'');res:=public.aos_cia_assignment_list_v1((payload->>'plan_id')::uuid,v_advisor,v_state,least(greatest(coalesce((payload->>'limit')::integer,50),1),100),greatest(coalesce((payload->>'offset')::integer,0),0));
 elsif act='ASSIGNMENT_ACTION' then res:=public.aos_cia_assignment_action_admin_v1(p_token,(payload->>'assignment_id')::uuid,payload->>'action',nullif(payload->>'reason',''));
 elsif act='EVENTS' then res:=public.aos_cia_assignment_events_v1((payload->>'plan_id')::uuid,least(greatest(coalesce((payload->>'limit')::integer,100),1),200));
 elsif act='ADVISOR_WORKLOAD' then res:=public.aos_cia_assignment_advisor_workload_v1();
 else res:=jsonb_build_object('ok',false,'error','UNSUPPORTED_ACTION');end if;
 dur:=greatest(0,round(extract(epoch from(clock_timestamp()-t0))*1000)::integer);insert into public.aos_cia_gateway_audit(user_id,usuario,action,ok,duration_ms,meta)values(uid,usr,'CIA_P9:'||act,coalesce((res->>'ok')::boolean,false),dur,jsonb_build_object('phase',9));return res;
exception when invalid_text_representation or numeric_value_out_of_range then return jsonb_build_object('ok',false,'error','INVALID_PAYLOAD');when others then begin dur:=greatest(0,round(extract(epoch from(clock_timestamp()-t0))*1000)::integer);if uid is not null then insert into public.aos_cia_gateway_audit(user_id,usuario,action,ok,duration_ms,meta)values(uid,coalesce(usr,''),'CIA_P9:'||act,false,dur,jsonb_build_object('phase',9,'error',left(sqlerrm,500)));end if;exception when others then null;end;return jsonb_build_object('ok',false,'error','PHASE9_GATEWAY_ERROR','detail',left(sqlerrm,500));end$$;
revoke all on function public.aos_cia_phase9_admin_gateway_v1(text,text,jsonb) from public;
grant execute on function public.aos_cia_phase9_admin_gateway_v1(text,text,jsonb) to anon,authenticated,service_role;
