-- WA-4A.1 Zi Vital knowledge seed — core
begin;
insert into public.aos_zi_knowledge_entities_v1(entity_key,entity_type,canonical_name,aliases,parent_entity_key,source_key,page_start,page_end,canonical_summary,public_client,advisor_internal,owner_admin,clinical_restricted,system_reference,status,version)
values
('ZI_SYSTEM','SYSTEM','Sistema Zi Vital','{}'::text[],null,'ZI_DOMAINS_20260827',1,14,'Arquitectura de cuidado estético consciente organizada por dominios y enfoques, con visión integral y de largo plazo.','Zi Vital organiza el cuidado en dominios y enfoques para entender primero qué territorio se quiere trabajar y luego definir cómo abordarlo. No se plantea como una suma de tratamientos aislados.','Explica primero el dominio y después el enfoque. Usa los tratamientos y productos como herramientas dentro del proceso, no como el centro de la conversación. Evita convertir la explicación en una clase larga.','La arquitectura busca diferenciar a Zi Vital por orden, criterio y acompañamiento, no por precio ni por moda. Debe orientar catálogo, comunicación, capacitación y crecimiento sin perder identidad.','La elección del enfoque y de las intervenciones concretas depende de la lectura clínica del paciente. La arquitectura no sustituye diagnóstico ni validación médica.','{"summary":"Jerarquía canónica: Sistema Zi Vital → Dominio → Enfoque → tratamientos/productos relacionados. Capas transversales: Detox y Vitaminas. Secuencia transversal: preparar, activar, regenerar y mantener.","domains":["DOMAIN_FACIAL","DOMAIN_CORPORAL","DOMAIN_CAPILAR"],"cross_layers":["ZI_LAYER_DETOX","ZI_LAYER_VITAMINS"],"sequence":"ZI_SEQUENCE"}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827'),
('ZI_SEQUENCE','PRINCIPLE','Preparar · Activar · Regenerar · Mantener','{}'::text[],'ZI_SYSTEM','ZI_DOMAINS_20260827',1,14,'Secuencia transversal que sostiene la arquitectura Zi Vital.','El plan puede organizarse en etapas: preparar, activar, regenerar y mantener. No todas las personas recorren exactamente las mismas etapas ni al mismo ritmo.','Usa la secuencia para explicar por qué un plan puede tener preparación, intervención y mantenimiento. No presentes una etapa como obligatoria para todos si el documento no lo define así para ese caso.','Esta secuencia debe servir como marco común para ordenar conceptos, paquetes, seguimiento y contenidos de Zi Vital.','La secuencia es una lógica del sistema; la indicación clínica concreta y el orden real del paciente requieren evaluación profesional.','{"summary":"Canonical process logic: PREPARAR → ACTIVAR → REGENERAR → MANTENER.","steps":["PREPARAR","ACTIVAR","REGENERAR","MANTENER"]}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827'),
('ZI_LAYER_DETOX','CROSS_LAYER','Detox','{}'::text[],'ZI_SYSTEM','ZI_DOMAINS_20260827',1,14,'Capa transversal descrita en el documento como preparación y soporte de los dominios.','El documento lo presenta como una capa transversal de preparación y soporte, especialmente destacada en procesos corporales y en pacientes descritos como inflamados.','Detox no debe explicarse como un tratamiento aislado por defecto; ubícalo como soporte dentro del plan cuando el enfoque documentado lo contemple.','Detox funciona en el documento como capa transversal y debe modelarse como relación reutilizable, no duplicarse dentro de cada dominio.','Las afirmaciones clínicas concretas sobre detox y su necesidad individual no deben inferirse automáticamente a partir del marco conceptual.','{"summary":"Detox = CROSS_LAYER; puede relacionarse con múltiples dominios/enfoques sin convertirse en un dominio."}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827'),
('ZI_LAYER_VITAMINS','CROSS_LAYER','Vitaminas','{}'::text[],'ZI_SYSTEM','ZI_DOMAINS_20260827',1,14,'Capa transversal de soporte descrita como parte estructural del sistema.','El documento las presenta como una capa transversal de soporte que acompaña distintos dominios y enfoques.','Vitaminas no debe explicarse como un tratamiento aislado por defecto; ubícalo como soporte dentro del plan cuando el enfoque documentado lo contemple.','Vitaminas funciona en el documento como capa transversal y debe modelarse como relación reutilizable, no duplicarse dentro de cada dominio.','Las afirmaciones clínicas concretas sobre vitaminas y su necesidad individual no deben inferirse automáticamente a partir del marco conceptual.','{"summary":"Vitaminas = CROSS_LAYER; puede relacionarse con múltiples dominios/enfoques sin convertirse en un dominio."}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827')
on conflict (entity_key) do update set
 entity_type=excluded.entity_type,canonical_name=excluded.canonical_name,aliases=excluded.aliases,
 parent_entity_key=excluded.parent_entity_key,source_key=excluded.source_key,page_start=excluded.page_start,
 page_end=excluded.page_end,canonical_summary=excluded.canonical_summary,public_client=excluded.public_client,
 advisor_internal=excluded.advisor_internal,owner_admin=excluded.owner_admin,
 clinical_restricted=excluded.clinical_restricted,system_reference=excluded.system_reference,
 status='ACTIVE',version=excluded.version,updated_at=now();
commit;
