-- ASCENDA OS — Sales import exact-batch idempotency
-- Prevents an identical pasted sales payload from being processed twice.
-- Does not collapse merely similar rows, preserving legitimate repeated purchases.

create table public.aos_import_ventas_batches (
  id bigint generated by default as identity primary key,
  batch_hash text not null unique,
  total_rows integer not null,
  resultado jsonb not null,
  created_at timestamptz not null default now()
);

revoke all on table public.aos_import_ventas_batches from anon, authenticated;

create or replace function public.aos_importar_ventas(p_ventas jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_insertados int := 0;
  v_errores int := 0;
  v_duplicados int := 0;
  v_row jsonb;
  v_num text;
  v_venta_id text;
  v_monto numeric;
  v_monto_raw text;
  v_existe boolean;
  v_fecha date;
  v_trat text;
  v_pago text;
  v_asesor text;
  v_dup_existe boolean;
  v_max_id_antes bigint;
  v_batch_hash text;
  v_total int;
  v_prev jsonb;
  v_result jsonb;
begin
  if p_ventas is null or jsonb_typeof(p_ventas) <> 'array' then
    raise exception 'p_ventas debe ser un arreglo JSON';
  end if;

  v_total := jsonb_array_length(p_ventas);
  if v_total = 0 then
    return jsonb_build_object('insertados',0,'duplicados',0,'errores',0,'total',0,'lote_duplicado',false);
  end if;

  v_batch_hash := md5(p_ventas::text);
  perform pg_advisory_xact_lock(hashtextextended(v_batch_hash,0));

  select b.resultado into v_prev
  from public.aos_import_ventas_batches b
  where b.batch_hash=v_batch_hash;

  if v_prev is not null then
    return jsonb_build_object(
      'insertados',0,
      'duplicados',v_total,
      'errores',0,
      'total',v_total,
      'lote_duplicado',true,
      'mensaje','Este lote exacto ya fue procesado anteriormente.'
    );
  end if;

  select coalesce(max(id),0) into v_max_id_antes from public.aos_ventas;

  for v_row in select * from jsonb_array_elements(p_ventas)
  loop
    begin
      v_num := regexp_replace(coalesce(v_row->>'celular',''),'[^0-9]','','g');
      if length(v_num)>9 then v_num:=right(v_num,9); end if;

      v_monto_raw:=coalesce(v_row->>'monto','0');
      v_monto_raw:=regexp_replace(v_monto_raw,'S/\.?\s*','','gi');
      v_monto_raw:=regexp_replace(v_monto_raw,'\$\s*','','g');
      v_monto_raw:=replace(v_monto_raw,',','');
      v_monto_raw:=regexp_replace(v_monto_raw,'[^0-9.]','','g');
      if v_monto_raw like '.%' then v_monto_raw:=ltrim(v_monto_raw,'.'); end if;
      v_monto:=coalesce(nullif(v_monto_raw,'')::numeric,0);

      v_fecha:=coalesce(nullif(v_row->>'fecha','')::date,current_date);
      v_trat:=upper(trim(coalesce(v_row->>'tratamiento','')));
      v_pago:=upper(trim(coalesce(v_row->>'pago','')));
      v_asesor:=upper(trim(coalesce(v_row->>'asesor','')));

      select exists(
        select 1 from public.aos_ventas
        where id<=v_max_id_antes
          and fecha=v_fecha
          and numero_limpio=v_num
          and tratamiento=v_trat
          and monto::numeric=v_monto
          and upper(trim(coalesce(pago,'')))=v_pago
          and upper(trim(coalesce(asesor,'')))=v_asesor
          and created_at>now()-interval '5 minutes'
        limit 1
      ) into v_dup_existe;

      if v_dup_existe then
        v_duplicados:=v_duplicados+1;
        continue;
      end if;

      v_venta_id:='V-'||to_char(now(),'YYYYMMDD')||'-'||lpad(floor(random()*99999)::text,5,'0');

      insert into public.aos_ventas(
        venta_id,fecha,nombres,apellidos,dni,celular,numero_limpio,
        tratamiento,descripcion,pago,monto,estado_pago,
        asesor,atendio,sede,tipo,moneda
      ) values(
        v_venta_id,v_fecha,
        upper(trim(coalesce(v_row->>'nombres',''))),
        upper(trim(coalesce(v_row->>'apellidos',''))),
        trim(coalesce(v_row->>'dni','')),
        trim(coalesce(v_row->>'celular','')),
        v_num,v_trat,
        trim(coalesce(v_row->>'descripcion','')),
        v_pago,v_monto,
        upper(trim(coalesce(v_row->>'estado_pago','PAGO COMPLETO'))),
        v_asesor,
        upper(trim(coalesce(v_row->>'atendio',''))),
        upper(trim(coalesce(v_row->>'sede','SAN ISIDRO'))),
        case when v_trat like '%COMPRA%' or v_trat like '%PRODUCTO%' or v_trat='OTROS' then 'PRODUCTO' else 'SERVICIO' end,
        'PEN'
      );
      v_insertados:=v_insertados+1;

      if v_num<>'' and length(v_num)>=7 then
        select exists(select 1 from public.aos_pacientes where numero_limpio=v_num limit 1) into v_existe;
        if v_existe then
          update public.aos_pacientes set
            n_ventas=coalesce(n_ventas,0)+1,
            "TOTAL_FACTURADO"=coalesce("TOTAL_FACTURADO",0)+v_monto,
            "ULTIMA_VISITA"=current_date,
            ult_visita=current_date,
            "ESTADO_PACIENTE"='ACTIVO',
            "SCORE_ESTADO"='PACIENTE',
            updated_at=now()
          where numero_limpio=v_num;
        else
          insert into public.aos_pacientes(
            "ID_PACIENTE","Nombres","Apellidos","Teléfono","N° documento",
            numero_limpio,"ESTADO_PACIENTE","SCORE_ESTADO",fuente_datos,
            "SEDE_PRINCIPAL",n_ventas,primera_venta,"TOTAL_FACTURADO"
          ) values(
            gen_random_uuid()::text,
            upper(trim(coalesce(v_row->>'nombres',''))),
            upper(trim(coalesce(v_row->>'apellidos',''))),
            v_num,
            trim(coalesce(v_row->>'dni','')),
            v_num,
            'ACTIVO','PACIENTE','importacion_ventas',
            upper(trim(coalesce(v_row->>'sede','SAN ISIDRO'))),
            1,current_date,v_monto
          );
        end if;
      end if;
    exception when others then
      v_errores:=v_errores+1;
    end;
  end loop;

  v_result:=jsonb_build_object(
    'insertados',v_insertados,
    'duplicados',v_duplicados,
    'errores',v_errores,
    'total',v_total,
    'lote_duplicado',false
  );

  insert into public.aos_import_ventas_batches(batch_hash,total_rows,resultado)
  values(v_batch_hash,v_total,v_result);

  return v_result;
end;
$function$;
