-- CIA Phase 5 — set resolver: each leaf resolves contact keys in its own domain; AND=intersection, OR=union.
begin;
create or replace view public.aos_cia_lead_call_state_v2 with(security_invoker=true)as
with l as(select distinct on(public.aos_cia_normalize_contact_key_v1(numero_limpio))public.aos_cia_normalize_contact_key_v1(numero_limpio)contact_key,coalesce(hora_ingreso,created_at,fecha::timestamp at time zone 'America/Lima')last_lead_at from public.aos_leads where public.aos_cia_normalize_contact_key_v1(numero_limpio)is not null order by public.aos_cia_normalize_contact_key_v1(numero_limpio),coalesce(hora_ingreso,created_at,fecha::timestamp at time zone 'America/Lima')desc,id desc),c as(select public.aos_cia_normalize_contact_key_v1(numero_limpio)contact_key,max(created_at)last_call_at from public.aos_llamadas where public.aos_cia_normalize_contact_key_v1(numero_limpio)is not null group by 1)
select l.contact_key,l.last_lead_at,c.last_call_at,(c.last_call_at is not null and c.last_call_at>=l.last_lead_at)called_since_latest_entry,(c.last_call_at is null or c.last_call_at<l.last_lead_at)unworked_since_latest_entry from l left join c using(contact_key);
revoke all on public.aos_cia_lead_call_state_v2 from public,anon,authenticated;grant select on public.aos_cia_lead_call_state_v2 to service_role;

create table if not exists public.aos_cia_domain_defaults_v2(source_key text primary key,default_row jsonb not null,updated_at timestamptz not null default now());
alter table public.aos_cia_domain_defaults_v2 enable row level security;revoke all on public.aos_cia_domain_defaults_v2 from public,anon,authenticated;grant select on public.aos_cia_domain_defaults_v2 to service_role;
insert into public.aos_cia_domain_defaults_v2(source_key,default_row)values
('LEAD','{"lead_ads":[],"lead_count":0,"lead_interests":[],"latest_interest":null,"days_since_last_lead":null,"latest_interest_type":null}'::jsonb),
('CALL','{"call_count":0,"called_today":false,"call_ever_statuses":[],"latest_call_status":null,"days_since_last_call":null,"latest_call_substatus":null,"effective_contact_count":0}'::jsonb),
('APPOINTMENT','{"ever_no_show":false,"no_show_count":0,"attended_count":0,"appointment_count":0,"last_appointment_at":null,"next_appointment_at":null,"appointment_statuses":[],"has_future_appointment":false,"last_appointment_status":null,"days_until_next_appointment":null}'::jsonb),
('SALE','{"sale_count":0,"product_count":0,"service_count":0,"payment_states":[],"payment_methods":[],"latest_item_type":null,"revenue_lifetime":0,"days_since_last_sale":null}'::jsonb),
('FOLLOWUP','{"next_followup_at":null,"followup_treatments":[],"overdue_followup_count":0,"pending_followup_count":0,"days_until_next_followup":null}'::jsonb)
on conflict(source_key)do update set default_row=excluded.default_row,updated_at=now();

create or replace function public.aos_cia_keys_intersect_v2(a text[],b text[])returns text[] language sql immutable parallel safe as $$select coalesce(array_agg(x order by x),array[]::text[])from(select unnest(a)x intersect select unnest(b)x)q;$$;
create or replace function public.aos_cia_keys_union_v2(a text[],b text[])returns text[] language sql immutable parallel safe as $$select coalesce(array_agg(x order by x),array[]::text[])from(select unnest(a)x union select unnest(b)x)q;$$;

create or replace function public.aos_cia_domain_absent_keys_v2(p_source_key text)returns text[] language plpgsql stable security invoker as $$declare keys text[]:=array[]::text[];begin
 if p_source_key='LEAD' then select coalesce(array_agg(contact_key order by contact_key),array[]::text[])into keys from public.aos_cia_contact_identity_v1 where not has_lead;
 elsif p_source_key='CALL' then select coalesce(array_agg(contact_key order by contact_key),array[]::text[])into keys from public.aos_cia_contact_identity_v1 where not has_call;
 elsif p_source_key='APPOINTMENT' then select coalesce(array_agg(contact_key order by contact_key),array[]::text[])into keys from public.aos_cia_contact_identity_v1 where not has_appointment;
 elsif p_source_key='SALE' then select coalesce(array_agg(contact_key order by contact_key),array[]::text[])into keys from public.aos_cia_contact_identity_v1 where not has_sale;
 elsif p_source_key='FOLLOWUP' then select coalesce(array_agg(i.contact_key order by i.contact_key),array[]::text[])into keys from public.aos_cia_contact_identity_v1 i left join public.aos_cia_followup_facts_v1 f using(contact_key)where f.contact_key is null;end if;return keys;end;$$;

create or replace function public.aos_cia_audience_leaf_keys_v2(p_rule jsonb)returns text[] language plpgsql stable security invoker as $$declare f text:=p_rule->>'field';op text:=p_rule->>'operator';sk text;sp text;keys text[]:=array[]::text[];begin
 select source_key,special_key into sk,sp from public.aos_cia_filter_execution_map_v2 where field_key=f;
 if sp='EXISTS_AS_LEAD' then select coalesce(array_agg(contact_key order by contact_key),array[]::text[])into keys from public.aos_cia_contact_identity_v1 where case op when 'is_true' then has_lead when 'is_false' then not has_lead else false end;
 elsif sp in('LEAD_CALLED_SINCE','LEAD_UNWORKED')then if op='is_unknown' then select coalesce(array_agg(contact_key order by contact_key),array[]::text[])into keys from public.aos_cia_contact_identity_v1 where not has_lead;elsif sp='LEAD_CALLED_SINCE'then select coalesce(array_agg(contact_key order by contact_key),array[]::text[])into keys from public.aos_cia_lead_call_state_v2 where case op when 'is_true'then called_since_latest_entry when 'is_false'then not called_since_latest_entry else false end;else select coalesce(array_agg(contact_key order by contact_key),array[]::text[])into keys from public.aos_cia_lead_call_state_v2 where case op when 'is_true'then unworked_since_latest_entry when 'is_false'then not unworked_since_latest_entry else false end;end if;
 elsif sp='CALLS_NEVER'then select coalesce(array_agg(contact_key order by contact_key),array[]::text[])into keys from public.aos_cia_contact_identity_v1 where case op when 'is_true'then not has_call when 'is_false'then has_call else false end;
 elsif sp='APPOINTMENTS_NEVER'then select coalesce(array_agg(contact_key order by contact_key),array[]::text[])into keys from public.aos_cia_contact_identity_v1 where case op when 'is_true'then not has_appointment when 'is_false'then has_appointment else false end;
 elsif sp='SALES_NEVER'then select coalesce(array_agg(contact_key order by contact_key),array[]::text[])into keys from public.aos_cia_contact_identity_v1 where case op when 'is_true'then not has_sale when 'is_false'then has_sale else false end;
 elsif sp='CRM_BRANCH'then select coalesce(array_agg(contact_key order by contact_key),array[]::text[])into keys from public.aos_cia_branch_fast_v2 x where public.aos_cia_audience_rule_match_v1(jsonb_build_object('crm_branch',x.branch),p_rule);
 elsif sk='IDENTITY'then select coalesce(array_agg(contact_key order by contact_key),array[]::text[])into keys from public.aos_cia_contact_identity_v1 x where public.aos_cia_audience_rule_match_v1(to_jsonb(x),p_rule);
 elsif sk='PROFILE'then select coalesce(array_agg(contact_key order by contact_key),array[]::text[])into keys from public.aos_cia_profile_adapter_v2 x where public.aos_cia_audience_rule_match_v1(to_jsonb(x),p_rule);
 elsif sk='LEAD'then select coalesce(array_agg(contact_key order by contact_key),array[]::text[])into keys from public.aos_cia_lead_adapter_v2 x where public.aos_cia_audience_rule_match_v1(to_jsonb(x),p_rule);
 elsif sk='CALL'then select coalesce(array_agg(contact_key order by contact_key),array[]::text[])into keys from public.aos_cia_call_adapter_v2 x where public.aos_cia_audience_rule_match_v1(to_jsonb(x),p_rule);
 elsif sk='APPOINTMENT'then select coalesce(array_agg(contact_key order by contact_key),array[]::text[])into keys from public.aos_cia_appointment_adapter_v2 x where public.aos_cia_audience_rule_match_v1(to_jsonb(x),p_rule);
 elsif sk='SALE'then select coalesce(array_agg(contact_key order by contact_key),array[]::text[])into keys from public.aos_cia_sale_adapter_v2 x where public.aos_cia_audience_rule_match_v1(to_jsonb(x),p_rule);
 elsif sk='FOLLOWUP'then select coalesce(array_agg(contact_key order by contact_key),array[]::text[])into keys from public.aos_cia_followup_adapter_v2 x where public.aos_cia_audience_rule_match_v1(to_jsonb(x),p_rule);
 elsif sk='EMAIL'then select coalesce(array_agg(contact_key order by contact_key),array[]::text[])into keys from public.aos_cia_email_adapter_v2 x where public.aos_cia_audience_rule_match_v1(to_jsonb(x),p_rule);
 elsif sk='SEGMENT'then select coalesce(array_agg(contact_key order by contact_key),array[]::text[])into keys from public.aos_cia_segment_adapter_v2 x where public.aos_cia_audience_rule_match_v1(to_jsonb(x),p_rule);
 elsif sk='PURCHASE'then select coalesce(array_agg(contact_key order by contact_key),array[]::text[])into keys from public.aos_cia_purchase_adapter_v2 x where public.aos_cia_audience_rule_match_v1(to_jsonb(x),p_rule);end if;return keys;end;$$;
create or replace function public.aos_cia_audience_leaf_keys_v3(p_rule jsonb)returns text[] language plpgsql stable security invoker as $$declare keys text[];absent text[];sk text;default_row jsonb;begin keys:=public.aos_cia_audience_leaf_keys_v2(p_rule);select source_key into sk from public.aos_cia_filter_execution_map_v2 where field_key=p_rule->>'field';if sk in('LEAD','CALL','APPOINTMENT','SALE','FOLLOWUP')then select d.default_row into default_row from public.aos_cia_domain_defaults_v2 d where d.source_key=sk;if default_row is not null and public.aos_cia_audience_rule_match_v1(default_row,p_rule)then absent:=public.aos_cia_domain_absent_keys_v2(sk);keys:=public.aos_cia_keys_union_v2(keys,absent);end if;end if;return coalesce(keys,array[]::text[]);end;$$;
create or replace function public.aos_cia_audience_resolve_node_v2(p_node jsonb,p_depth integer default 1)returns text[] language plpgsql stable security invoker as $$declare r jsonb;child text[];acc text[];first_child boolean:=true;op text;begin if p_node?'field'then return public.aos_cia_audience_leaf_keys_v3(p_node);end if;if p_depth>2 then return array[]::text[];end if;op:=upper(coalesce(p_node->>'op',''));for r in select value from jsonb_array_elements(p_node->'rules')loop child:=public.aos_cia_audience_resolve_node_v2(r,case when r?'field'then p_depth else p_depth+1 end);if first_child then acc:=child;first_child:=false;elsif op='AND'then acc:=public.aos_cia_keys_intersect_v2(acc,child);elsif op='OR'then acc:=public.aos_cia_keys_union_v2(acc,child);else return array[]::text[];end if;end loop;return coalesce(acc,array[]::text[]);end;$$;
create or replace function public.aos_cia_audience_count_v2(p_filter jsonb)returns jsonb language plpgsql stable security invoker as $$declare v jsonb;keys text[];refreshed timestamptz;begin v:=public.aos_cia_audience_validate_v1(p_filter);if not coalesce((v->>'valid')::boolean,false)then return jsonb_build_object('ok',false,'validation',v);end if;keys:=public.aos_cia_audience_resolve_node_v2(p_filter->'root',1);select max(cache_refreshed_at)into refreshed from public.aos_cia_segment_runtime_cache_v2;return jsonb_build_object('ok',true,'count',cardinality(keys),'resolver_version',2,'registry_version',1,'segment_cache_refreshed_at',refreshed,'observed_at',statement_timestamp());end;$$;
revoke all on function public.aos_cia_keys_intersect_v2(text[],text[]),public.aos_cia_keys_union_v2(text[],text[]),public.aos_cia_domain_absent_keys_v2(text),public.aos_cia_audience_leaf_keys_v2(jsonb),public.aos_cia_audience_leaf_keys_v3(jsonb),public.aos_cia_audience_resolve_node_v2(jsonb,integer),public.aos_cia_audience_count_v2(jsonb) from public,anon,authenticated;
grant execute on function public.aos_cia_keys_intersect_v2(text[],text[]),public.aos_cia_keys_union_v2(text[],text[]),public.aos_cia_domain_absent_keys_v2(text),public.aos_cia_audience_leaf_keys_v2(jsonb),public.aos_cia_audience_leaf_keys_v3(jsonb),public.aos_cia_audience_resolve_node_v2(jsonb,integer),public.aos_cia_audience_count_v2(jsonb) to service_role;
commit;
