-- ASCENDA CIA V3 — Phase 11 Call Center Integration V3
-- Additive/private rollout control. Default is OFF/V2_ONLY.

create table if not exists public.aos_cia_call_routing_control (
  id smallint primary key default 1 check (id = 1),
  global_enabled boolean not null default false,
  fallback_to_v2 boolean not null default true check (fallback_to_v2 = true),
  updated_by_user_id uuid null references public.aos_usuarios(id),
  metadata jsonb not null default '{}'::jsonb check (pg_column_size(metadata) <= 8192),
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp()
);

insert into public.aos_cia_call_routing_control(id,global_enabled,fallback_to_v2,metadata)
values(1,false,true,'{}'::jsonb)
on conflict (id) do nothing;

create table if not exists public.aos_cia_call_routing_advisors (
  advisor_user_id uuid primary key references public.aos_usuarios(id),
  mode text not null default 'V2_ONLY' check (mode in ('V2_ONLY','V3_CANARY','V3_PREFERRED')),
  fallback_to_v2 boolean not null default true check (fallback_to_v2 = true),
  enabled_at timestamptz null,
  updated_by_user_id uuid not null references public.aos_usuarios(id),
  metadata jsonb not null default '{}'::jsonb check (pg_column_size(metadata) <= 8192),
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp()
);

create table if not exists public.aos_cia_call_routing_events (
  id bigint generated by default as identity primary key,
  request_id uuid not null default gen_random_uuid(),
  event_type text not null check (event_type in ('ROUTE','FALLBACK','CLAIM','CONSUME','ERROR','CONFIG')),
  advisor_user_id uuid null references public.aos_usuarios(id),
  routing_mode text null,
  route_selected text null check (route_selected is null or route_selected in ('V2','V3')),
  assignment_id uuid null references public.aos_cia_assignments(id),
  plan_id uuid null references public.aos_cia_assignment_plans(id),
  activation_id uuid null references public.aos_audiencia_activaciones(id),
  contact_key text null,
  fallback_reason text null,
  latency_ms integer null check (latency_ms is null or latency_ms >= 0),
  payload jsonb not null default '{}'::jsonb check (pg_column_size(payload) <= 16384),
  occurred_at timestamptz not null default clock_timestamp()
);

create index if not exists idx_cia_call_routing_events_advisor_time
  on public.aos_cia_call_routing_events(advisor_user_id, occurred_at desc);
create index if not exists idx_cia_call_routing_events_assignment
  on public.aos_cia_call_routing_events(assignment_id, occurred_at desc)
  where assignment_id is not null;

alter table public.aos_cia_call_routing_control enable row level security;
alter table public.aos_cia_call_routing_advisors enable row level security;
alter table public.aos_cia_call_routing_events enable row level security;

revoke all on table public.aos_cia_call_routing_control from public, anon, authenticated;
revoke all on table public.aos_cia_call_routing_advisors from public, anon, authenticated;
revoke all on table public.aos_cia_call_routing_events from public, anon, authenticated;

grant select on table public.aos_cia_call_routing_control to service_role;
grant select on table public.aos_cia_call_routing_advisors to service_role;
grant select on table public.aos_cia_call_routing_events to service_role;
