-- CATALOG SEP2026.1 — reconciliation foundation
-- Creates immutable lineage infrastructure and a temporary-to-phase helper function.
-- No patient, sales, quote, payment, revenue, routing or AI-send mutation.
begin;

create table if not exists public.aos_catalogo_reconciliation_lineage_v1 (
  id bigint generated by default as identity primary key,
  reconciliation_code text not null,
  entity_kind text not null check (entity_kind in ('SERVICE','TOPPING')),
  entity_id text not null,
  action text not null check (action in ('UPDATED_CURRENT','INSERTED_CURRENT','INACTIVATED_HISTORICAL')),
  source_row integer,
  source_name text,
  old_name text,
  new_name text,
  snapshot_before jsonb,
  snapshot_after jsonb,
  source_payload jsonb,
  applied_at timestamptz not null default now(),
  unique(reconciliation_code,entity_kind,entity_id,action)
);

comment on table public.aos_catalogo_reconciliation_lineage_v1 is
'Immutable audit lineage for governed catalog reconciliations. Not a second catalog/master.';
revoke all on table public.aos_catalogo_reconciliation_lineage_v1 from public,anon,authenticated;
grant select on table public.aos_catalogo_reconciliation_lineage_v1 to service_role;

create or replace function public.aos_catalogo_reconciliation_lineage_immutable_guard_v1()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  raise exception 'CATALOG_RECONCILIATION_LINEAGE_IMMUTABLE';
end;
$$;

create or replace function public.aos_apply_catalog_sep26_service_row_v1(p jsonb)
returns uuid
language plpgsql
security definer
set search_path=public
as $$
declare
  v_source_row int := (p->>'r')::int;
  v_source_name text := p->>'s';
  v_legacy text := nullif(p->>'l','');
  v_name text := p->>'n';
  v_category text := p->>'c';
  v_price numeric := (p->>'p')::numeric;
  v_currency text := p->>'m';
  v_sessions int := (p->>'cs')::int;
  v_raw_sessions text := p->>'rs';
  v_gift text := p->>'g';
  v_doctor boolean := coalesce((p->>'d')::boolean,false);
  v_nurse boolean := coalesce((p->>'u')::boolean,false);
  v_entity text := coalesce(p->>'e','S');
  v_family text := p->>'f';
  v_brand text := p->>'b';
  v_active text := p->>'a';
  v_indication text := p->>'i';
  v_body text := p->>'ba';
  v_zones int := nullif(p->>'z','')::int;
  v_unit_cap int := nullif(p->>'uc','')::int;
  v_volume numeric := nullif(p->>'v','')::numeric;
  v_syringes int := nullif(p->>'sy','')::int;
  v_family_name text;
  v_id uuid;
  v_before jsonb;
  v_after jsonb;
  v_info jsonb;
  v_composition text;
  v_payload jsonb;
  v_identity jsonb;
begin
  if v_name is null or v_category is null or v_price is null or v_price<=0 then
    raise exception 'SEP26_INVALID_SOURCE_ROW:%',p;
  end if;
  if v_currency not in ('PEN','USD') then
    raise exception 'SEP26_INVALID_CURRENCY:%',v_currency;
  end if;
  if v_sessions is null or v_sessions<1 then
    raise exception 'SEP26_INVALID_CLINICAL_SESSIONS:%',v_name;
  end if;

  v_family_name := case v_family
    when 'DETOX_IONICO' then 'DETOX IÓNICO'
    when 'VITAMINOTERAPIA' then 'VITAMINOTERAPIA'
    when 'FACIALES' then 'FACIALES'
    when 'PEELINGS' then 'PEELINGS'
    when 'BIOREVITALIZACION' then 'BIOREVITALIZACIÓN'
    when 'MESOTERAPIA_MICRONEEDLING' then 'MESOTERAPIA / MICRONEEDLING'
    when 'EXOSOMAS' then 'EXOSOMAS'
    when 'BIOESTIMULACION_DE_COLAGENO' then 'BIOESTIMULACIÓN DE COLÁGENO'
    when 'ACIDO_HIALURONICO' then 'ÁCIDO HIALURÓNICO'
    when 'TOXINA_BOTULINICA' then 'TOXINA BOTULÍNICA'
    when 'ENZIMAS' then 'ENZIMAS'
    when 'HIFU' then 'HIFU'
    when 'RADIOFRECUENCIA_FRACCIONADA' then 'RADIOFRECUENCIA FRACCIONADA'
    when 'TRATAMIENTOS_CAPILARES' then 'TRATAMIENTOS CAPILARES'
    when 'TRATAMIENTOS_CORPORALES' then 'TRATAMIENTOS CORPORALES'
    when 'APARATOLOGIA_CORPORAL' then 'APARATOLOGÍA CORPORAL'
    when 'CRIOLIPOLISIS' then 'CRIOLIPÓLISIS'
    when 'PEPTONAS' then 'PEPTONAS'
    when 'TRATAMIENTOS_GLUTEOS' then 'TRATAMIENTOS GLÚTEOS'
    when 'CONSULTA_OPERATIVO' then 'CONSULTA / OPERATIVO'
    else v_family end;

  v_payload := jsonb_strip_nulls(jsonb_build_object(
    'reconciliation_code','CATALOG_SEP2026_V1',
    'source_file','LISTA DE PRECIOS SEPTIEMBRE - 2026 - SERVICIOS',
    'source_row',v_source_row,
    'source_name',v_source_name,
    'source_n_sessions_raw',v_raw_sessions,
    'gift_raw',v_gift,
    'authoritative_current_price',v_price,
    'currency',v_currency,
    'price_authority_mode','CURRENT_SINGLE_PRICE',
    'verified_at','2026-08-28'
  ));

  v_identity := jsonb_strip_nulls(jsonb_build_object(
    'family_code',v_family,
    'family_name',v_family_name,
    'entity_kind',case when v_entity='O' then 'OPERATIONAL_SUPPLY' else 'CLINICAL_SERVICE' end,
    'clinical_treatment',v_entity<>'O',
    'active_or_technology',v_active,
    'brand',v_brand,
    'indication',v_indication,
    'body_area',v_body,
    'commercial_variant',v_name,
    'zones',v_zones,
    'unit_cap',v_unit_cap,
    'volume_ml',v_volume,
    'syringes',v_syringes,
    'clinical_sessions',v_sessions,
    'source_n_sessions_raw',v_raw_sessions,
    'current_status','CURRENT',
    'aliases',jsonb_build_array(v_source_name,coalesce(v_legacy,v_name),v_name),
    'public_catalog',v_entity<>'O',
    'recommendable',v_entity<>'O',
    'clinical_review_required',(v_legacy is null or (v_family='TOXINA_BOTULINICA' and v_brand is null)),
    'source','SEP2026_PRICE_LIST',
    'source_row',v_source_row,
    'verified_at','2026-08-28'
  ));

  if v_legacy is not null then
    select c.id,
           jsonb_build_object(
             'nombre',c.nombre,'nombre_corto',c.nombre_corto,'categoria',c.categoria,
             'num_sesiones',c.num_sesiones,'precio_base',c.precio_base,'precio_oferta',c.precio_oferta,
             'moneda',c.moneda,'estado',c.estado,'requiere_doctora',c.requiere_doctora,
             'requiere_enfermeria',c.requiere_enfermeria,'composicion',c.composicion,
             'info_extendida',c.info_extendida,'updated_at',c.updated_at
           ),
           c.info_extendida,c.composicion
      into strict v_id,v_before,v_info,v_composition
    from public.aos_catalogo_servicios c
    where c.tipo='SERVICIO' and c.estado='ACTIVO' and c.nombre=v_legacy;

    insert into public.aos_catalogo_reconciliation_lineage_v1
      (reconciliation_code,entity_kind,entity_id,action,source_row,source_name,old_name,new_name,snapshot_before,source_payload)
    values
      ('CATALOG_SEP2026_V1','SERVICE',v_id::text,'UPDATED_CURRENT',v_source_row,v_source_name,v_legacy,v_name,v_before,v_payload);

    update public.aos_catalogo_servicios
    set nombre=v_name,
        nombre_corto=v_name,
        categoria=v_category,
        num_sesiones=v_sessions::text,
        precio_base=v_price,
        precio_oferta=v_price,
        moneda=v_currency,
        requiere_doctora=v_doctor,
        requiere_enfermeria=v_nurse,
        estado='ACTIVO',
        composicion=case when v_family='TOXINA_BOTULINICA' and v_brand is null then null else v_composition end,
        info_extendida=coalesce(v_info,'{}'::jsonb)
          || jsonb_build_object('treatment_identity',v_identity)
          || jsonb_build_object('catalog_sep2026',v_payload),
        updated_at=now()
    where id=v_id;
  else
    if exists(select 1 from public.aos_catalogo_servicios where tipo='SERVICIO' and nombre=v_name) then
      raise exception 'SEP26_NEW_COLLISION:%',v_name;
    end if;

    insert into public.aos_catalogo_servicios
      (nombre,nombre_corto,tipo,categoria,num_sesiones,precio_base,precio_oferta,moneda,
       requiere_doctora,requiere_enfermeria,estado,faqs,info_extendida,updated_at)
    values
      (v_name,v_name,'SERVICIO',v_category,v_sessions::text,v_price,v_price,v_currency,
       v_doctor,v_nurse,'ACTIVO','[]'::jsonb,
       jsonb_build_object('treatment_identity',v_identity)
         || jsonb_build_object('catalog_sep2026',v_payload),now())
    returning id into v_id;

    select jsonb_build_object(
      'nombre',c.nombre,'categoria',c.categoria,'num_sesiones',c.num_sesiones,
      'precio_base',c.precio_base,'precio_oferta',c.precio_oferta,'moneda',c.moneda,
      'estado',c.estado,'requiere_doctora',c.requiere_doctora,
      'requiere_enfermeria',c.requiere_enfermeria,'info_extendida',c.info_extendida
    ) into v_after
    from public.aos_catalogo_servicios c where c.id=v_id;

    insert into public.aos_catalogo_reconciliation_lineage_v1
      (reconciliation_code,entity_kind,entity_id,action,source_row,source_name,old_name,new_name,
       snapshot_before,snapshot_after,source_payload)
    values
      ('CATALOG_SEP2026_V1','SERVICE',v_id::text,'INSERTED_CURRENT',v_source_row,v_source_name,
       null,v_name,null,v_after,v_payload);
  end if;

  return v_id;
exception
  when no_data_found then
    raise exception 'SEP26_LEGACY_NOT_FOUND:%',v_legacy;
  when too_many_rows then
    raise exception 'SEP26_LEGACY_NOT_UNIQUE:%',v_legacy;
end;
$$;

revoke all on function public.aos_apply_catalog_sep26_service_row_v1(jsonb) from public,anon,authenticated;
grant execute on function public.aos_apply_catalog_sep26_service_row_v1(jsonb) to service_role;

do $$
begin
  if (select count(*) from public.aos_catalogo_servicios where tipo='SERVICIO' and estado='ACTIVO')<>167 then
    raise exception 'SEP26 baseline services !=167';
  end if;
  if (select count(*) from public.aos_catalogo_servicios where tipo='PRODUCTO' and estado='ACTIVO')<>50 then
    raise exception 'SEP26 baseline products !=50';
  end if;
  if (select count(*) from public.aos_catalogo_toppings where estado='ACTIVO')<>20 then
    raise exception 'SEP26 baseline toppings !=20';
  end if;
  if exists(select 1 from public.aos_catalogo_reconciliation_lineage_v1 where reconciliation_code='CATALOG_SEP2026_V1') then
    raise exception 'SEP26 reconciliation already present';
  end if;
end $$;

commit;
