-- ASCENDA CIA Phase 6 — universal audience definition library.
-- Additive only. No operational source tables are modified.

create table if not exists public.aos_audiencias (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  descripcion text not null default '',
  tipo text not null default 'DYNAMIC',
  estado text not null default 'ACTIVE',
  schema_version integer not null default 1,
  current_version integer not null default 1,
  created_by_user_id uuid not null references public.aos_usuarios(id) on delete restrict,
  updated_by_user_id uuid not null references public.aos_usuarios(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  archived_by_user_id uuid references public.aos_usuarios(id) on delete restrict,
  constraint aos_audiencias_nombre_len_chk check (char_length(btrim(nombre)) between 3 and 120),
  constraint aos_audiencias_descripcion_len_chk check (char_length(descripcion) <= 1000),
  constraint aos_audiencias_tipo_chk check (tipo in ('DYNAMIC')),
  constraint aos_audiencias_estado_chk check (estado in ('ACTIVE','ARCHIVED')),
  constraint aos_audiencias_schema_version_chk check (schema_version >= 1),
  constraint aos_audiencias_current_version_chk check (current_version >= 1),
  constraint aos_audiencias_archive_consistency_chk check (
    (estado='ACTIVE' and archived_at is null and archived_by_user_id is null)
    or (estado='ARCHIVED' and archived_at is not null and archived_by_user_id is not null)
  )
);

create unique index if not exists aos_audiencias_active_name_uidx
  on public.aos_audiencias (lower(btrim(nombre)))
  where estado='ACTIVE';

create index if not exists aos_audiencias_estado_updated_idx
  on public.aos_audiencias (estado, updated_at desc);

create table if not exists public.aos_audiencia_versiones (
  id uuid primary key default gen_random_uuid(),
  audiencia_id uuid not null references public.aos_audiencias(id) on delete restrict,
  version integer not null,
  filter_dsl jsonb not null,
  reason text not null default '',
  count_cache integer not null default 0,
  resolved_at timestamptz not null default now(),
  created_by_user_id uuid not null references public.aos_usuarios(id) on delete restrict,
  created_at timestamptz not null default now(),
  constraint aos_audiencia_versiones_version_chk check (version >= 1),
  constraint aos_audiencia_versiones_filter_object_chk check (jsonb_typeof(filter_dsl)='object'),
  constraint aos_audiencia_versiones_filter_size_chk check (pg_column_size(filter_dsl) <= 65536),
  constraint aos_audiencia_versiones_reason_len_chk check (char_length(reason) <= 500),
  constraint aos_audiencia_versiones_count_chk check (count_cache >= 0),
  constraint aos_audiencia_versiones_audience_version_uidx unique (audiencia_id, version)
);

create index if not exists aos_audiencia_versiones_audience_created_idx
  on public.aos_audiencia_versiones (audiencia_id, version desc);

create table if not exists public.aos_audiencia_audit (
  id bigint generated by default as identity primary key,
  audiencia_id uuid not null references public.aos_audiencias(id) on delete restrict,
  audiencia_version_id uuid references public.aos_audiencia_versiones(id) on delete restrict,
  action text not null,
  actor_user_id uuid not null references public.aos_usuarios(id) on delete restrict,
  before_state jsonb not null default '{}'::jsonb,
  after_state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint aos_audiencia_audit_action_chk check (action in ('CREATE','VERSION_CREATE','DUPLICATE','ARCHIVE','RESTORE')),
  constraint aos_audiencia_audit_before_size_chk check (pg_column_size(before_state) <= 32768),
  constraint aos_audiencia_audit_after_size_chk check (pg_column_size(after_state) <= 32768)
);

create index if not exists aos_audiencia_audit_audience_created_idx
  on public.aos_audiencia_audit (audiencia_id, created_at desc);

alter table public.aos_audiencias enable row level security;
alter table public.aos_audiencia_versiones enable row level security;
alter table public.aos_audiencia_audit enable row level security;

revoke all on table public.aos_audiencias from public, anon, authenticated;
revoke all on table public.aos_audiencia_versiones from public, anon, authenticated;
revoke all on table public.aos_audiencia_audit from public, anon, authenticated;
revoke all on sequence public.aos_audiencia_audit_id_seq from public, anon, authenticated;

grant all on table public.aos_audiencias to service_role;
grant all on table public.aos_audiencia_versiones to service_role;
grant all on table public.aos_audiencia_audit to service_role;
grant usage, select on sequence public.aos_audiencia_audit_id_seq to service_role;

create or replace function public.aos_cia_audience_version_guard_v1()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare v jsonb;
begin
  if tg_op in ('UPDATE','DELETE') then
    raise exception using errcode='55000', message='AUDIENCE_VERSION_IMMUTABLE';
  end if;
  v:=public.aos_cia_audience_validate_v1(new.filter_dsl);
  if not coalesce((v->>'valid')::boolean,false) then
    raise exception using errcode='22023', message='AUDIENCE_DSL_INVALID';
  end if;
  return new;
end;
$$;

revoke all on function public.aos_cia_audience_version_guard_v1() from public, anon, authenticated;
grant execute on function public.aos_cia_audience_version_guard_v1() to service_role;

drop trigger if exists trg_aos_cia_audience_version_guard_v1 on public.aos_audiencia_versiones;
create trigger trg_aos_cia_audience_version_guard_v1
before insert or update or delete on public.aos_audiencia_versiones
for each row execute function public.aos_cia_audience_version_guard_v1();

create or replace function public.aos_cia_audience_touch_v1()
returns trigger
language plpgsql
set search_path=public
as $$
begin
  new.updated_at:=now();
  return new;
end;
$$;

revoke all on function public.aos_cia_audience_touch_v1() from public, anon, authenticated;
grant execute on function public.aos_cia_audience_touch_v1() to service_role;

drop trigger if exists trg_aos_cia_audience_touch_v1 on public.aos_audiencias;
create trigger trg_aos_cia_audience_touch_v1
before update on public.aos_audiencias
for each row execute function public.aos_cia_audience_touch_v1();
