-- WA-4A.1 Zi Vital knowledge seed — facial
begin;
insert into public.aos_zi_knowledge_entities_v1(entity_key,entity_type,canonical_name,aliases,parent_entity_key,source_key,page_start,page_end,canonical_summary,public_client,advisor_internal,owner_admin,clinical_restricted,system_reference,status,version)
values
('DOMAIN_FACIAL','DOMAIN','Dominio Facial',array['Facial']::text[],'ZI_SYSTEM','ZI_DOMAINS_20260827',2,5,'Imagen, presencia y armonía consciente; integra calidad cutánea, equilibrio estructural y regeneración.','El Dominio Facial trabaja imagen, presencia y armonía consciente. Zi Vital prioriza calidad de piel, equilibrio estructural y regeneración respetando rasgos, identidad y naturalidad.','Antes de recomendar herramientas, identifica si la conversación es sobre calidad cutánea, armonía estructural o regeneración. Eso orienta a Skin Signature, Harmony Design o BioRegen Face.','El dominio facial contiene tres enfoques diferenciados y debe evitar que el catálogo se comunique como procedimientos sueltos.','La evaluación de piel, rostro y tejido corresponde a la consulta médica; el bot o asesor no debe adjudicar un enfoque clínico definitivo por síntomas aislados.','{"summary":"Dominio con enfoques canónicos: APP_SKIN_SIGNATURE, APP_HARMONY_DESIGN, APP_BIOREGEN_FACE.","approaches":["APP_SKIN_SIGNATURE","APP_HARMONY_DESIGN","APP_BIOREGEN_FACE"]}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827'),
('APP_SKIN_SIGNATURE','APPROACH','Skin Signature','{}'::text[],'DOMAIN_FACIAL','ZI_DOMAINS_20260827',2,3,'Enfoque facial orientado a calidad cutánea, salud, hidratación, densidad y luminosidad sin alterar estructuras.','Skin Signature es el enfoque facial centrado en calidad de piel, hidratación, luminosidad y estabilidad cutánea, sin buscar cambios estructurales del rostro.','Úsalo cuando el plan ya está orientado a calidad cutánea. El documento lo vincula con hidrofacial, peelings, Pink Glow, Dermapen, radiofrecuencia fraccionada y productos de cuidado domiciliario.','Es la base de la estética facial consciente dentro del documento y funciona como puerta de entrada o mantenimiento para distintos perfiles.','El documento recomienda valorar estado de la piel y contempla soporte con vitaminas y, en pacientes descritos como inflamados, detox. La necesidad individual debe validarse clínicamente.','{"summary":"Enfoque canónico dentro del sistema Zi Vital.","domain":"DOMAIN_FACIAL","aliases":[],"source_treatments":["Hidrofacial avanzado","Peelings médicos (PQ Age, Biorrepel)","Pink Glow (biorevitalizador)","Dermapen con activos","Radiofrecuencia fraccionada","Mascarillas regenerativas y secantes según biotipo"],"source_products":["Sensiclean","UltrAGlow","Hydrashield","Regushield","Sensishield","SkinRegeneration","Beauty Maker","Astaxantina","Lymdharial / Gotas, Pomada","Power 10 formula soak up helper 30 ml","Power 10 formula firefighter 30 ml","Power 10 formula pore lupin 30 ml","Power 10 formula cera guard 30 ml","Power 10 formula honeydew fairy 30 ml","Ultra eye contour","Serum acne control","Polvo enzimatico","Mascarilla coenzyme Q10 30gr","Esthemax enzyme powder 113","Cardo mariano 500 mg/120"],"source_terms_are_not_canonical_catalog_names":true}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827'),
('APP_HARMONY_DESIGN','APPROACH','Harmony Design','{}'::text[],'DOMAIN_FACIAL','ZI_DOMAINS_20260827',3,4,'Enfoque facial de equilibrio estructural, expresión y soporte con criterio médico y moderación.','Harmony Design es el enfoque facial orientado a equilibrio estructural, expresión y soporte, buscando resultados naturales sin exagerar rasgos.','Explícalo como diseño médico del rostro, no como ''poner volumen''. El documento lo relaciona con ácido hialurónico, perfilamiento, labios, toxina, HIFU facial y enzimas para papada.','Su diferenciador estratégico es moderación, naturalidad y criterio frente a la sobrecorrección.','La selección de puntos, productos y dosis es médica. El documento indica evaluar calidad de piel y complementar con otros enfoques cuando corresponda.','{"summary":"Enfoque canónico dentro del sistema Zi Vital.","domain":"DOMAIN_FACIAL","aliases":[],"source_treatments":["Ácido hialurónico en puntos de anclaje","Perfilamiento facial y nasal","Labios (volumen, forma o hidratación)","Toxina botulínica estratégica","HIFU facial como complemento","Enzimas faciales (reducción de papada)"],"source_products":["Lifting-B","Hydrashield","Regushield","Sensishield","Perfect-F","Redu Fast","Zinc Premium","Lip balm 5g","Lymdharial / Gotas, Pomada","Beauty Maker","Astaxantina","Neuro Vital","Cardo mariano 500 mg/120"],"source_terms_are_not_canonical_catalog_names":true}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827'),
('APP_BIOREGEN_FACE','APPROACH','BioRegen Face','{}'::text[],'DOMAIN_FACIAL','ZI_DOMAINS_20260827',5,5,'Enfoque facial de regeneración, longevidad y sostén biológico con resultados progresivos y naturales.','BioRegen Face es el enfoque facial de regeneración y longevidad. Busca estimular procesos propios del tejido con resultados progresivos y naturales.','Posiciónalo como proceso de regeneración, no como relleno rápido. El documento lo vincula con bioestimuladores, exosomas, PDRN/polinucleótidos, PRP e hidrataciones profundas.','Representa la filosofía de ''regenerar en lugar de rellenar'' y refuerza el posicionamiento de largo plazo.','La elección de bioestimuladores, exosomas, PDRN, PRP o hidrataciones profundas depende de evaluación médica y no debe automatizarse.','{"summary":"Enfoque canónico dentro del sistema Zi Vital.","domain":"DOMAIN_FACIAL","aliases":[],"source_treatments":["Bioestimuladores de colágeno","Exosomas","Polinucleótidos / PDRN","PRP","Hidrataciones profundas con AH"],"source_products":["Beauty Maker","Neuro Vital","Astaxantina","Hydrashield","Regushield","Sensishield","SkinRegeneration","UltrAGlow","Cardo mariano 500 mg/120","Anti-hair loss shampoo 150 ml","Spray minoxidil","Nf cap women o men anti-hair"],"source_terms_are_not_canonical_catalog_names":true}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827')
on conflict (entity_key) do update set
 entity_type=excluded.entity_type,canonical_name=excluded.canonical_name,aliases=excluded.aliases,
 parent_entity_key=excluded.parent_entity_key,source_key=excluded.source_key,page_start=excluded.page_start,
 page_end=excluded.page_end,canonical_summary=excluded.canonical_summary,public_client=excluded.public_client,
 advisor_internal=excluded.advisor_internal,owner_admin=excluded.owner_admin,
 clinical_restricted=excluded.clinical_restricted,system_reference=excluded.system_reference,
 status='ACTIVE',version=excluded.version,updated_at=now();
commit;
