-- SUPERSEDED / NEVER APPLIED.
-- Provisional filename created before Supabase assigned the canonical remote version.
-- Canonical migration: 20260814065732_cia_phase10_plan_health_scaling_fix_v1.sql
