-- ASCENDA OS — CIA Phase 4 confirmed ISDIN legacy aliases
begin;
insert into public.aos_product_alias_overrides(alias_text,canonical_short_name,reason) values
('ESENTIAL CLEASSING','CLEANSING ISDIN','LEGACY_TYPO'),
('ESSENTIAL CLEASING','CLEANSING ISDIN','LEGACY_TYPO'),
('ESSENTIAL CLEASING - 20%','CLEANSING ISDIN','LEGACY_DISCOUNT_ALIAS'),
('FOTOPROTECTOR STICK','FOTO STICK ISDIN','LEGACY_ALIAS'),
('FOTOPROTECTOR STICK ISDIN','FOTO STICK ISDIN','LEGACY_ALIAS'),
('FOTOPROTECTOR INVISBLE STICK','FOTO STICK ISDIN','LEGACY_TYPO'),
('FOTOULTRA 100 ACTIVE UNIFY 50 ML','FOTOULTRA','LEGACY_SIZE_ALIAS'),
('FOTOULTRA 100 ACTIVE UNIFY 50 ML-ISDIN','FOTOULTRA','LEGACY_SIZE_ALIAS'),
('HIALURONIC CONCENTRATE','HYAL CONC ISDIN','LEGACY_ALIAS'),
('HIALURONIC MOINSTURE OIL','HYAL MOIST OILY','LEGACY_TYPO'),
('HYALURONIC MOISTURE OILY Y COMBINATION SKIN 50 G- ISDIN','HYAL MOIST OILY','LEGACY_ALIAS')
on conflict(alias_text) do update set canonical_short_name=excluded.canonical_short_name,reason=excluded.reason,active=true,updated_at=now();
commit;
