-- CIA Phase 5 — Runtime V2 foundation.
begin;
create or replace function public.aos_cia_normalize_contact_key_v1(p_raw text)
returns text language sql immutable parallel safe as $$
select case when length(regexp_replace(coalesce(p_raw,''),'\D','','g'))=9 then regexp_replace(coalesce(p_raw,''),'\D','','g')
 when length(regexp_replace(coalesce(p_raw,''),'\D','','g'))=11 and left(regexp_replace(coalesce(p_raw,''),'\D','','g'),2)='51' then right(regexp_replace(coalesce(p_raw,''),'\D','','g'),9)
 else null end;$$;

create table if not exists public.aos_cia_segment_runtime_cache_v2(contact_key text primary key,policy_key text not null,policy_version integer not null,policy_status text not null,value_tier text not null,value_score integer not null,lifecycle text not null,engagement text not null,engagement_score integer not null,traits text[] not null default array[]::text[],explanation jsonb not null default '{}'::jsonb,segment_calculated_at timestamptz,cache_refreshed_at timestamptz not null default now());
alter table public.aos_cia_segment_runtime_cache_v2 enable row level security;
revoke all on public.aos_cia_segment_runtime_cache_v2 from public,anon,authenticated;
grant select,insert,update,delete on public.aos_cia_segment_runtime_cache_v2 to service_role;
insert into public.aos_cia_segment_runtime_cache_v2(contact_key,policy_key,policy_version,policy_status,value_tier,value_score,lifecycle,engagement,engagement_score,traits,explanation,segment_calculated_at,cache_refreshed_at)
select contact_key,policy_key,policy_version,policy_status,value_tier,value_score,lifecycle,engagement,engagement_score,traits,explanation,calculated_at,statement_timestamp() from public.aos_cia_customer_segments_v1
on conflict(contact_key)do update set policy_key=excluded.policy_key,policy_version=excluded.policy_version,policy_status=excluded.policy_status,value_tier=excluded.value_tier,value_score=excluded.value_score,lifecycle=excluded.lifecycle,engagement=excluded.engagement,engagement_score=excluded.engagement_score,traits=excluded.traits,explanation=excluded.explanation,segment_calculated_at=excluded.segment_calculated_at,cache_refreshed_at=excluded.cache_refreshed_at;

create table if not exists public.aos_cia_email_runtime_cache_v2(contact_key text primary key,identity_confidence text,sent_count integer not null default 0,never_sent boolean,last_sent_at timestamptz,days_since_last integer,delivered_count integer not null default 0,opened_count integer not null default 0,clicked_count integer not null default 0,bounced_count integer not null default 0,last_event_at timestamptz,cache_refreshed_at timestamptz not null default now());
alter table public.aos_cia_email_runtime_cache_v2 enable row level security;
revoke all on public.aos_cia_email_runtime_cache_v2 from public,anon,authenticated;
grant select,insert,update,delete on public.aos_cia_email_runtime_cache_v2 to service_role;
insert into public.aos_cia_email_runtime_cache_v2(contact_key,identity_confidence,sent_count,never_sent,last_sent_at,days_since_last,delivered_count,opened_count,clicked_count,bounced_count,last_event_at,cache_refreshed_at)
select contact_key,identity_confidence,sent_count,never_sent,last_sent_at,days_since_last,delivered_count,opened_count,clicked_count,bounced_count,last_event_at,statement_timestamp() from public.aos_cia_email_facts_v1
on conflict(contact_key)do update set identity_confidence=excluded.identity_confidence,sent_count=excluded.sent_count,never_sent=excluded.never_sent,last_sent_at=excluded.last_sent_at,days_since_last=excluded.days_since_last,delivered_count=excluded.delivered_count,opened_count=excluded.opened_count,clicked_count=excluded.clicked_count,bounced_count=excluded.bounced_count,last_event_at=excluded.last_event_at,cache_refreshed_at=excluded.cache_refreshed_at;

create or replace view public.aos_cia_profile_fast_v2 with(security_invoker=true)as
select i.contact_key,i.identity_status,i.identity_conflict,i.canonical_patient_id,i.canonical_names,i.canonical_surnames,i.canonical_email,p."ESTADO_PACIENTE" patient_state,coalesce(nullif(btrim(p."ETIQUETA_BASE"),''),nullif(btrim(be.etiqueta),''))base_label,nullif(btrim(be.campana),'')base_campaign,nullif(btrim(p."SEDE_PRINCIPAL"),'')raw_branch,nullif(btrim(p.departamento),'')department,nullif(btrim(p.ciudad),'')city,nullif(btrim(p.distrito),'')district,nullif(upper(btrim(p."Sexo")),'')sex,case when p."Fecha de nacimiento"~'^\d{1,2}/\d{1,2}/\d{4}$' then date_part('year',age((now()at time zone 'America/Lima')::date,to_date(p."Fecha de nacimiento",'DD/MM/YYYY')))::integer when p."Fecha de nacimiento"~'^\d{4}-\d{2}-\d{2}$' then date_part('year',age((now()at time zone 'America/Lima')::date,to_date(p."Fecha de nacimiento",'YYYY-MM-DD')))::integer else null end age_years
from public.aos_cia_contact_identity_v1 i left join public.aos_pacientes p on p."ID_PACIENTE"=i.canonical_patient_id left join public.aos_base_etiquetas be on public.aos_cia_normalize_contact_key_v1(be.numero)=i.contact_key;
revoke all on public.aos_cia_profile_fast_v2 from public,anon,authenticated;grant select on public.aos_cia_profile_fast_v2 to service_role;

create table if not exists public.aos_cia_filter_execution_map_v2(field_key text primary key,source_key text not null,source_column text,special_key text,data_type text not null,updated_at timestamptz not null default now());
alter table public.aos_cia_filter_execution_map_v2 enable row level security;revoke all on public.aos_cia_filter_execution_map_v2 from public,anon,authenticated;grant select on public.aos_cia_filter_execution_map_v2 to service_role;
insert into public.aos_cia_filter_execution_map_v2(field_key,source_key,source_column,special_key,data_type,updated_at)
select r.field_key,case when r.field_key in('contact.exists_as_lead','lead.called_since_latest_entry','lead.unworked_since_latest_entry','calls.never_called','appointments.never_had','sales.never_bought','crm.branch') then 'SPECIAL' when r.field_key in('contact.identity_status','contact.identity_conflict') then 'IDENTITY' when r.field_key like 'contact.%' or r.field_key like 'crm.%' then 'PROFILE' when r.field_key like 'lead.%' then 'LEAD' when r.field_key like 'calls.%' then 'CALL' when r.field_key like 'appointments.%' then 'APPOINTMENT' when r.field_key like 'followups.%' then 'FOLLOWUP' when r.field_key like 'email.%' then 'EMAIL' when r.field_key like 'segment.%' then 'SEGMENT' when r.field_key in('sales.products','sales.product_categories','sales.product_unresolved_count','sales.services','sales.service_categories','sales.service_category_unresolved_count') then 'PURCHASE' when r.field_key like 'sales.%' then 'SALE' else 'PROFILE' end,null,case r.field_key when 'contact.exists_as_lead' then 'EXISTS_AS_LEAD' when 'lead.called_since_latest_entry' then 'LEAD_CALLED_SINCE' when 'lead.unworked_since_latest_entry' then 'LEAD_UNWORKED' when 'calls.never_called' then 'CALLS_NEVER' when 'appointments.never_had' then 'APPOINTMENTS_NEVER' when 'sales.never_bought' then 'SALES_NEVER' when 'crm.branch' then 'CRM_BRANCH' else null end,r.data_type,statement_timestamp() from public.aos_audience_filter_registry r where r.active
on conflict(field_key)do update set source_key=excluded.source_key,source_column=excluded.source_column,special_key=excluded.special_key,data_type=excluded.data_type,updated_at=excluded.updated_at;

create or replace view public.aos_cia_branch_fast_v2 with(security_invoker=true)as select p.contact_key,coalesce(p.raw_branch,nullif(btrim(s.latest_branch),''),nullif(btrim(a.next_branch),''),nullif(btrim(a.last_branch),''))branch from public.aos_cia_profile_fast_v2 p left join public.aos_cia_sales_facts_v1 s using(contact_key) left join public.aos_cia_appointment_facts_v1 a using(contact_key);
create or replace view public.aos_cia_profile_adapter_v2 with(security_invoker=true)as select p.contact_key,p.identity_status,p.identity_conflict,p.canonical_patient_id,case when p.canonical_email is null or btrim(p.canonical_email)='' then null when lower(btrim(p.canonical_email))~'^[^@\s]+@[^@\s]+\.[^@\s]+$' then true else false end email_valid,(p.canonical_patient_id is not null)exists_as_patient,p.patient_state,p.base_label,p.base_campaign,p.department,p.city,p.district,p.sex,p.age_years,case when p.age_years is null then null when p.age_years<18 then 'UNDER_18' when p.age_years<=24 then '18_24' when p.age_years<=34 then '25_34' when p.age_years<=44 then '35_44' when p.age_years<=54 then '45_54' when p.age_years<=64 then '55_64' else '65_PLUS' end::text age_band from public.aos_cia_profile_fast_v2 p;
create or replace view public.aos_cia_lead_adapter_v2 with(security_invoker=true)as select contact_key,lead_count,days_since_last_lead,latest_interest,latest_interest_type,interests as lead_interests,ads as lead_ads from public.aos_cia_lead_facts_v1;
create or replace view public.aos_cia_call_adapter_v2 with(security_invoker=true)as select contact_key,call_count,days_since_last_call,latest_status as latest_call_status,latest_substatus as latest_call_substatus,ever_statuses as call_ever_statuses,called_today,effective_contact_count from public.aos_cia_call_facts_v1;
create or replace view public.aos_cia_appointment_adapter_v2 with(security_invoker=true)as select contact_key,appointment_count,last_appointment_at,last_appointment_status,next_appointment_at,has_future_appointment,no_show_count,ever_no_show,attended_count,appointment_statuses,case when next_appointment_at is not null then(next_appointment_at-(now()at time zone 'America/Lima')::date)::integer end days_until_next_appointment from public.aos_cia_appointment_facts_v1;
create or replace view public.aos_cia_sale_adapter_v2 with(security_invoker=true)as select contact_key,sale_count,revenue_lifetime,days_since_last_sale,product_count,service_count,latest_item_type,payment_states,payment_methods from public.aos_cia_sales_facts_v1;
create or replace view public.aos_cia_followup_adapter_v2 with(security_invoker=true)as select contact_key,pending_count as pending_followup_count,overdue_count as overdue_followup_count,next_followup_at,treatments as followup_treatments,case when next_followup_at is not null then(next_followup_at-(now()at time zone 'America/Lima')::date)::integer end days_until_next_followup from public.aos_cia_followup_facts_v1;
create or replace view public.aos_cia_email_adapter_v2 with(security_invoker=true)as select contact_key,sent_count as email_sent_count,never_sent as email_never_sent,days_since_last as email_days_since_last,opened_count as email_opened_count,clicked_count as email_clicked_count,bounced_count as email_bounced_count from public.aos_cia_email_runtime_cache_v2;
create or replace view public.aos_cia_segment_adapter_v2 with(security_invoker=true)as select contact_key,value_tier,value_score,lifecycle,engagement,traits from public.aos_cia_segment_runtime_cache_v2;
create or replace view public.aos_cia_purchase_adapter_v2 with(security_invoker=true)as select contact_key,canonical_products,product_categories,product_unresolved_count,canonical_services,service_categories,service_category_unresolved_count,service_unresolved_count from public.aos_cia_purchase_detail_facts_v1;
revoke all on public.aos_cia_branch_fast_v2,public.aos_cia_profile_adapter_v2,public.aos_cia_lead_adapter_v2,public.aos_cia_call_adapter_v2,public.aos_cia_appointment_adapter_v2,public.aos_cia_sale_adapter_v2,public.aos_cia_followup_adapter_v2,public.aos_cia_email_adapter_v2,public.aos_cia_segment_adapter_v2,public.aos_cia_purchase_adapter_v2 from public,anon,authenticated;
grant select on public.aos_cia_branch_fast_v2,public.aos_cia_profile_adapter_v2,public.aos_cia_lead_adapter_v2,public.aos_cia_call_adapter_v2,public.aos_cia_appointment_adapter_v2,public.aos_cia_sale_adapter_v2,public.aos_cia_followup_adapter_v2,public.aos_cia_email_adapter_v2,public.aos_cia_segment_adapter_v2,public.aos_cia_purchase_adapter_v2 to service_role;
commit;
