-- REMOTE SYNC: already applied live as 20260813211008. Additive audit table only.
create table if not exists public.aos_audiencia_activacion_eventos (
  id bigint generated by default as identity primary key,
  activacion_id uuid not null references public.aos_audiencia_activaciones(id) on delete restrict,
  event_type text not null,
  actor_user_id uuid not null references public.aos_usuarios(id) on delete restrict,
  from_state text,
  to_state text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint aos_audiencia_activacion_eventos_type_chk check (event_type in ('CREATE','START','PAUSE','RESUME','COMPLETE','CANCEL')),
  constraint aos_audiencia_activacion_eventos_to_chk check (to_state in ('DRAFT','ACTIVE','PAUSED','COMPLETED','CANCELLED'))
);
create index if not exists aos_audiencia_activacion_eventos_activation_created_idx on public.aos_audiencia_activacion_eventos(activacion_id,created_at,id);