-- WA-4A.1 Zi Vital knowledge seed — care
begin;
insert into public.aos_zi_knowledge_entities_v1(entity_key,entity_type,canonical_name,aliases,parent_entity_key,source_key,page_start,page_end,canonical_summary,public_client,advisor_internal,owner_admin,clinical_restricted,system_reference,status,version)
values
('CARE_PROCESS','PROCESS','Proceso de Atención Zi Vital','{}'::text[],'ZI_SYSTEM','ZI_ATTENTION_20260827',1,8,'Recorrido consciente y lineal que integra funciones clínicas, emocionales, comerciales y legales.','La atención Zi Vital está planteada como un recorrido: primero se entiende el caso, luego se explica el proceso, la doctora evalúa y diseña el plan, y después se aterrizan los siguientes pasos.','Respeta la secuencia: recepción → triaje → explicación previa → consulta médica → aterrizaje del plan → consentimiento/preparación/procedimiento → seguimiento. No adelantes venta antes de comprensión y criterio clínico.','El proceso busca construir confianza, comprensión, autoridad, valor percibido, seguridad, contención y continuidad; debe auditarse como experiencia y no solo como flujo operativo.','La consulta médica y la validación del plan pertenecen a la doctora. El triaje y la preparación no sustituyen diagnóstico.','{"summary":"Secuencia canónica de siete fases con cuatro subfases dentro de la Fase 6.","phases":["CARE_F1","CARE_F2","CARE_F3","CARE_F4","CARE_F5","CARE_F6","CARE_F7"],"roles":["ROLE_RECEPCION","ROLE_ENFERMERIA","ROLE_DOCTORA"]}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827'),
('ROLE_RECEPCION','ROLE','Recepcionista',array['Recepción']::text[],'CARE_PROCESS','ZI_ATTENTION_20260827',1,8,'Rol de orden, apertura, contención inicial, aterrizaje del plan y cierre.','Recepción te guía en el registro, la explicación práctica del plan y el cierre de la atención.','Responsable de orden, apertura, contención inicial, aterrizaje y cierre; no reemplaza criterio médico.','Debe sostener seriedad, claridad y continuidad sin convertir el proceso en presión de venta.','No diagnostica ni valida indicaciones clínicas.','{"summary":"Rol operativo canónico: ROLE_RECEPCION. Sin superposición con los otros roles del documento."}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827'),
('ROLE_ENFERMERIA','ROLE','Enfermería','{}'::text[],'CARE_PROCESS','ZI_ATTENTION_20260827',1,8,'Rol de triaje, educación, preparación, ejecución y acompañamiento.','Enfermería realiza el triaje, prepara al paciente y acompaña el procedimiento según el caso.','Su función es escucha estructurada, evaluación básica, educación, preparación, ejecución y acompañamiento dentro de su alcance.','Es clave para transformar espera y preparación en comprensión y contención.','No sustituye la evaluación y diseño del plan médico.','{"summary":"Rol operativo canónico: ROLE_ENFERMERIA. Sin superposición con los otros roles del documento."}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827'),
('ROLE_DOCTORA','ROLE','Doctora','{}'::text[],'CARE_PROCESS','ZI_ATTENTION_20260827',1,8,'Rol de diagnóstico, criterio clínico, diseño del plan y validación médica.','La doctora evalúa, explica el caso y diseña el plan de trabajo.','Retoma el triaje, profundiza, evalúa y recomienda desde criterio médico; la decisión final del paciente no debe forzarse.','Es la fuente de autoridad clínica del recorrido y debe separarse de la presión comercial.','Diagnóstico, criterio clínico, diseño del plan y validación médica pertenecen a este rol.','{"summary":"Rol operativo canónico: ROLE_DOCTORA. Sin superposición con los otros roles del documento."}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827'),
('CARE_F1','CARE_PHASE','Recepción y apertura formal del caso','{}'::text[],'CARE_PROCESS','ZI_ATTENTION_20260827',1,2,'Orden, profesionalismo y seguridad desde el primer minuto.','En recepción se abre formalmente el caso y se completan los datos necesarios antes de continuar.','Verifica filiación e identificación y no continúes el flujo si el proceso formal no está completo.','La apertura formal construye confianza y percepción de estándar médico.','Los datos personales y médicos deben manejarse según el protocolo; la continuidad depende del registro formal.','{"summary":"Fase 1 del Proceso de Atención Zi Vital.","order":1}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827'),
('CARE_F2','CARE_PHASE','Triaje consciente','{}'::text[],'CARE_PROCESS','ZI_ATTENTION_20260827',2,3,'Escucha estructurada y evaluación inicial para preparar una consulta eficiente y humana.','En triaje, enfermería busca entender qué motiva la visita, antecedentes relevantes, expectativas y contexto antes de la consulta.','Realiza las preguntas de triaje de forma conversacional, no como checklist frío, y registra la información para la consulta.','El triaje construye vínculo y comprensión y evita venta apresurada.','El triaje recoge información y signos básicos, pero no diagnostica.','{"summary":"Fase 2 del Proceso de Atención Zi Vital.","order":2,"triage_questions":["¿Qué te motivó a venir hoy a Zi Vital?","¿Qué es lo que más te incomoda actualmente de tu piel, cuerpo o cabello?","¿Has pasado recientemente por una etapa de estrés, cambio personal o exigencia fuerte?","¿Has realizado antes tratamientos estéticos o regenerativos? ¿Cómo fue esa experiencia?","¿Qué te gustaría sentir o ver como resultado de este proceso?","¿Hay algo que definitivamente no te gustaría hacer o que te genere temor?","¿Tienes alguna condición médica, alergia o tratamiento actual que debamos considerar?","¿Prefieres procesos progresivos o resultados más visibles en menos tiempo?","¿Te imaginas este cuidado como algo puntual o como un proceso a sostener?","Para orientarte bien y no proponerte algo fuera de lugar, ¿hay un rango de inversión en el que te sientas cómodo en esta etapa?"]}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827'),
('CARE_F3','CARE_PHASE','Explicación previa del proceso y enfoques','{}'::text[],'CARE_PROCESS','ZI_ATTENTION_20260827',4,4,'Reduce ansiedad y ordena expectativas antes de la consulta médica.','Antes de la consulta se explica que Zi Vital trabaja por enfoques y planes; la doctora recomienda y el paciente decide cómo avanzar.','Reduce ansiedad: aclara que la consulta sirve para entender el caso y armar un plan, y que no todo debe hacerse el mismo día.','La preconsulta reduce el miedo a que ''le vendan'' y prepara una consulta abierta.','La explicación previa no determina tratamiento ni enfoque clínico final.','{"summary":"Fase 3 del Proceso de Atención Zi Vital.","order":3}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827'),
('CARE_F4','CARE_PHASE','Consulta médica personalizada','{}'::text[],'CARE_PROCESS','ZI_ATTENTION_20260827',4,5,'Evaluación clínica, escucha, explicación clara y diseño del plan.','La doctora realiza la evaluación, explica lo que observa y diseña un plan con prioridades, fases y tiempos.','No vendas por la doctora: la doctora evalúa, explica y recomienda. El asesor recibe después el plan ya definido.','La consulta construye autoridad real mediante lenguaje de recomendación.','La evaluación y diseño del plan pertenecen a la doctora.','{"summary":"Fase 4 del Proceso de Atención Zi Vital.","order":4}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827'),
('CARE_F5','CARE_PHASE','Aterrizaje del plan, cotización y decisión','{}'::text[],'CARE_PROCESS','ZI_ATTENTION_20260827',5,5,'Traduce el plan médico a una decisión clara, sostenible y sin presión.','Después de la consulta se explica el plan, el orden de los pasos, la cotización y opciones de pago sin presionar la decisión.','Traduce el plan médico a pasos, valor y opciones. Acompaña la decisión sin presión.','El aterrizaje construye valor percibido y reduce choque por precio al explicar proceso, no solo costo.','El equipo comercial no debe modificar el criterio médico para cerrar una venta.','{"summary":"Fase 5 del Proceso de Atención Zi Vital.","order":5}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827'),
('CARE_F6','CARE_PHASE','Consentimientos, preparación y procedimiento','{}'::text[],'CARE_PROCESS','ZI_ATTENTION_20260827',5,7,'Seguridad legal, contención emocional y ejecución clínica.','Antes del procedimiento se completan consentimientos, preparación y explicación de lo que se realizará; el procedimiento se registra según el protocolo.','Explica consentimientos, sensaciones y pasos; el documento permite educación y upselling consciente durante el procedimiento, sin cierre forzado.','Consentimientos y preparación construyen seguridad y contención; la educación durante el procedimiento permite upselling ético.','Consentimientos, preparación y ejecución deben seguir protocolos; cualquier decisión clínica queda en el rol autorizado.','{"summary":"Fase 6 del Proceso de Atención Zi Vital.","order":6,"subphases":["Firma de documentos y consentimiento informado","Preparación del paciente (Enfermería)","Ejecución del procedimiento","Registro fotográfico clínico"]}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827'),
('CARE_F7','CARE_PHASE','Cierre, seguimiento y despedida','{}'::text[],'CARE_PROCESS','ZI_ATTENTION_20260827',7,7,'Continuidad, programación de siguientes sesiones y despedida cuidada.','Al finalizar se organizan siguientes sesiones, recomendaciones complementarias y continuidad del proceso.','Programa continuidad, comunica productos complementarios cuando correspondan y cierra con claridad.','El cierre construye continuidad y evita una relación de una sola visita.','Las recomendaciones post procedimiento y siguientes sesiones deben respetar el plan y la evolución del paciente.','{"summary":"Fase 7 del Proceso de Atención Zi Vital.","order":7}'::jsonb,'ACTIVE','ZI_KNOWLEDGE_V1_20260827')
on conflict (entity_key) do update set
 entity_type=excluded.entity_type,canonical_name=excluded.canonical_name,aliases=excluded.aliases,
 parent_entity_key=excluded.parent_entity_key,source_key=excluded.source_key,page_start=excluded.page_start,
 page_end=excluded.page_end,canonical_summary=excluded.canonical_summary,public_client=excluded.public_client,
 advisor_internal=excluded.advisor_internal,owner_admin=excluded.owner_admin,
 clinical_restricted=excluded.clinical_restricted,system_reference=excluded.system_reference,
 status='ACTIVE',version=excluded.version,updated_at=now();
commit;
