'use strict'
const fs=require('fs')
const path=require('path')
const root=path.resolve(__dirname,'../..')
const migration=fs.readFileSync(path.join(root,'supabase/migrations/20260817224500_s15_unified_notification_events.sql'),'utf8')
const rollback=fs.readFileSync(path.join(root,'supabase/rollback/20260817224500_s15_unified_notification_events_rollback.sql'),'utf8')
const push=fs.readFileSync(path.join(root,'app/push-notifications-s14.js'),'utf8')
const server=fs.readFileSync(path.join(root,'app/server-f17.js'),'utf8')
const client=fs.readFileSync(path.join(root,'app/public/notification-push-s14.js'),'utf8')
const center=fs.readFileSync(path.join(root,'app/public/notification-center-s15.js'),'utf8')
function ok(v,m){if(!v){console.error('S15 CONTRACT FAIL:',m);process.exit(1)}}

for(const col of ['para_user_id','channel','event_type','route','entity_id','dedupe_key','in_app_enabled','push_enabled','push_after','push_status'])ok(migration.includes('add column if not exists '+col),'notification column missing: '+col)
ok(migration.includes('create unique index if not exists aos_notificaciones_dedupe_v1_uq'),'dedupe unique index missing')
ok(migration.includes('create table if not exists public.aos_notification_policies_v1'),'policy registry missing')
for(const ev of ['SALE_ADDED','ADMIN_SALES_DIGEST','COMMISSION_ADJUSTED','APPOINTMENT_CREATED','ADMIN_APPOINTMENT_DIGEST','APPOINTMENT_ATTENDED','APPOINTMENT_NO_SHOW','APPOINTMENT_CANCELLED','APPOINTMENT_RESCHEDULED','ADMIN_ATTENDED_DIGEST','ADMIN_NO_SHOW_DIGEST','INTERNAL_CHAT_MESSAGE','TASK_ASSIGNED','MANUAL_NOTIFICATION'])ok(migration.includes("'"+ev+"'"),'policy/event missing: '+ev)
ok(migration.includes("('INTERNAL_CHAT_MESSAGE','CHAT',false,true"),'chat must remain push-only to avoid double in-app unread')
ok(migration.includes("('ADMIN_SALES_DIGEST','SALES',true,true,'NORMAL',60"),'admin sales must be aggregated')
ok(migration.includes("('ADMIN_APPOINTMENT_DIGEST','AGENDA',true,true,'NORMAL',60"),'admin appointment activity must be aggregated')
ok(migration.includes('aos_notification_resolve_user_v1'),'identity-backed notification resolver missing')
ok(migration.includes("if v_ref='ADMIN'"),'ADMIN compatibility alias missing')
ok(migration.includes('aos_notification_sale_commission_v1'),'commission parity helper missing')
ok(migration.includes("if v_tipo='SERVICIO' then return round(v_monto*0.005,2)"),'service commission parity changed')
ok(migration.includes('aos_notification_emit_v1'),'canonical event projector missing')
ok(migration.includes('on conflict(dedupe_key) where dedupe_key is not null do nothing'),'dedupe upsert gate missing')
ok(migration.includes('for update skip locked'),'push outbox claim must be concurrency safe')
ok(migration.includes("push_status='CLAIMED'"),'push claim state missing')
ok(migration.includes('aos_admin_notificaciones_v1'),'filtered admin notification reader missing')
ok(migration.includes('aos_mis_mensajes'),'advisor coordination compatibility projection missing')
for(const trg of ['trg_aos_notification_sale_v1','trg_aos_notification_commission_adjust_v1','trg_aos_notification_agenda_insert_v1','trg_aos_notification_agenda_update_v1','trg_aos_notification_message_v1','trg_aos_notification_task_v1'])ok(migration.includes(trg),'business trigger missing: '+trg)
ok(migration.includes("st in ('ASISTIO','EFECTIVA')"),'attendance states not covered')
ok(migration.includes("st='NO ASISTIO'"),'no-show state not covered')
ok(migration.includes("st='CANCELADA'")&&migration.includes("st='REAGENDADA'"),'cancel/reschedule states not covered')

ok(push.includes('function genericEnvelope(n)'),'generic AOS_PUSH envelope missing')
ok(push.includes("version: 'AOS_PUSH_V1'"),'generic push must preserve AOS_PUSH_V1')
ok(push.includes("rpc('aos_notification_push_claim_v1'"),'generic push claim missing')
ok(push.includes('async function dispatchPendingNotifications'),'notification outbox dispatcher missing')
ok(push.includes("await finishNotification(n.id, 'DELIVERED'"),'notification completion missing')
ok(server.includes('let notificationPumpBusy = false'),'pump overlap guard missing')
ok(server.includes('setInterval(function() { runNotificationPump()'), 'notification pump cadence missing')
ok(server.includes("console.error('[S15] notification pump fail-open'"),'notification pump must be fail-open')
ok(server.includes('stopNotificationPump(); server.close'),'pump shutdown cleanup missing')

ok(client.includes("'/notification-center-s15.js?v=20260817-s15-p01'")||client.includes("'/notification-center-s15.js?v=20260817-s15-auth-p02'"),'global notification center loader missing')
ok(client.includes('#nav-advisor-sales')&&client.includes('#nav-admin-agenda'),'notification opt-in gesture must cover non-WhatsApp modules')
ok(center.includes("d.type==='AOS_PUSH_EVENT'"),'open-app generic push listener missing')
ok(center.includes("sbRpc('aos_admin_notificaciones_v1'")||center.includes("api('/api/notifications/inbox?limit=50')"),'admin notification filter patch missing')
ok(center.includes('AOS_NOTIFICATION_CENTER.readAndOpen'),'notification read+route UX missing')
for(const ch of ['WHATSAPP','SALES','COMMISSION','AGENDA','CHAT','TASKS','SENTINEL','SYSTEM'])ok(center.includes(ch+':{')||center.includes(ch+"':{"),'channel visual distinction missing: '+ch)

ok(rollback.includes('drop trigger if exists trg_aos_notification_sale_v1'),'rollback trigger coverage missing')
ok(rollback.includes('drop table if exists public.aos_notification_policies_v1'),'rollback policy cleanup missing')
ok(rollback.includes('create or replace function public.aos_enviar_notificacion'),'manual notification rollback missing')
ok(rollback.includes('create or replace function public.aos_mis_mensajes'),'coordination rollback missing')

console.log('S15 unified notification contract PASS')
