'use strict'
const fs=require('fs'),path=require('path')
const root=path.resolve(__dirname,'../..')
const sql=fs.readFileSync(path.join(root,'supabase/migrations/20260817224700_s15_legacy_notification_bridge.sql'),'utf8')
const rollback=fs.readFileSync(path.join(root,'supabase/rollback/20260817224700_s15_legacy_notification_bridge_rollback.sql'),'utf8')
const center=fs.readFileSync(path.join(root,'app/public/notification-center-s15.js'),'utf8')
const agentIcon=fs.readFileSync(path.join(root,'app/public/icons/channel-agent.svg'),'utf8')
const server=fs.readFileSync(path.join(root,'app/server.js'),'utf8')
function ok(v,m){if(!v){console.error('S15 LEGACY BRIDGE CONTRACT FAIL:',m);process.exit(1)}}

ok(sql.includes("('AGENT_ALERT','AGENTS',true,true"),'AGENT_ALERT policy missing or push disabled')
ok(sql.includes("('LEGACY_NOTIFICATION','SYSTEM',true,true"),'generic legacy policy missing or push disabled')
ok(sql.includes("upper(coalesce(new.de,''))='AGENTES_AI'"),'legacy AGENTES_AI detection missing')
ok(sql.includes("like '%BRUNO%'"),'Bruno legacy alert detection missing')
ok(sql.includes("like '%LEÓN%'")||sql.includes("like '%LEON%'"),'Leon legacy alert detection missing')
ok(sql.includes("if nullif(trim(coalesce(new.event_type,'')),'') is not null then return new"),'native S15 events must bypass legacy bridge')
ok(sql.includes("new.push_enabled:=pol.web_push_enabled"),'future legacy notifications must inherit Web Push policy')
ok(sql.includes("new.push_status:=case when pol.web_push_enabled then 'PENDING' else 'SKIPPED' end"),'future legacy push state projection missing')
ok(sql.includes('before insert on public.aos_notificaciones'),'legacy bridge must normalize before insert')
ok(sql.includes("push_enabled=false")&&sql.includes("push_status='SKIPPED'"),'historical agent alerts must never be replayed to Web Push')
ok(sql.includes("metadata=coalesce(n.metadata,'{}'::jsonb)||jsonb_build_object('legacy_backfill',true"),'historical agent backfill traceability missing')
ok(sql.includes("channel='AGENTS'")&&sql.includes("event_type='AGENT_ALERT'"),'historical agent rows must be classified')
ok(sql.includes("aos_notification_resolve_user_v1(n.para)"),'historical legacy rows must bind to canonical user identity')
ok(center.includes("AGENTS:{emoji:'🤖',label:'Agentes AI'}"),'unified center must distinguish AI-agent notifications')
ok(agentIcon.includes('<svg')&&agentIcon.includes('#4F46E5'),'AI agent channel icon missing')
ok(server.includes("de: 'AGENTES_AI'")&&server.includes("para: 'ADMIN'"),'legacy producer fixture changed; reassess bridge assumptions')
ok(rollback.includes('drop trigger if exists trg_aos_notification_legacy_bridge_v1'),'legacy bridge trigger rollback missing')
ok(rollback.includes('drop function if exists public.aos_notification_legacy_bridge_v1'),'legacy bridge function rollback missing')
ok(rollback.includes("event_type in ('AGENT_ALERT','LEGACY_NOTIFICATION')"),'legacy policies rollback missing')

console.log('S15 legacy notification bridge contract PASS')
