'use strict'
const fs=require('fs'),path=require('path')
const root=path.resolve(__dirname,'../..')
const sql=fs.readFileSync(path.join(root,'supabase/migrations/20260817224600_s15_topbar_notification_bridge.sql'),'utf8')
const rollback=fs.readFileSync(path.join(root,'supabase/rollback/20260817224600_s15_topbar_notification_bridge_rollback.sql'),'utf8')
const app=fs.readFileSync(path.join(root,'app/public/app.html'),'utf8')
function ok(v,m){if(!v){console.error('S15 TOPBAR CONTRACT FAIL:',m);process.exit(1)}}
ok(app.includes("_rpc('aos_list_notificaciones'"),'app shell no longer calls list-notifications compatibility RPC')
ok(app.includes("_rpc('aos_mark_notif_read'"),'app shell no longer calls mark-read compatibility RPC')
ok(sql.includes('create or replace function public.aos_list_notificaciones'),'topbar list RPC missing')
ok(sql.includes('aos_notification_resolve_user_v1(p_id_asesor)'),'topbar must resolve canonical user identity')
ok(sql.includes("n.para_user_id=uid"),'topbar must filter direct recipient rows')
ok(sql.includes("upper(coalesce(n.para,''))='ADMIN' and is_admin"),'ADMIN legacy alias compatibility missing')
ok(sql.includes("'unreadNotifs'" )&&sql.includes("'unreadMsgs'" )&&sql.includes("'items'"),'topbar response contract fields missing')
ok(sql.includes("'tsLeido'" )&&sql.includes("'cuerpo'" )&&sql.includes("'fecha'" )&&sql.includes("'hora'"),'topbar item compatibility fields missing')
ok(sql.includes('create or replace function public.aos_mark_notif_read'),'topbar mark-read bridge missing')
ok(rollback.includes('drop function if exists public.aos_list_notificaciones'),'topbar list rollback missing')
ok(rollback.includes('drop function if exists public.aos_mark_notif_read'),'topbar mark-read rollback missing')
console.log('S15 topbar bridge contract PASS')
