-- ASCENDA OS — Zero-Cost Staging
-- Minimal synthetic schema contract for Sales Intelligence Phase A.
-- Contains no production records or patient data.
-- The self-hosted runner may restore an old local Supabase backup; reset only
-- the synthetic public schema so every contract starts from deterministic state.

DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;

CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

CREATE TABLE public.aos_ventas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha date NOT NULL,
  nombres text,
  apellidos text,
  dni text,
  celular text,
  tratamiento text,
  descripcion text,
  pago text,
  monto numeric(14,2) NOT NULL DEFAULT 0,
  estado_pago text,
  asesor text,
  atendio text,
  sede text,
  numero_limpio text,
  nro_doc text,
  estado_doc text,
  tipo_comprobante text,
  tipo text,
  venta_id text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_zcs_ventas_fecha ON public.aos_ventas(fecha);
CREATE INDEX idx_zcs_ventas_sede_fecha ON public.aos_ventas(sede, fecha);
CREATE INDEX idx_zcs_ventas_asesor_fecha ON public.aos_ventas(asesor, fecha);

CREATE TABLE public.aos_metas_ventas (
  periodo text PRIMARY KEY,
  meta numeric(14,2) NOT NULL DEFAULT 0
);

CREATE TABLE public.aos_auditoria_ediciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tabla text NOT NULL,
  registro_id text NOT NULL,
  campo text NOT NULL,
  valor_anterior text,
  valor_nuevo text,
  editado_por text,
  origen text,
  created_at timestamptz NOT NULL DEFAULT now()
);


-- Synthetic Auth/2FA contract for the level-1 canary.
-- No production identities, credentials or patient data.
CREATE TABLE public.aos_auth_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  usuario text NOT NULL,
  email text,
  codigo text NOT NULL,
  usado boolean NOT NULL DEFAULT false,
  expira_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.aos_rrhh (
  codigo_asesor text PRIMARY KEY,
  nombre text NOT NULL,
  apellido text,
  puesto text,
  sede text,
  usuario text,
  password_hash text,
  permisos jsonb NOT NULL DEFAULT '{}'::jsonb,
  estado text NOT NULL DEFAULT 'ACTIVO'
);

CREATE TABLE public.aos_usuarios (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  codigo_asesor text UNIQUE NOT NULL,
  nombre text NOT NULL,
  email text,
  rol text NOT NULL DEFAULT 'asesor',
  paneles_acceso text[] NOT NULL DEFAULT ARRAY[]::text[],
  avatar_url text,
  nivel_jerarquia integer,
  acceso_geo text,
  sedes_permitidas text[] NOT NULL DEFAULT ARRAY[]::text[],
  area text,
  cargo text,
  two_factor boolean NOT NULL DEFAULT false,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.aos_paneles_disponibles (
  id text PRIMARY KEY,
  nombre text NOT NULL,
  icono text DEFAULT '📄',
  categoria text DEFAULT 'general',
  orden integer DEFAULT 0,
  descripcion text DEFAULT ''
);

CREATE TABLE public.aos_cia_admin_sessions (
  token_hash text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.aos_usuarios(id) ON DELETE CASCADE,
  usuario text NOT NULL,
  expires_at timestamptz NOT NULL,
  last_used_at timestamptz,
  revoked boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  source_auth_code_id uuid REFERENCES public.aos_auth_codes(id)
);

CREATE TABLE public.aos_security_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  usuario text,
  accion text NOT NULL,
  detalles jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
