-- ASCENDA OS — Zero-Cost Staging
-- Minimal synthetic schema contract for Sales Intelligence Phase A.
-- Contains no production records or patient data.

CREATE TABLE public.aos_ventas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha date NOT NULL,
  nombres text,
  apellidos text,
  dni text,
  celular text,
  tratamiento text,
  descripcion text,
  pago text,
  monto numeric(14,2) NOT NULL DEFAULT 0,
  estado_pago text,
  asesor text,
  atendio text,
  sede text,
  numero_limpio text,
  nro_doc text,
  estado_doc text,
  tipo_comprobante text,
  tipo text,
  venta_id text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_zcs_ventas_fecha ON public.aos_ventas(fecha);
CREATE INDEX idx_zcs_ventas_sede_fecha ON public.aos_ventas(sede, fecha);
CREATE INDEX idx_zcs_ventas_asesor_fecha ON public.aos_ventas(asesor, fecha);

CREATE TABLE public.aos_metas_ventas (
  periodo text PRIMARY KEY,
  meta numeric(14,2) NOT NULL DEFAULT 0
);

CREATE TABLE public.aos_auditoria_ediciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tabla text NOT NULL,
  registro_id text NOT NULL,
  campo text NOT NULL,
  valor_anterior text,
  valor_nuevo text,
  editado_por text,
  origen text,
  created_at timestamptz NOT NULL DEFAULT now()
);
