-- Synthetic canonical source contracts for WA-4A isolated TEST only.
create table public.aos_catalogo_servicios(
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  nombre_corto text,
  tipo text default 'SERVICIO',
  categoria text,
  descripcion_comercial text,
  beneficios text,
  duracion_sesion text,
  num_sesiones text,
  frecuencia text,
  precio_base numeric,
  precio_oferta numeric,
  requiere_doctora boolean default false,
  requiere_enfermeria boolean default false,
  tags text,
  estado text default 'ACTIVO',
  faqs jsonb default '[]'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table public.aos_promociones(
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  descripcion text,
  tipo_descuento text default 'porcentaje',
  valor_descuento numeric default 0,
  segmentos text[] default '{}',
  tratamientos text[] default '{}',
  vigencia_inicio date,
  vigencia_fin date,
  codigo text,
  activa boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table public.aos_sedes_geo(
  id bigint generated by default as identity primary key,
  nombre text not null,
  direccion text,
  telefono text,
  maps_link text,
  horario_lv text,
  horario_finde text,
  activa boolean default true
);

create table public.aos_config_horarios(
  id uuid primary key default gen_random_uuid(),
  sede text not null,
  dia_semana integer not null,
  hora_apertura time not null,
  hora_cierre time not null,
  activo boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table public.aos_catalogo_categorias(
  id text primary key default gen_random_uuid()::text,
  nombre text not null,
  descripcion_comercial text,
  beneficios text,
  faqs jsonb default '[]'::jsonb,
  estado text default 'ACTIVO',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

grant select on public.aos_catalogo_servicios,public.aos_promociones,public.aos_sedes_geo,public.aos_config_horarios,public.aos_catalogo_categorias to service_role;

insert into public.aos_catalogo_servicios(id,nombre,nombre_corto,tipo,categoria,descripcion_comercial,beneficios,duracion_sesion,num_sesiones,frecuencia,precio_base,precio_oferta,faqs,tags,updated_at) values
('10000000-0000-4000-8000-000000000001','Botox Test','Botox','SERVICIO','Facial','Descripción comercial aprobada','Beneficio aprobado','30 min','1','Según evaluación',500,450,'[{"q":"¿Dura?","a":"La duración depende del protocolo aprobado."}]','botox arrugas',now()),
('10000000-0000-4000-8000-000000000002','Servicio Stale','Stale','SERVICIO','Facial','Dato demasiado antiguo','Antiguo','45 min','1',null,300,null,'[]','stale',now()-interval '200 days'),
('10000000-0000-4000-8000-000000000003','Laser Conflict','Laser','SERVICIO','Laser','Versión A','A','30 min','1',null,700,null,'[]','laser',now()),
('10000000-0000-4000-8000-000000000004','Laser Conflict','Laser','SERVICIO','Laser','Versión B','B','30 min','1',null,900,null,'[]','laser',now());

insert into public.aos_promociones(id,nombre,descripcion,tipo_descuento,valor_descuento,tratamientos,codigo,vigencia_inicio,vigencia_fin,activa,updated_at) values
('20000000-0000-4000-8000-000000000001','Promo Test','Promo vigente','porcentaje',10,array['Botox Test'],'PROMO10',current_date-1,current_date+7,true,now()),
('20000000-0000-4000-8000-000000000002','Promo Expirada','No debe responderse','porcentaje',50,array['Botox Test'],'OLD50',current_date-30,current_date-1,true,now());

insert into public.aos_sedes_geo(nombre,direccion,telefono,maps_link,horario_lv,horario_finde,activa) values
('SAN_ISIDRO','Av. Test 100','999 111 222','https://maps.example/test','10:30-20:30','09:30-18:00',true),
('MIRAFLORES_TEST','Av. Test 200','999 333 444','https://maps.example/test2','09:00-18:00','09:00-18:00',true);

insert into public.aos_config_horarios(id,sede,dia_semana,hora_apertura,hora_cierre,activo,updated_at) values
('30000000-0000-4000-8000-000000000001','SAN ISIDRO',1,'09:00','19:00',true,now()),
('30000000-0000-4000-8000-000000000002','SAN ISIDRO',6,'09:00','19:00',true,now()),
('30000000-0000-4000-8000-000000000003','MIRAFLORES TEST',1,'09:00','18:00',true,now());

insert into public.aos_catalogo_categorias(id,nombre,descripcion_comercial,beneficios,faqs,estado,updated_at) values
('cat-facial','Facial','Información genérica de categoría','Beneficio genérico','[{"q":"FAQ","a":"Respuesta genérica"}]','ACTIVO',now());
